import { randomUUID } from "node:crypto";

import { createServiceRoleClient } from "@/lib/supabase/service-role";

const BUCKET = "voice-audio";

/**
 * Uploads a generated MP3 Buffer to the voice-audio bucket and returns its
 * public URL — the storage half of both the admin preview-seed flow
 * (voices-actions.ts) and the on-demand lesson-audio flow (voice-audio.ts).
 * Uses the service-role client (bypasses the bucket's admin-only RLS
 * policies) because the on-demand path is triggered by an ordinary
 * learner's session, not an admin one — same reasoning as
 * voice_audio_cache's own service-role writes.
 *
 * `cacheControl` was left at the Supabase JS SDK's own default (a mere
 * `max-age=3600`, i.e. 1 hour) until 2026-09-11 — found while diagnosing
 * reader reports of some sentences' audio audibly stalling before playing:
 * every path here is content-addressed and written exactly once
 * (`generatedClipPath`'s random UUID + `upsert: false`), so a clip already
 * uploaded to a given path can never change under it. A 1-hour cache
 * lifetime for content that's actually permanent means a clip a learner (or
 * a CDN edge node) fetched once still falls out of cache and forces a cold
 * refetch from Storage well within the same reading session — exactly the
 * kind of intermittent, "only some sentences" slowdown reported live. Set
 * to a year (the standard "may as well be forever" value for immutable
 * assets) so a clip fetched once stays cached for the rest of a normal
 * reading session and well beyond. Only affects clips uploaded from here on
 * — Supabase Storage doesn't retroactively change an already-stored
 * object's own Cache-Control header, so existing clips keep serving with
 * the old 1-hour value until they're naturally regenerated by something
 * else (never triggered by this change, which touches no existing audio).
 */
export async function uploadVoiceClip(path: string, mp3: Buffer): Promise<string> {
  const supabase = createServiceRoleClient();

  const { error } = await supabase.storage
    .from(BUCKET)
    .upload(path, mp3, { contentType: "audio/mpeg", upsert: false, cacheControl: "31536000" });
  if (error) throw error;

  const {
    data: { publicUrl },
  } = supabase.storage.from(BUCKET).getPublicUrl(path);
  return publicUrl;
}

/** A fresh, collision-proof path for one voice's cached generated clip. */
export function generatedClipPath(voiceId: string): string {
  return `generated/${voiceId}/${randomUUID()}.mp3`;
}

/**
 * Same bucket, a separate `generated/elevenlabs/` prefix — kept apart from
 * generatedClipPath's Kokoro-oriented `generated/<voiceId>/` paths purely
 * for easy manual inspection of storage usage per provider, not because
 * either provider's clips need different access rules.
 */
export function generatedElevenLabsClipPath(voiceId: string): string {
  return `generated/elevenlabs/${voiceId}/${randomUUID()}.mp3`;
}

/** Same bucket, a separate `generated/edge-tts/` prefix — mirrors generatedElevenLabsClipPath's per-provider prefix convention for the free, zero-config Edge-TTS narration pipeline (see providers/edge-tts.ts). */
export function generatedEdgeTtsClipPath(voiceId: string): string {
  return `generated/edge-tts/${voiceId}/${randomUUID()}.mp3`;
}

/** Same bucket, a separate `generated/cartesia/` prefix — mirrors generatedAzureClipPath's per-provider prefix convention for the Cartesia narration pipeline (see providers/cartesia.ts). */
export function generatedCartesiaClipPath(voiceId: string): string {
  return `generated/cartesia/${voiceId}/${randomUUID()}.mp3`;
}

/** Same bucket, a separate `generated/hume/` prefix — mirrors generatedAzureClipPath's per-provider prefix convention for the Hume AI narration pipeline (see providers/hume.ts). */
export function generatedHumeClipPath(voiceId: string): string {
  return `generated/hume/${voiceId}/${randomUUID()}.mp3`;
}

/** The path for a voice's one admin-preview sample — deterministic (not UUID-suffixed) so re-seeding the same voice overwrites its old sample instead of accumulating orphans. */
export function samplePath(voiceId: string): string {
  return `samples/${voiceId}.mp3`;
}

/**
 * Recovers the bucket-relative path from a voice-audio public URL —
 * mirrors illustrationPathFromUrl's exact reasoning in content-actions.ts
 * (this bucket has no SELECT/list policy either, so deriving the path from
 * an already-known URL is what makes cleanup possible without one).
 */
export function voiceAudioPathFromUrl(url: string): string | null {
  const marker = `/object/public/${BUCKET}/`;
  const index = url.indexOf(marker);
  if (index === -1) return null;
  return url.slice(index + marker.length);
}

/** Best-effort delete — used when removing a voice (its sample + every cached generated clip). A failed cleanup leaves an orphaned Storage object, never a broken reference, so it's logged, not thrown. */
export async function deleteVoiceClips(paths: string[]): Promise<void> {
  if (paths.length === 0) return;
  const supabase = createServiceRoleClient();
  const { error } = await supabase.storage.from(BUCKET).remove(paths);
  if (error) console.error("[voice] deleteVoiceClips: Storage remove failed", { paths, error });
}
