/**
 * One-time (and re-runnable) backfill that pre-generates every isolated
 * word's pronunciation clip ahead of time, instead of waiting for a learner
 * to be the first person ever to click that word — see the conversation
 * that asked for this: individual word audio (voice_audio_cache, content
 * types "sentence_word"/"book_sentence_word") is otherwise only generated
 * on demand, the very first time any learner clicks a word nobody has
 * clicked before, which is the real remaining cause of an occasional word
 * click still feeling delayed even after the batched cache-lookup fix.
 *
 * Deliberately reuses the exact same claim/synthesize/upload/cache-write
 * primitives resolvePronunciationAudioAction's own generateIsolatedWordAudio
 * (src/lib/voice/voice-audio.ts) already uses in production — cacheKeyParts,
 * claimCacheRow, buildProviderSynthesisInput, clipPathForProvider,
 * uploadVoiceClip, createEdgeTtsProvider — rather than inventing a second
 * implementation, so a word generated by this script is indistinguishable
 * from one generated by a real click. NEVER touches sentence audio: it only
 * ever writes voice_audio_cache rows for the free Edge-TTS voice(s) used to
 * substitute for isolated words (see pickSubstituteVoice below, mirroring
 * pickGenderMatchedEdgeTtsVoice) — it never calls a paid provider, never
 * regenerates a sentence clip, and never touches the sentences/book_sentences
 * tables themselves.
 *
 * Run with: npx tsx scripts/backfill-word-audio.ts
 */
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
dotenv.config({ path: "C:/Looma/.env.local" });

import type { Database } from "@/types/database";

import { cacheKeyParts } from "@/lib/voice/resolution";
import {
  buildProviderSynthesisInput,
  claimCacheRow,
  clipPathForProvider,
  isStaleGenerating,
  MAX_VOICE_RETRY_ATTEMPTS,
} from "@/lib/voice/story-voice-generation";
import { uploadVoiceClip } from "@/lib/voice/storage";
import { createEdgeTtsProvider } from "@/lib/voice/providers/edge-tts";
import type { SentenceDirection } from "@/lib/voice/director-types";
import type { TTSVoiceSettings } from "@/lib/voice/provider";

const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const supabase: SupabaseClient<Database> = createClient<Database>(url, key);

const EDGE_TTS_GENERATION_VERSION = "edge-tts:sentence-word:v1";
const CONCURRENCY = 2;

const NEUTRAL_DIRECTION: Omit<SentenceDirection, "sentenceId"> = {
  emotion: "neutral",
  energy: "medium",
  pace: "normal",
  emphasisWord: null,
  pauseBefore: "none",
};
const NEUTRAL_VOICE_SETTINGS: TTSVoiceSettings = {
  stability: 0.5,
  similarityBoost: 0.75,
  style: 0,
  speed: 1,
  useSpeakerBoost: true,
};

function tokenize(target: string): string[] {
  return target.match(/\S+|\s/g) ?? [];
}
function normalizeMistakeWord(word: string): string {
  return word
    .trim()
    .toLowerCase()
    .replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, "");
}
function isTrackableWord(word: string): boolean {
  const n = normalizeMistakeWord(word);
  return n.length > 0 && /\p{L}/u.test(n);
}

interface VoiceRow {
  id: string;
  source: string;
  gender: string;
  accent: string | null;
}
interface IdVoiceIdRow {
  id: string;
  voice_id: string | null;
}
interface SectionRow {
  id: string;
  book_id: string;
}
interface SentenceRow {
  en: string;
  lesson_id: string;
}
interface BookSentenceRow {
  en: string;
  section_id: string;
}

async function fetchAll<T>(table: string, cols: string): Promise<T[]> {
  const out: T[] = [];
  let from = 0;
  const pageSize = 1000;
  for (;;) {
    const { data, error } = await supabase
      .from(table as keyof Database["public"]["Tables"])
      .select(cols)
      .range(from, from + pageSize - 1);
    if (error) throw error;
    if (!data || data.length === 0) break;
    out.push(...(data as unknown as T[]));
    if (data.length < pageSize) break;
    from += pageSize;
  }
  return out;
}

/** Mirrors pickGenderMatchedEdgeTtsVoice in voice-audio.ts (not exported there, so reimplemented here read-only). */
async function pickSubstituteVoice(gender: "female" | "male"): Promise<string> {
  const allVoices = await fetchAll<VoiceRow>("voices", "id, source, gender, accent");
  const edgeTts = allVoices.filter((v) => v.source === "edge-tts");
  const american = edgeTts
    .filter((v) => v.gender === gender && v.accent === "American")
    .sort((a, b) => (a.id < b.id ? -1 : 1))[0];
  if (american) return american.id;
  const anyMatch = edgeTts
    .filter((v) => v.gender === gender)
    .sort((a, b) => (a.id < b.id ? -1 : 1))[0];
  if (!anyMatch) throw new Error(`No edge-tts voice registered for gender ${gender}`);
  return anyMatch.id;
}

async function collectNeededWords(): Promise<Map<string, Set<string>>> {
  const femaleSub = await pickSubstituteVoice("female");
  const maleSub = await pickSubstituteVoice("male");

  const allVoices = await fetchAll<VoiceRow>("voices", "id, gender");
  const voiceGender = new Map<string, string>(allVoices.map((v) => [v.id, v.gender]));

  const lessons = await fetchAll<IdVoiceIdRow>("lessons", "id, voice_id");
  const lessonGender = new Map<string, string>();
  for (const l of lessons)
    lessonGender.set(l.id, (l.voice_id && voiceGender.get(l.voice_id)) ?? "female");

  const books = await fetchAll<IdVoiceIdRow>("books", "id, voice_id");
  const bookGender = new Map<string, string>();
  for (const b of books)
    bookGender.set(b.id, (b.voice_id && voiceGender.get(b.voice_id)) ?? "male");

  const sections = await fetchAll<SectionRow>("book_sections", "id, book_id");
  const sectionToBook = new Map<string, string>(sections.map((s) => [s.id, s.book_id]));

  const sentences = await fetchAll<SentenceRow>("sentences", "en, lesson_id");
  const bookSentences = await fetchAll<BookSentenceRow>("book_sentences", "en, section_id");

  const wordsByVoice = new Map<string, Set<string>>([
    [femaleSub, new Set<string>()],
    [maleSub, new Set<string>()],
  ]);

  for (const s of sentences) {
    const gender = lessonGender.get(s.lesson_id) ?? "female";
    const bucket = wordsByVoice.get(gender === "male" ? maleSub : femaleSub)!;
    for (const tok of tokenize(s.en))
      if (isTrackableWord(tok)) bucket.add(normalizeMistakeWord(tok));
  }
  for (const b of bookSentences) {
    const bookId = sectionToBook.get(b.section_id);
    const gender = (bookId ? bookGender.get(bookId) : undefined) ?? "male";
    const bucket = wordsByVoice.get(gender === "male" ? maleSub : femaleSub)!;
    for (const tok of tokenize(b.en))
      if (isTrackableWord(tok)) bucket.add(normalizeMistakeWord(tok));
  }

  return wordsByVoice;
}

/** Exact mirror of generateIsolatedWordAudio in voice-audio.ts — same claim/synthesize/upload/cache-write sequence, reimplemented here read-only since that function isn't exported (deliberately, per that file's own doc comment about never exposing this as a public action). */
async function generateOne(
  word: string,
  voiceId: string,
  providerVoiceId: string,
): Promise<"generated" | "skipped" | "failed"> {
  const provider = createEdgeTtsProvider();
  const genKey = cacheKeyParts(word, voiceId, EDGE_TTS_GENERATION_VERSION);

  const { data: existingRow } = await supabase
    .from("voice_audio_cache")
    .select("id, status, attempts, updated_at")
    .eq("voice_id", voiceId)
    .eq("text_hash", genKey.textHash)
    .eq("generation_version", EDGE_TTS_GENERATION_VERSION)
    .maybeSingle();

  if (existingRow) {
    if (existingRow.status === "ready") return "skipped";
    if (existingRow.status === "generating" && !isStaleGenerating(existingRow.updated_at))
      return "skipped";
    if (existingRow.status === "failed" && existingRow.attempts >= MAX_VOICE_RETRY_ATTEMPTS)
      return "skipped";
  }

  const existingByKey = existingRow
    ? new Map([[`${voiceId}:${genKey.textHash}:${EDGE_TTS_GENERATION_VERSION}`, existingRow]])
    : new Map();
  const direction: SentenceDirection = { sentenceId: `word:${voiceId}`, ...NEUTRAL_DIRECTION };
  const claimed = await claimCacheRow(
    supabase,
    genKey,
    "edge-tts",
    direction,
    existingByKey,
    provider.name,
  );
  if (!claimed) return "skipped";

  try {
    const { text, voiceSettings } = buildProviderSynthesisInput(
      provider.name,
      direction,
      word,
      providerVoiceId,
      NEUTRAL_VOICE_SETTINGS,
    );
    const { audio, durationMs } = await provider.synthesize({
      text,
      voiceId: providerVoiceId,
      model: "edge-tts",
      voiceSettings,
    });
    const audioUrl = await uploadVoiceClip(clipPathForProvider(provider.name, voiceId), audio);
    await supabase
      .from("voice_audio_cache")
      .update({
        status: "ready",
        audio_url: audioUrl,
        duration_ms: durationMs,
        last_error: null,
        updated_at: new Date().toISOString(),
      })
      .eq("id", claimed.id);
    return "generated";
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await supabase
      .from("voice_audio_cache")
      .update({
        status: "failed",
        last_error: message.slice(0, 500),
        updated_at: new Date().toISOString(),
      })
      .eq("id", claimed.id);
    return "failed";
  }
}

async function runWithConcurrency<T>(
  items: T[],
  limit: number,
  worker: (item: T, index: number) => Promise<void>,
) {
  let next = 0;
  async function runner() {
    for (;;) {
      const index = next++;
      if (index >= items.length) return;
      await worker(items[index]!, index);
    }
  }
  await Promise.all(Array.from({ length: limit }, () => runner()));
}

async function main() {
  console.log("Collecting words that still need isolated-word audio...");
  const wordsByVoice = await collectNeededWords();

  const jobs: { word: string; voiceId: string; providerVoiceId: string }[] = [];
  const allVoices = await fetchAll<{ id: string; provider_voice_id: string }>(
    "voices",
    "id, provider_voice_id",
  );
  const providerVoiceIdById = new Map<string, string>(
    allVoices.map((v) => [v.id, v.provider_voice_id]),
  );
  for (const [voiceId, words] of wordsByVoice) {
    const providerVoiceId = providerVoiceIdById.get(voiceId);
    if (!providerVoiceId) continue;
    for (const word of words) jobs.push({ word, voiceId, providerVoiceId });
  }
  console.log(`Total (word, voice) pairs to check: ${jobs.length}`);

  let generated = 0;
  let skipped = 0;
  let failed = 0;
  let done = 0;

  await runWithConcurrency(jobs, CONCURRENCY, async ({ word, voiceId, providerVoiceId }) => {
    const outcome = await generateOne(word, voiceId, providerVoiceId);
    if (outcome === "generated") generated += 1;
    else if (outcome === "skipped") skipped += 1;
    else failed += 1;
    done += 1;
    if (done % 200 === 0 || done === jobs.length) {
      console.log(
        `Progress: ${done}/${jobs.length} — generated=${generated} skipped=${skipped} failed=${failed}`,
      );
    }
  });

  console.log("Done.");
  console.log({ total: jobs.length, generated, skipped, failed });
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
