/**
 * One-time bootstrapping tool for the Milestone 12 initial content
 * library — not part of the running app. Reads the exact same TypeScript
 * seed arrays the app already uses locally (src/data/lessons/*.ts) and
 * emits the matching SQL migration, so the database and local-fallback
 * content can never drift apart: there is one authored copy of the actual
 * sentences, not two.
 *
 * Run with: npx tsx scripts/generate-content-seed.ts
 * Output:   supabase/migrations/20250109000000_seed_initial_content.sql
 *
 * Future content growth is expected to go through the admin CMS (Milestone
 * 11), not this script — this exists to bootstrap the initial library only,
 * and can be re-run later only if the local seed files are hand-edited
 * again before a real Supabase project is linked.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { conversationLessons } from "../src/data/lessons/conversation";
import { normalLessons } from "../src/data/lessons/normal";
import { storyLessons } from "../src/data/lessons/stories";
import { unitsByMode } from "../src/data/units";
import { REQUIRED_SENTENCE_COUNT } from "../src/lib/admin/validation";
import type { Lesson, LearningMode } from "../src/types/content";

const allLessons: Lesson[] = [...normalLessons, ...storyLessons, ...conversationLessons];

// Fail loudly rather than silently emit a lesson with the wrong sentence
// count — the same rule the admin CMS enforces (validateLessonInput).
for (const lesson of allLessons) {
  const required = REQUIRED_SENTENCE_COUNT[lesson.mode];
  if (lesson.sentences.length !== required) {
    throw new Error(
      `${lesson.id} has ${lesson.sentences.length} sentences, expected exactly ${required} for mode "${lesson.mode}".`,
    );
  }
}

function escapeSql(value: string): string {
  return value.replace(/'/g, "''");
}

function sqlString(value: string): string {
  return `'${escapeSql(value)}'`;
}

function sqlNullableString(value: string | null | undefined): string {
  return value ? sqlString(value) : "null";
}

const lines: string[] = [
  "-- Milestone 12: initial curated content library.",
  "--",
  "-- Generated by scripts/generate-content-seed.ts from the same TypeScript",
  "-- arrays the app reads locally (src/data/lessons/*.ts) — there is one",
  "-- authored copy of this content, not two hand-kept-in-sync copies.",
  "--",
  "-- Idempotent by construction: every insert conflicts on a stable,",
  "-- deterministic key (levels: mode+index: lessons/sentences: their",
  '-- existing slug-style id, e.g. "normal-1", "normal-1-s1") and upserts',
  "-- rather than duplicating, so running this migration twice is a no-op.",
  "",
];

// --- Levels: only the (mode, level) pairs actually used, named from the
// same source src/data/units.ts already uses for the local-fallback UI, so
// database-backed level names never conflict with what's already shown. ---

const usedLevels = new Set<string>();
for (const lesson of allLessons) {
  usedLevels.add(`${lesson.mode}:${lesson.level}`);
}

lines.push("-- Levels");
for (const key of Array.from(usedLevels).sort()) {
  const [mode, levelStr] = key.split(":") as [LearningMode, string];
  const level = Number(levelStr);
  const unit = unitsByMode[mode].find((entry) => entry.level === level);
  if (!unit) {
    throw new Error(`No named unit found in src/data/units.ts for ${mode} level ${level}.`);
  }

  lines.push(
    `insert into levels (mode, index, title, title_ar) values (${sqlString(mode)}, ${level}, ${sqlString(unit.title)}, ${sqlString(unit.titleAr)}) on conflict (mode, index) do update set title = excluded.title, title_ar = excluded.title_ar;`,
  );
}
lines.push("");

// --- Lessons ---

lines.push("-- Lessons");
for (const lesson of allLessons) {
  const levelLookup = `(select id from levels where mode = ${sqlString(lesson.mode)} and index = ${lesson.level})`;
  lines.push(
    `insert into lessons (id, mode, level_id, order_index, title, title_ar, is_free, status, updated_at) values (${sqlString(lesson.id)}, ${sqlString(lesson.mode)}, ${levelLookup}, ${lesson.order}, ${sqlString(lesson.title)}, ${sqlString(lesson.titleAr)}, ${lesson.isFree}, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();`,
  );
}
lines.push("");

// --- Sentences: order_index is the array position, matching exactly how
// the admin CMS's saveLesson() assigns it on every save. ---

lines.push("-- Sentences");
for (const lesson of allLessons) {
  lesson.sentences.forEach((sentence, index) => {
    lines.push(
      `insert into sentences (id, lesson_id, order_index, en, ar, speaker, updated_at) values (${sqlString(sentence.id)}, ${sqlString(lesson.id)}, ${index}, ${sqlString(sentence.en)}, ${sqlString(sentence.ar)}, ${sqlNullableString(sentence.speaker)}, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, updated_at = now();`,
    );
  });
}
lines.push("");

const sql = lines.join("\n");
const outputPath = resolve(
  __dirname,
  "../supabase/migrations/20250109000000_seed_initial_content.sql",
);
writeFileSync(outputPath, sql, "utf8");

console.log(`Wrote ${allLessons.length} lessons and ${usedLevels.size} levels to ${outputPath}`);
