-- Stories content-quality overhaul: rewrites six stories that still read
-- like textbook exercises (repetitive "X did Y" sentences, predictable
-- beats, generic endings) into natural, connected mini-narratives — see
-- scripts/scratch/stories-quality-report.txt and this change's own report
-- for the full audit and per-story reasoning.
--
-- Touches, independently reversible per story (restore from the
-- pre-change snapshot noted in the report; this migration only updates
-- existing rows in place plus two explicit deletes, no bulk rewrite):
--   story-1  "A New Neighbor"      12 -> 11 sentences
--   story-2  "The Job Interview"   12 sentences, new ending + description
--   story-3  "The Missing Shoe"    12 -> 11 sentences
--   story-7  "The Wrong Coffee"    12 sentences
--   story-9  "The Strange Package" 12 sentences
--   story-12 "A Seat at the Café"  12 sentences
--
-- Every other published Story was read end-to-end during the same audit
-- and judged already natural/engaging — deliberately left untouched.
--
-- Only updates sentences.en/ar/word_translations (legacy Arabic columns)
-- and lessons.description/description_ar for story-2, matching the
-- pattern of 20250136000000_stories_sync_admin_authored.sql. The Spanish
-- and Turkish content_translations layer for these sentences was applied
-- directly against the live project (see that change's own report) and
-- is not reproduced here, consistent with how this file's Arabic-only
-- scope has always worked for a fresh database.
begin;

update lessons set
  description = 'Ahmed is running late for the biggest interview of his year — and decides honesty beats a perfect excuse.',
  description_ar = 'يتأخر أحمد عن أهم مقابلة عمل في عامه، ويقرر أن الصدق أفضل من عذر مثالي.',
  updated_at = now()
where id = 'story-2';

update sentences set en = 'A loud bump against the wall woke Layla up on Saturday morning.', ar = 'أيقظ صوت اصطدام قوي بالحائط ليلى صباح يوم السبت.', word_translations = '[{"ar":"واحد","en":"A"},{"ar":"عالٍ","en":"loud"},{"ar":"اصطدام","en":"bump"},{"ar":"بـ","en":"against"},{"ar":"الـ","en":"the"},{"ar":"الحائط","en":"wall"},{"ar":"أيقظ","en":"woke"},{"ar":"ليلى","en":"Layla"},{"ar":"تمامًا","en":"up"},{"ar":"في","en":"on"},{"ar":"السبت","en":"Saturday"},{"ar":"صباح","en":"morning."}]'::jsonb, updated_at = now() where id = 'story-1-s1';
update sentences set en = 'She opened her door and saw boxes everywhere in the hallway.', ar = 'فتحت بابها ورأت صناديق في كل مكان في الممر.', word_translations = '[{"ar":"هي","en":"She"},{"ar":"فتحت","en":"opened"},{"ar":"لها","en":"her"},{"ar":"بابها","en":"door"},{"ar":"و","en":"and"},{"ar":"رأت","en":"saw"},{"ar":"صناديق","en":"boxes"},{"ar":"في كل مكان","en":"everywhere"},{"ar":"في","en":"in"},{"ar":"الـ","en":"the"},{"ar":"الممر","en":"hallway."}]'::jsonb, updated_at = now() where id = 'story-1-s2';
update sentences set en = 'A woman was struggling to carry a heavy one up the stairs.', ar = 'كانت امرأة تكافح لحمل صندوق ثقيل إلى أعلى الدرج.', word_translations = '[{"ar":"واحدة","en":"A"},{"ar":"امرأة","en":"woman"},{"ar":"كانت","en":"was"},{"ar":"تكافح","en":"struggling"},{"ar":"لـ","en":"to"},{"ar":"حمل","en":"carry"},{"ar":"واحد","en":"a"},{"ar":"ثقيل","en":"heavy"},{"ar":"واحد","en":"one"},{"ar":"إلى أعلى","en":"up"},{"ar":"الـ","en":"the"},{"ar":"الدرج","en":"stairs."}]'::jsonb, updated_at = now() where id = 'story-1-s3';
update sentences set en = '"Do you want some help with that?" Layla asked.', ar = 'سألت ليلى: "هل تريدين بعض المساعدة في هذا؟"', word_translations = '[{"ar":"\"هل","en":"\"Do"},{"ar":"أنت","en":"you"},{"ar":"تريدين","en":"want"},{"ar":"بعض","en":"some"},{"ar":"مساعدة","en":"help"},{"ar":"في","en":"with"},{"ar":"ذلك؟\"","en":"that?\""},{"ar":"ليلى","en":"Layla"},{"ar":"سألت","en":"asked."}]'::jsonb, updated_at = now() where id = 'story-1-s4';
update sentences set en = 'The woman looked up, relieved, and said, "Please, yes."', ar = 'نظرت المرأة إليها بارتياح وقالت: "نعم، أرجوك."', word_translations = '[{"ar":"الـ","en":"The"},{"ar":"امرأة","en":"woman"},{"ar":"نظرت","en":"looked"},{"ar":"إلى أعلى،","en":"up,"},{"ar":"بارتياح،","en":"relieved,"},{"ar":"و","en":"and"},{"ar":"قالت،","en":"said,"},{"ar":"\"من فضلك،","en":"\"Please,"},{"ar":"نعم.\"","en":"yes.\""}]'::jsonb, updated_at = now() where id = 'story-1-s5';
update sentences set en = 'Her name was Noor, and she had just moved from another city.', ar = 'كان اسمها نور، وكانت قد انتقلت للتو من مدينة أخرى.', word_translations = '[{"ar":"ها","en":"Her"},{"ar":"اسم","en":"name"},{"ar":"كان","en":"was"},{"ar":"نور،","en":"Noor,"},{"ar":"و","en":"and"},{"ar":"هي","en":"she"},{"ar":"كانت","en":"had"},{"ar":"للتو","en":"just"},{"ar":"انتقلت","en":"moved"},{"ar":"من","en":"from"},{"ar":"أخرى","en":"another"},{"ar":"مدينة.","en":"city."}]'::jsonb, updated_at = now() where id = 'story-1-s6';
update sentences set en = 'Together they carried the last boxes into the new apartment.', ar = 'حملتا معًا الصناديق الأخيرة إلى الشقة الجديدة.', word_translations = '[{"ar":"معًا","en":"Together"},{"ar":"هما","en":"they"},{"ar":"حملتا","en":"carried"},{"ar":"الـ","en":"the"},{"ar":"الأخيرة","en":"last"},{"ar":"صناديق","en":"boxes"},{"ar":"إلى","en":"into"},{"ar":"الـ","en":"the"},{"ar":"الجديدة","en":"new"},{"ar":"شقة.","en":"apartment."}]'::jsonb, updated_at = now() where id = 'story-1-s7';
update sentences set en = 'Noor found her kettle first and made two cups of tea.', ar = 'وجدت نور غلايتها أولاً وأعدت كوبين من الشاي.', word_translations = '[{"ar":"نور","en":"Noor"},{"ar":"وجدت","en":"found"},{"ar":"لها","en":"her"},{"ar":"غلايتها","en":"kettle"},{"ar":"أولاً","en":"first"},{"ar":"و","en":"and"},{"ar":"أعدت","en":"made"},{"ar":"كوبين","en":"two"},{"ar":"أكواب","en":"cups"},{"ar":"من","en":"of"},{"ar":"شاي.","en":"tea."}]'::jsonb, updated_at = now() where id = 'story-1-s8';
update sentences set en = 'They sat on unopened boxes and talked for almost an hour.', ar = 'جلستا على صناديق لم تُفتح وتحدثتا لما يقارب ساعة.', word_translations = '[{"ar":"هما","en":"They"},{"ar":"جلستا","en":"sat"},{"ar":"على","en":"on"},{"ar":"لم تُفتح","en":"unopened"},{"ar":"صناديق","en":"boxes"},{"ar":"و","en":"and"},{"ar":"تحدثتا","en":"talked"},{"ar":"لـ","en":"for"},{"ar":"تقريبًا","en":"almost"},{"ar":"واحدة","en":"an"},{"ar":"ساعة.","en":"hour."}]'::jsonb, updated_at = now() where id = 'story-1-s9';
update sentences set en = 'Noor admitted she didn''t know a single person in the building yet.', ar = 'اعترفت نور بأنها لا تعرف حتى الآن شخصًا واحدًا في المبنى.', word_translations = '[{"ar":"نور","en":"Noor"},{"ar":"اعترفت","en":"admitted"},{"ar":"بأنها","en":"she"},{"ar":"لم","en":"didn''t"},{"ar":"تعرف","en":"know"},{"ar":"واحد","en":"a"},{"ar":"واحدًا","en":"single"},{"ar":"شخصًا","en":"person"},{"ar":"في","en":"in"},{"ar":"الـ","en":"the"},{"ar":"المبنى","en":"building"},{"ar":"حتى الآن.","en":"yet."}]'::jsonb, updated_at = now() where id = 'story-1-s10';
update sentences set en = '"Well, now you know one," Layla said, and they both laughed.', ar = 'قالت ليلى: "حسنًا، الآن تعرفين واحدًا،" وضحكتا معًا.', word_translations = '[{"ar":"\"حسنًا،","en":"\"Well,"},{"ar":"الآن","en":"now"},{"ar":"أنت","en":"you"},{"ar":"تعرفين","en":"know"},{"ar":"واحدًا،\"","en":"one,\""},{"ar":"ليلى","en":"Layla"},{"ar":"قالت،","en":"said,"},{"ar":"و","en":"and"},{"ar":"هما","en":"they"},{"ar":"معًا","en":"both"},{"ar":"ضحكتا.","en":"laughed."}]'::jsonb, updated_at = now() where id = 'story-1-s11';
update sentences set en = 'Every table in the café was taken by the time Noor got there for lunch.', ar = 'كانت جميع الطاولات في المقهى مشغولة بحلول الوقت الذي وصلت فيه نور لتناول الغداء.', word_translations = '[{"ar":"كل","en":"Every"},{"ar":"طاولة","en":"table"},{"ar":"في","en":"in"},{"ar":"الـ","en":"the"},{"ar":"المقهى","en":"café"},{"ar":"كانت","en":"was"},{"ar":"مشغولة","en":"taken"},{"ar":"بحلول","en":"by"},{"ar":"الـ","en":"the"},{"ar":"الوقت","en":"time"},{"ar":"نور","en":"Noor"},{"ar":"وصلت","en":"got"},{"ar":"هناك","en":"there"},{"ar":"لـ","en":"for"},{"ar":"الغداء.","en":"lunch."}]'::jsonb, updated_at = now() where id = 'story-12-s1';
update sentences set en = 'The only free seat was across from a stranger reading by the window.', ar = 'كان المقعد الوحيد الفارغ مقابل غريب يقرأ بجانب النافذة.', word_translations = '[{"ar":"الـ","en":"The"},{"ar":"الوحيد","en":"only"},{"ar":"الفارغ","en":"free"},{"ar":"المقعد","en":"seat"},{"ar":"كان","en":"was"},{"ar":"مقابل","en":"across"},{"ar":"-","en":"from"},{"ar":"-","en":"a"},{"ar":"غريب","en":"stranger"},{"ar":"يقرأ","en":"reading"},{"ar":"بجانب","en":"by"},{"ar":"الـ","en":"the"},{"ar":"النافذة.","en":"window."}]'::jsonb, updated_at = now() where id = 'story-12-s2';
update sentences set en = '"Would you mind if I sat here?" she asked, and he waved her over without looking up.', ar = 'سألته: "هل تمانع إن جلست هنا؟" فأشار لها بالجلوس دون أن يرفع نظره.', word_translations = '[{"ar":"سألته:","en":"\"Would"},{"ar":"\"هل","en":"you"},{"ar":"تمانع","en":"mind"},{"ar":"إن","en":"if"},{"ar":"-","en":"I"},{"ar":"جلست","en":"sat"},{"ar":"هنا؟\"","en":"here?\""},{"ar":"-","en":"she"},{"ar":"فـ","en":"asked,"},{"ar":"-","en":"and"},{"ar":"أشار لها","en":"he"},{"ar":"بالجلوس","en":"waved"},{"ar":"-","en":"her"},{"ar":"-","en":"over"},{"ar":"دون","en":"without"},{"ar":"أن يرفع","en":"looking"},{"ar":"نظره.","en":"up."}]'::jsonb, updated_at = now() where id = 'story-12-s3';
update sentences set en = 'They ordered coffee and sat mostly in silence, each in their own world.', ar = 'طلبا القهوة وجلسا في صمت غالبًا، كل واحد منهما في عالمه الخاص.', word_translations = '[{"ar":"هما","en":"They"},{"ar":"طلبا","en":"ordered"},{"ar":"القهوة","en":"coffee"},{"ar":"و","en":"and"},{"ar":"جلسا","en":"sat"},{"ar":"غالبًا","en":"mostly"},{"ar":"في","en":"in"},{"ar":"صمت،","en":"silence,"},{"ar":"كل واحد منهما","en":"each"},{"ar":"في","en":"in"},{"ar":"-","en":"their"},{"ar":"الخاص","en":"own"},{"ar":"عالمهم.","en":"world."}]'::jsonb, updated_at = now() where id = 'story-12-s4';
update sentences set en = 'Noor pulled out her own book, and the cover caught the man''s attention.', ar = 'أخرجت نور كتابها الخاص، فلفت الغلاف انتباه الرجل.', word_translations = '[{"ar":"نور","en":"Noor"},{"ar":"أخرجت","en":"pulled"},{"ar":"-","en":"out"},{"ar":"-","en":"her"},{"ar":"الخاص","en":"own"},{"ar":"كتابها،","en":"book,"},{"ar":"فـ","en":"and"},{"ar":"-","en":"the"},{"ar":"الغلاف","en":"cover"},{"ar":"لفت","en":"caught"},{"ar":"-","en":"the"},{"ar":"الرجل","en":"man''s"},{"ar":"انتباه.","en":"attention."}]'::jsonb, updated_at = now() where id = 'story-12-s5';
update sentences set en = '"Wait," he said, "that''s my favorite book. I''ve read it three times."', ar = 'قال: "لحظة، هذا كتابي المفضل. قرأته ثلاث مرات."', word_translations = '[{"ar":"\"لحظة،","en":"\"Wait,\""},{"ar":"هو","en":"he"},{"ar":"قال،","en":"said,"},{"ar":"\"هذا","en":"\"that''s"},{"ar":"كتابي","en":"my"},{"ar":"المفضل","en":"favorite"},{"ar":"كتاب.","en":"book."},{"ar":"-","en":"I''ve"},{"ar":"قرأته","en":"read"},{"ar":"-","en":"it"},{"ar":"ثلاث","en":"three"},{"ar":"مرات.\"","en":"times.\""}]'::jsonb, updated_at = now() where id = 'story-12-s6';
update sentences set en = 'She admitted she was only on chapter two and still deciding how she felt about it.', ar = 'اعترفت بأنها لا تزال في الفصل الثاني وما زالت تقرر رأيها فيه.', word_translations = '[{"ar":"هي","en":"She"},{"ar":"اعترفت","en":"admitted"},{"ar":"بأنها","en":"she"},{"ar":"-","en":"was"},{"ar":"فقط","en":"only"},{"ar":"في","en":"on"},{"ar":"الفصل","en":"chapter"},{"ar":"الثاني","en":"two"},{"ar":"و","en":"and"},{"ar":"لا تزال","en":"still"},{"ar":"تقرر","en":"deciding"},{"ar":"كيف","en":"how"},{"ar":"-","en":"she"},{"ar":"شعرت","en":"felt"},{"ar":"حيال","en":"about"},{"ar":"ذلك.","en":"it."}]'::jsonb, updated_at = now() where id = 'story-12-s7';
update sentences set en = 'That was enough to start a conversation neither of them had planned on having.', ar = 'كان ذلك كافيًا لبدء حديث لم يخطط له أي منهما.', word_translations = '[{"ar":"كان","en":"That"},{"ar":"ذلك","en":"was"},{"ar":"كافيًا","en":"enough"},{"ar":"لـ","en":"to"},{"ar":"بدء","en":"start"},{"ar":"واحد","en":"a"},{"ar":"حديث","en":"conversation"},{"ar":"لا","en":"neither"},{"ar":"أي","en":"of"},{"ar":"منهما","en":"them"},{"ar":"خطط","en":"had"},{"ar":"له","en":"planned"},{"ar":"-","en":"on"},{"ar":"-.","en":"having."}]'::jsonb, updated_at = now() where id = 'story-12-s8';
update sentences set en = 'Twenty minutes later, their coffee had gone cold and neither of them had noticed.', ar = 'بعد عشرين دقيقة، برد قهوتهما ولم يلاحظ أي منهما ذلك.', word_translations = '[{"ar":"عشرين","en":"Twenty"},{"ar":"دقيقة","en":"minutes"},{"ar":"بعد،","en":"later,"},{"ar":"-","en":"their"},{"ar":"قهوتهما","en":"coffee"},{"ar":"-","en":"had"},{"ar":"ذهبت","en":"gone"},{"ar":"باردة","en":"cold"},{"ar":"و","en":"and"},{"ar":"لا","en":"neither"},{"ar":"أحد","en":"of"},{"ar":"منهما","en":"them"},{"ar":"-","en":"had"},{"ar":"لاحظ.","en":"noticed."}]'::jsonb, updated_at = now() where id = 'story-12-s9';
update sentences set en = 'He recommended a chapter she wasn''t ready for yet and refused to say why.', ar = 'أوصاها بفصل لم تكن مستعدة له بعد، ورفض أن يخبرها لماذا.', word_translations = '[{"ar":"أوصاها","en":"He"},{"ar":"بـ","en":"recommended"},{"ar":"-","en":"a"},{"ar":"فصل","en":"chapter"},{"ar":"-","en":"she"},{"ar":"لم تكن","en":"wasn''t"},{"ar":"مستعدة","en":"ready"},{"ar":"له","en":"for"},{"ar":"بعد،","en":"yet"},{"ar":"و","en":"and"},{"ar":"رفض","en":"refused"},{"ar":"أن","en":"to"},{"ar":"يخبرها","en":"say"},{"ar":"لماذا.","en":"why."}]'::jsonb, updated_at = now() where id = 'story-12-s10';
update sentences set en = 'They exchanged numbers, agreeing to compare notes once she''d caught up.', ar = 'تبادلا أرقام الهاتف، واتفقا على مقارنة آرائهما بعد أن تلحق بالقراءة.', word_translations = '[{"ar":"تبادلا","en":"They"},{"ar":"أرقام الهاتف،","en":"exchanged"},{"ar":"-","en":"numbers,"},{"ar":"واتفقا","en":"agreeing"},{"ar":"على","en":"to"},{"ar":"مقارنة","en":"compare"},{"ar":"آرائهما","en":"notes"},{"ar":"بعد أن","en":"once"},{"ar":"تلحق","en":"she''d"},{"ar":"بالقراءة","en":"caught"},{"ar":"-.","en":"up."}]'::jsonb, updated_at = now() where id = 'story-12-s11';
update sentences set en = 'Noor finished the book that weekend, mostly just to find out what he meant.', ar = 'أنهت نور الكتاب في تلك العطلة الأسبوعية، فقط لتعرف ما الذي كان يقصده.', word_translations = '[{"ar":"نور","en":"Noor"},{"ar":"أنهت","en":"finished"},{"ar":"الـ","en":"the"},{"ar":"الكتاب","en":"book"},{"ar":"في","en":"that"},{"ar":"تلك العطلة الأسبوعية،","en":"weekend,"},{"ar":"-","en":"mostly"},{"ar":"فقط","en":"just"},{"ar":"لـ","en":"to"},{"ar":"تعرف","en":"find"},{"ar":"-","en":"out"},{"ar":"ما","en":"what"},{"ar":"-","en":"he"},{"ar":"الذي كان يقصده.","en":"meant."}]'::jsonb, updated_at = now() where id = 'story-12-s12';
update sentences set en = 'Ahmed''s alarm didn''t go off, and he woke up with twenty minutes to cross town for his interview.', ar = 'لم يرن منبه أحمد، فاستيقظ ليجد أمامه عشرين دقيقة فقط ليقطع المدينة ويصل إلى مقابلته.', word_translations = '[{"ar":"أحمد","en":"Ahmed''s"},{"ar":"منبه","en":"alarm"},{"ar":"لم","en":"didn''t"},{"ar":"يرن","en":"go"},{"ar":"-","en":"off,"},{"ar":"و","en":"and"},{"ar":"هو","en":"he"},{"ar":"استيقظ","en":"woke"},{"ar":"-","en":"up"},{"ar":"مع","en":"with"},{"ar":"عشرين","en":"twenty"},{"ar":"دقيقة","en":"minutes"},{"ar":"لـ","en":"to"},{"ar":"يقطع","en":"cross"},{"ar":"المدينة","en":"town"},{"ar":"من أجل","en":"for"},{"ar":"ـه","en":"his"},{"ar":"مقابلة.","en":"interview."}]'::jsonb, updated_at = now() where id = 'story-2-s1';
update sentences set en = 'He grabbed his jacket and ran out still buttoning his shirt on the stairs.', ar = 'خطف سترته وخرج مسرعًا وهو لا يزال يزرر قميصه على الدرج.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"خطف","en":"grabbed"},{"ar":"سترته","en":"his"},{"ar":"سترة","en":"jacket"},{"ar":"و","en":"and"},{"ar":"ركض","en":"ran"},{"ar":"خارجًا","en":"out"},{"ar":"لا يزال","en":"still"},{"ar":"يزرر","en":"buttoning"},{"ar":"قميصه","en":"his"},{"ar":"قميص","en":"shirt"},{"ar":"على","en":"on"},{"ar":"الـ","en":"the"},{"ar":"الدرج.","en":"stairs."}]'::jsonb, updated_at = now() where id = 'story-2-s2';
update sentences set en = 'The bus pulled away just as he reached the stop.', ar = 'انطلقت الحافلة بعيدًا في اللحظة التي وصل فيها إلى المحطة.', word_translations = '[{"ar":"الـ","en":"The"},{"ar":"الحافلة","en":"bus"},{"ar":"انطلقت","en":"pulled"},{"ar":"بعيدًا","en":"away"},{"ar":"تمامًا","en":"just"},{"ar":"بينما","en":"as"},{"ar":"هو","en":"he"},{"ar":"وصل","en":"reached"},{"ar":"الـ","en":"the"},{"ar":"المحطة.","en":"stop."}]'::jsonb, updated_at = now() where id = 'story-2-s3';
update sentences set en = 'He ended up jogging the last four blocks in dress shoes.', ar = 'انتهى به الأمر بالركض في آخر أربعة أحياء وهو يرتدي حذاء رسميًا.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"انتهى به الأمر","en":"ended"},{"ar":"تمامًا","en":"up"},{"ar":"بالركض","en":"jogging"},{"ar":"الـ","en":"the"},{"ar":"آخر","en":"last"},{"ar":"أربعة","en":"four"},{"ar":"أحياء","en":"blocks"},{"ar":"في","en":"in"},{"ar":"رسمي","en":"dress"},{"ar":"حذاء.","en":"shoes."}]'::jsonb, updated_at = now() where id = 'story-2-s4';
update sentences set en = 'He walked in two minutes early, catching his breath, hoping it didn''t show.', ar = 'دخل قبل دقيقتين من الموعد، ملتقطًا أنفاسه، آملاً ألا يظهر ذلك عليه.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"دخل","en":"walked"},{"ar":"في","en":"in"},{"ar":"اثنتين","en":"two"},{"ar":"دقيقة","en":"minutes"},{"ar":"مبكرًا،","en":"early,"},{"ar":"ملتقطًا","en":"catching"},{"ar":"ـه","en":"his"},{"ar":"أنفاس،","en":"breath,"},{"ar":"آملاً","en":"hoping"},{"ar":"ذلك","en":"it"},{"ar":"لا","en":"didn''t"},{"ar":"يظهر.","en":"show."}]'::jsonb, updated_at = now() where id = 'story-2-s5';
update sentences set en = 'The interviewer glanced at his slightly crooked collar but said nothing.', ar = 'ألقت المحاورة نظرة على ياقته المائلة قليلاً لكنها لم تقل شيئًا.', word_translations = '[{"ar":"الـ","en":"The"},{"ar":"المحاورة","en":"interviewer"},{"ar":"نظرت","en":"glanced"},{"ar":"إلى","en":"at"},{"ar":"ـه","en":"his"},{"ar":"قليلاً","en":"slightly"},{"ar":"المائلة","en":"crooked"},{"ar":"ياقة","en":"collar"},{"ar":"لكنها","en":"but"},{"ar":"قالت","en":"said"},{"ar":"لا شيء.","en":"nothing."}]'::jsonb, updated_at = now() where id = 'story-2-s6';
update sentences set en = 'Halfway through, she asked why he looked like he''d run there.', ar = 'في منتصف المقابلة، سألته لماذا يبدو وكأنه ركض إلى هنا.', word_translations = '[{"ar":"في المنتصف،","en":"Halfway"},{"ar":"المقابلة،","en":"through,"},{"ar":"هي","en":"she"},{"ar":"سألته","en":"asked"},{"ar":"لماذا","en":"why"},{"ar":"هو","en":"he"},{"ar":"بدا","en":"looked"},{"ar":"وكأنه","en":"like"},{"ar":"هو","en":"he''d"},{"ar":"ركض","en":"run"},{"ar":"إلى هنا.","en":"there."}]'::jsonb, updated_at = now() where id = 'story-2-s7';
update sentences set en = 'Ahmed decided honesty was easier than pretending, and told her exactly what had happened.', ar = 'قرر أحمد أن الصدق أسهل من التظاهر، فأخبرها بالضبط بما حدث.', word_translations = '[{"ar":"أحمد","en":"Ahmed"},{"ar":"قرر","en":"decided"},{"ar":"الصدق","en":"honesty"},{"ar":"كان","en":"was"},{"ar":"أسهل","en":"easier"},{"ar":"من","en":"than"},{"ar":"التظاهر،","en":"pretending,"},{"ar":"و","en":"and"},{"ar":"أخبر","en":"told"},{"ar":"ها","en":"her"},{"ar":"بالضبط","en":"exactly"},{"ar":"بما","en":"what"},{"ar":"قد","en":"had"},{"ar":"حدث.","en":"happened."}]'::jsonb, updated_at = now() where id = 'story-2-s8';
update sentences set en = 'She laughed, more than the story really deserved, and relaxed visibly.', ar = 'ضحكت أكثر مما تستحق القصة فعلاً، وبدا عليها الارتياح بوضوح.', word_translations = '[{"ar":"هي","en":"She"},{"ar":"ضحكت،","en":"laughed,"},{"ar":"أكثر","en":"more"},{"ar":"من","en":"than"},{"ar":"الـ","en":"the"},{"ar":"القصة","en":"story"},{"ar":"فعلاً","en":"really"},{"ar":"تستحق،","en":"deserved,"},{"ar":"و","en":"and"},{"ar":"بدا عليها الارتياح","en":"relaxed"},{"ar":"بوضوح.","en":"visibly."}]'::jsonb, updated_at = now() where id = 'story-2-s9';
update sentences set en = '"At least I know you can handle things going wrong," she said.', ar = 'قالت: "على الأقل أعرف أنك تستطيع التعامل مع الأمور حين تسوء."', word_translations = '[{"ar":"\"","en":"\"At"},{"ar":"على الأقل،","en":"least"},{"ar":"أعرف","en":"I"},{"ar":"أنك","en":"know"},{"ar":"أنت","en":"you"},{"ar":"تستطيع","en":"can"},{"ar":"التعامل مع","en":"handle"},{"ar":"الأمور","en":"things"},{"ar":"حين","en":"going"},{"ar":"تسوء،\"","en":"wrong,\""},{"ar":"هي","en":"she"},{"ar":"قالت.","en":"said."}]'::jsonb, updated_at = now() where id = 'story-2-s10';
update sentences set en = 'The rest of the interview felt more like a conversation than a test.', ar = 'بدت بقية المقابلة أشبه بحديث ودي منها باختبار.', word_translations = '[{"ar":"الـ","en":"The"},{"ar":"بقية","en":"rest"},{"ar":"من","en":"of"},{"ar":"الـ","en":"the"},{"ar":"المقابلة","en":"interview"},{"ar":"بدت","en":"felt"},{"ar":"أكثر","en":"more"},{"ar":"كـ","en":"like"},{"ar":"واحد","en":"a"},{"ar":"حديث","en":"conversation"},{"ar":"من","en":"than"},{"ar":"واحد","en":"a"},{"ar":"اختبار.","en":"test."}]'::jsonb, updated_at = now() where id = 'story-2-s11';
update sentences set en = 'Two days later, she called to offer him the job — and to ask if he''d found a better alarm clock.', ar = 'بعد يومين، اتصلت لتعرض عليه الوظيفة، ولتسأله إن كان قد وجد منبهًا أفضل.', word_translations = '[{"ar":"اثنان","en":"Two"},{"ar":"أيام","en":"days"},{"ar":"بعد،","en":"later,"},{"ar":"هي","en":"she"},{"ar":"اتصلت","en":"called"},{"ar":"لـ","en":"to"},{"ar":"تعرض","en":"offer"},{"ar":"عليه","en":"him"},{"ar":"الـ","en":"the"},{"ar":"وظيفة","en":"job"},{"ar":"—","en":"—"},{"ar":"و","en":"and"},{"ar":"لـ","en":"to"},{"ar":"تسأل","en":"ask"},{"ar":"إن","en":"if"},{"ar":"كان قد","en":"he''d"},{"ar":"وجد","en":"found"},{"ar":"واحد","en":"a"},{"ar":"أفضل","en":"better"},{"ar":"منبه","en":"alarm"},{"ar":"ساعة.","en":"clock."}]'::jsonb, updated_at = now() where id = 'story-2-s12';
update sentences set en = 'Ali was already ten minutes late when he realized his left shoe was missing.', ar = 'كان علي متأخرًا بالفعل عشر دقائق عندما أدرك أن حذاءه الأيسر مفقود.', word_translations = '[{"ar":"علي","en":"Ali"},{"ar":"كان","en":"was"},{"ar":"بالفعل","en":"already"},{"ar":"عشر","en":"ten"},{"ar":"دقائق","en":"minutes"},{"ar":"متأخرًا","en":"late"},{"ar":"عندما","en":"when"},{"ar":"هو","en":"he"},{"ar":"أدرك","en":"realized"},{"ar":"حذاءه","en":"his"},{"ar":"الأيسر","en":"left"},{"ar":"حذاء","en":"shoe"},{"ar":"كان","en":"was"},{"ar":"مفقود.","en":"missing."}]'::jsonb, updated_at = now() where id = 'story-3-s1';
update sentences set en = 'He checked under the bed, then behind the door, then under the bed again.', ar = 'بحث تحت السرير، ثم خلف الباب، ثم تحت السرير مرة أخرى.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"بحث","en":"checked"},{"ar":"تحت","en":"under"},{"ar":"الـ","en":"the"},{"ar":"السرير،","en":"bed,"},{"ar":"ثم","en":"then"},{"ar":"خلف","en":"behind"},{"ar":"الـ","en":"the"},{"ar":"الباب،","en":"door,"},{"ar":"ثم","en":"then"},{"ar":"تحت","en":"under"},{"ar":"الـ","en":"the"},{"ar":"السرير","en":"bed"},{"ar":"مرة أخرى.","en":"again."}]'::jsonb, updated_at = now() where id = 'story-3-s2';
update sentences set en = 'His little sister was oddly quiet in the kitchen, which was never a good sign.', ar = 'كانت أخته الصغيرة هادئة بشكل غريب في المطبخ، وهو أمر لم يكن مبشرًا أبدًا.', word_translations = '[{"ar":"أخته","en":"His"},{"ar":"الصغيرة","en":"little"},{"ar":"شقيقته","en":"sister"},{"ar":"كانت","en":"was"},{"ar":"بغرابة","en":"oddly"},{"ar":"هادئة","en":"quiet"},{"ar":"في","en":"in"},{"ar":"الـ","en":"the"},{"ar":"المطبخ،","en":"kitchen,"},{"ar":"وهو","en":"which"},{"ar":"أمر","en":"was"},{"ar":"لم يكن","en":"never"},{"ar":"أبدًا","en":"a"},{"ar":"مبشرًا","en":"good"},{"ar":"بالخير.","en":"sign."}]'::jsonb, updated_at = now() where id = 'story-3-s3';
update sentences set en = 'He found her there, calmly handing his shoe to the dog, one lace at a time.', ar = 'وجدها هناك، تسلم حذاءه للكلب بهدوء، رباطًا واحدًا في كل مرة.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"وجد","en":"found"},{"ar":"ها","en":"her"},{"ar":"هناك،","en":"there,"},{"ar":"بهدوء","en":"calmly"},{"ar":"تسلم","en":"handing"},{"ar":"حذاءه","en":"his"},{"ar":"حذاء","en":"shoe"},{"ar":"لـ","en":"to"},{"ar":"الـ","en":"the"},{"ar":"الكلب،","en":"dog,"},{"ar":"رباطًا","en":"one"},{"ar":"واحدًا","en":"lace"},{"ar":"في","en":"at"},{"ar":"واحد","en":"a"},{"ar":"مرة.","en":"time."}]'::jsonb, updated_at = now() where id = 'story-3-s4';
update sentences set en = 'The dog looked almost as confused as Ali felt.', ar = 'بدا الكلب في حيرة تقارب حيرة علي نفسه.', word_translations = '[{"ar":"الـ","en":"The"},{"ar":"الكلب","en":"dog"},{"ar":"بدا","en":"looked"},{"ar":"تقريبًا","en":"almost"},{"ar":"في","en":"as"},{"ar":"حيرة","en":"confused"},{"ar":"مثل","en":"as"},{"ar":"علي","en":"Ali"},{"ar":"نفسه.","en":"felt."}]'::jsonb, updated_at = now() where id = 'story-3-s5';
update sentences set en = 'He couldn''t decide whether to be angry or just start laughing, so he did both.', ar = 'لم يستطع أن يقرر إن كان سيغضب أم سيضحك فقط، فاختار الاثنين معًا.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"لم يستطع","en":"couldn''t"},{"ar":"أن","en":"decide"},{"ar":"يقرر","en":"whether"},{"ar":"إن","en":"to"},{"ar":"كان","en":"be"},{"ar":"سيغضب","en":"angry"},{"ar":"أم","en":"or"},{"ar":"سيضحك","en":"just"},{"ar":"فقط","en":"start"},{"ar":"أن يبدأ","en":"laughing,"},{"ar":"فـ","en":"so"},{"ar":"اختار","en":"he"},{"ar":"الاثنين","en":"did"},{"ar":"معًا.","en":"both."}]'::jsonb, updated_at = now() where id = 'story-3-s6';
update sentences set en = 'There was no time to argue, so he grabbed his old shoes instead.', ar = 'لم يكن هناك وقت للجدال، فأمسك حذاءه القديم بدلاً منه.', word_translations = '[{"ar":"لم","en":"There"},{"ar":"يكن","en":"was"},{"ar":"هناك","en":"no"},{"ar":"وقت","en":"time"},{"ar":"لـ","en":"to"},{"ar":"الجدال،","en":"argue,"},{"ar":"فـ","en":"so"},{"ar":"أمسك","en":"he"},{"ar":"حذاءه","en":"grabbed"},{"ar":"القديم","en":"his"},{"ar":"حذاء","en":"old"},{"ar":"بدلاً","en":"shoes"},{"ar":"منه.","en":"instead."}]'::jsonb, updated_at = now() where id = 'story-3-s7';
update sentences set en = 'He told the story at school before he''d even sat down.', ar = 'روى القصة في المدرسة قبل أن يجلس حتى.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"روى","en":"told"},{"ar":"الـ","en":"the"},{"ar":"القصة","en":"story"},{"ar":"في","en":"at"},{"ar":"المدرسة","en":"school"},{"ar":"قبل","en":"before"},{"ar":"أن","en":"he''d"},{"ar":"حتى","en":"even"},{"ar":"يجلس","en":"sat"},{"ar":"-.","en":"down."}]'::jsonb, updated_at = now() where id = 'story-3-s8';
update sentences set en = 'By lunchtime, half the class knew about the dog and the shoe.', ar = 'بحلول وقت الغداء، كان نصف الصف يعرف قصة الكلب والحذاء.', word_translations = '[{"ar":"بحلول","en":"By"},{"ar":"وقت الغداء،","en":"lunchtime,"},{"ar":"نصف","en":"half"},{"ar":"الـ","en":"the"},{"ar":"الصف","en":"class"},{"ar":"كان يعرف","en":"knew"},{"ar":"عن","en":"about"},{"ar":"الـ","en":"the"},{"ar":"الكلب","en":"dog"},{"ar":"و","en":"and"},{"ar":"الـ","en":"the"},{"ar":"الحذاء.","en":"shoe."}]'::jsonb, updated_at = now() where id = 'story-3-s9';
update sentences set en = 'Someone started calling him "Shoe Boy," and it stuck.', ar = 'بدأ أحدهم بمناداته "فتى الحذاء"، واستمر اللقب.', word_translations = '[{"ar":"أحدهم","en":"Someone"},{"ar":"بدأ","en":"started"},{"ar":"بمناداته","en":"calling"},{"ar":"-","en":"him"},{"ar":"\"فتى","en":"\"Shoe"},{"ar":"الحذاء\"،","en":"Boy,\""},{"ar":"و","en":"and"},{"ar":"اللقب","en":"it"},{"ar":"استمر.","en":"stuck."}]'::jsonb, updated_at = now() where id = 'story-3-s10';
update sentences set en = 'Weeks later, his sister still won''t say why she picked that shoe.', ar = 'بعد أسابيع، ما زالت أخته ترفض أن تقول لماذا اختارت ذلك الحذاء بالذات.', word_translations = '[{"ar":"بعد","en":"Weeks"},{"ar":"أسابيع،","en":"later,"},{"ar":"ـه","en":"his"},{"ar":"أخته","en":"sister"},{"ar":"ما زالت","en":"still"},{"ar":"ترفض","en":"won''t"},{"ar":"أن تقول","en":"say"},{"ar":"لماذا","en":"why"},{"ar":"هي","en":"she"},{"ar":"اختارت","en":"picked"},{"ar":"ذلك","en":"that"},{"ar":"الحذاء.","en":"shoe."}]'::jsonb, updated_at = now() where id = 'story-3-s11';
update sentences set en = 'Yusuf was running late, so he ordered his coffee without really looking at the menu board.', ar = 'كان يوسف متأخرًا، فطلب قهوته دون أن ينظر حقًا إلى لوحة القائمة.', word_translations = '[{"ar":"يوسف","en":"Yusuf"},{"ar":"كان","en":"was"},{"ar":"يجري","en":"running"},{"ar":"متأخرًا،","en":"late,"},{"ar":"فـ","en":"so"},{"ar":"هو","en":"he"},{"ar":"طلب","en":"ordered"},{"ar":"قهوته","en":"his"},{"ar":"قهوة","en":"coffee"},{"ar":"دون","en":"without"},{"ar":"حقًا","en":"really"},{"ar":"ينظر","en":"looking"},{"ar":"إلى","en":"at"},{"ar":"الـ","en":"the"},{"ar":"لوحة","en":"menu"},{"ar":"القائمة.","en":"board."}]'::jsonb, updated_at = now() where id = 'story-7-s1';
update sentences set en = 'The shop was packed, and every name the barista called sounded a little like his.', ar = 'كان المقهى مزدحمًا، وكل اسم كان يناديه الباريستا يبدو قريبًا من اسمه.', word_translations = '[{"ar":"الـ","en":"The"},{"ar":"المقهى","en":"shop"},{"ar":"كان","en":"was"},{"ar":"مزدحمًا،","en":"packed,"},{"ar":"و","en":"and"},{"ar":"كل","en":"every"},{"ar":"اسم","en":"name"},{"ar":"الـ","en":"the"},{"ar":"الباريستا","en":"barista"},{"ar":"يناديه","en":"called"},{"ar":"يبدو","en":"sounded"},{"ar":"قريبًا","en":"a"},{"ar":"قليلاً","en":"little"},{"ar":"من","en":"like"},{"ar":"اسمه.","en":"his."}]'::jsonb, updated_at = now() where id = 'story-7-s2';
update sentences set en = 'When "Yusuf" finally rang out, he grabbed the nearest cup and headed for the door.', ar = 'عندما نودي أخيرًا باسم "يوسف"، خطف أقرب كوب وتوجه نحو الباب.', word_translations = '[{"ar":"عندما","en":"When"},{"ar":"\"يوسف\"","en":"\"Yusuf\""},{"ar":"أخيرًا","en":"finally"},{"ar":"نودي","en":"rang"},{"ar":"-","en":"out,"},{"ar":"هو","en":"he"},{"ar":"خطف","en":"grabbed"},{"ar":"-","en":"the"},{"ar":"أقرب","en":"nearest"},{"ar":"كوب","en":"cup"},{"ar":"و","en":"and"},{"ar":"توجه","en":"headed"},{"ar":"نحو","en":"for"},{"ar":"الـ","en":"the"},{"ar":"الباب.","en":"door."}]'::jsonb, updated_at = now() where id = 'story-7-s3';
update sentences set en = 'He took a sip on the sidewalk and immediately stopped walking.', ar = 'أخذ رشفة على الرصيف وتوقف عن المشي فورًا.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"أخذ","en":"took"},{"ar":"واحدة","en":"a"},{"ar":"رشفة","en":"sip"},{"ar":"على","en":"on"},{"ar":"الـ","en":"the"},{"ar":"الرصيف","en":"sidewalk"},{"ar":"و","en":"and"},{"ar":"فورًا","en":"immediately"},{"ar":"توقف","en":"stopped"},{"ar":"المشي.","en":"walking."}]'::jsonb, updated_at = now() where id = 'story-7-s4';
update sentences set en = 'It was sweet, syrupy, nothing like the black coffee he''d asked for.', ar = 'كانت حلوة وكثيفة كالشراب، لا تشبه إطلاقًا القهوة السوداء التي طلبها.', word_translations = '[{"ar":"كانت","en":"It"},{"ar":"-","en":"was"},{"ar":"حلوة،","en":"sweet,"},{"ar":"وكثيفة كالشراب،","en":"syrupy,"},{"ar":"لا","en":"nothing"},{"ar":"تشبه","en":"like"},{"ar":"إطلاقًا","en":"the"},{"ar":"الـ","en":"black"},{"ar":"السوداء","en":"coffee"},{"ar":"القهوة","en":"he''d"},{"ar":"التي","en":"asked"},{"ar":"طلبها.","en":"for."}]'::jsonb, updated_at = now() where id = 'story-7-s5';
update sentences set en = 'He checked the cup and found someone else''s name written under his own crossed-out order.', ar = 'تفحص الكوب فوجد اسم شخص آخر مكتوبًا تحت طلبه الذي شُطب.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"تفحص","en":"checked"},{"ar":"الـ","en":"the"},{"ar":"الكوب","en":"cup"},{"ar":"فـ","en":"and"},{"ar":"وجد","en":"found"},{"ar":"اسم","en":"someone"},{"ar":"شخص","en":"else''s"},{"ar":"آخر","en":"name"},{"ar":"مكتوبًا","en":"written"},{"ar":"تحت","en":"under"},{"ar":"طلبه","en":"his"},{"ar":"الخاص","en":"own"},{"ar":"الذي شُطب","en":"crossed-out"},{"ar":"-.","en":"order."}]'::jsonb, updated_at = now() where id = 'story-7-s6';
update sentences set en = 'Somehow the barista had written both on the same cup and given him the wrong half.', ar = 'بطريقة ما كتب الباريستا الاسمين على الكوب نفسه وأعطاه النصف الخطأ.', word_translations = '[{"ar":"بطريقة ما","en":"Somehow"},{"ar":"-","en":"the"},{"ar":"الباريستا","en":"barista"},{"ar":"-","en":"had"},{"ar":"كتب","en":"written"},{"ar":"الاسمين","en":"both"},{"ar":"على","en":"on"},{"ar":"الـ","en":"the"},{"ar":"نفسه","en":"same"},{"ar":"الكوب","en":"cup"},{"ar":"و","en":"and"},{"ar":"أعطاه","en":"given"},{"ar":"-","en":"him"},{"ar":"الـ","en":"the"},{"ar":"الخطأ","en":"wrong"},{"ar":"النصف.","en":"half."}]'::jsonb, updated_at = now() where id = 'story-7-s7';
update sentences set en = 'He walked back in, half-annoyed and half-amused, and held up the cup.', ar = 'عاد إلى الداخل، بين الانزعاج والتسلية، ورفع الكوب.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"عاد","en":"walked"},{"ar":"إلى","en":"back"},{"ar":"الداخل،","en":"in,"},{"ar":"بين الانزعاج","en":"half-annoyed"},{"ar":"و","en":"and"},{"ar":"التسلية،","en":"half-amused,"},{"ar":"و","en":"and"},{"ar":"رفع","en":"held"},{"ar":"-","en":"up"},{"ar":"الـ","en":"the"},{"ar":"الكوب.","en":"cup."}]'::jsonb, updated_at = now() where id = 'story-7-s8';
update sentences set en = 'The barista looked at it, then laughed and said, "That''s actually my next customer''s."', ar = 'نظر الباريستا إليه، ثم ضحك وقال: "هذا في الواقع لزبوني التالي."', word_translations = '[{"ar":"الـ","en":"The"},{"ar":"الباريستا","en":"barista"},{"ar":"نظر","en":"looked"},{"ar":"إلى","en":"at"},{"ar":"-","en":"it,"},{"ar":"ثم","en":"then"},{"ar":"ضحك","en":"laughed"},{"ar":"و","en":"and"},{"ar":"قال،","en":"said,"},{"ar":"\"هذا","en":"\"That''s"},{"ar":"في الواقع","en":"actually"},{"ar":"لـ","en":"my"},{"ar":"التالي","en":"next"},{"ar":"زبوني.","en":"customer''s.\""}]'::jsonb, updated_at = now() where id = 'story-7-s9';
update sentences set en = 'A man near the counter raised his hand, looking equally confused about his own cup.', ar = 'رفع رجل بالقرب من الطاولة يده، وبدا مرتبكًا هو الآخر بشأن كوبه.', word_translations = '[{"ar":"واحد","en":"A"},{"ar":"رجل","en":"man"},{"ar":"بالقرب من","en":"near"},{"ar":"الـ","en":"the"},{"ar":"الطاولة","en":"counter"},{"ar":"رفع","en":"raised"},{"ar":"-","en":"his"},{"ar":"يده،","en":"hand,"},{"ar":"وبدا","en":"looking"},{"ar":"مرتبكًا","en":"equally"},{"ar":"هو الآخر","en":"confused"},{"ar":"بشأن","en":"about"},{"ar":"-","en":"his"},{"ar":"-","en":"own"},{"ar":"كوبه.","en":"cup."}]'::jsonb, updated_at = now() where id = 'story-7-s10';
update sentences set en = 'They swapped, the barista apologized with a free pastry, and Yusuf finally got his coffee.', ar = 'تبادلا الكوبين، واعتذر الباريستا بمعجنات مجانية، وحصل يوسف أخيرًا على قهوته.', word_translations = '[{"ar":"تبادلا","en":"They"},{"ar":"الكوبين،","en":"swapped,"},{"ar":"-","en":"the"},{"ar":"الباريستا","en":"barista"},{"ar":"اعتذر","en":"apologized"},{"ar":"بـ","en":"with"},{"ar":"-","en":"a"},{"ar":"مجانية","en":"free"},{"ar":"معجنات،","en":"pastry,"},{"ar":"و","en":"and"},{"ar":"يوسف","en":"Yusuf"},{"ar":"أخيرًا","en":"finally"},{"ar":"حصل","en":"got"},{"ar":"-","en":"his"},{"ar":"قهوته.","en":"coffee."}]'::jsonb, updated_at = now() where id = 'story-7-s11';
update sentences set en = 'He was later to work than planned, but at least he had a better story than "traffic."', ar = 'وصل إلى العمل متأخرًا أكثر مما خطط له، لكن على الأقل كانت لديه قصة أفضل من "الزحام."', word_translations = '[{"ar":"هو","en":"He"},{"ar":"وصل","en":"was"},{"ar":"متأخرًا","en":"later"},{"ar":"إلى","en":"to"},{"ar":"العمل","en":"work"},{"ar":"أكثر","en":"than"},{"ar":"من خطط له،","en":"planned,"},{"ar":"لكن","en":"but"},{"ar":"على","en":"at"},{"ar":"الأقل","en":"least"},{"ar":"-","en":"he"},{"ar":"كانت","en":"had"},{"ar":"لديه","en":"a"},{"ar":"قصة","en":"better"},{"ar":"أفضل","en":"story"},{"ar":"من","en":"than"},{"ar":"\"الزحام.\"","en":"\"traffic.\""}]'::jsonb, updated_at = now() where id = 'story-7-s12';
update sentences set en = 'A large box was waiting outside Tariq''s door when he got home, though he hadn''t ordered anything.', ar = 'كان صندوق كبير بانتظاره أمام باب طارق حين عاد إلى المنزل، رغم أنه لم يطلب شيئًا.', word_translations = '[{"ar":"واحد","en":"A"},{"ar":"كبير","en":"large"},{"ar":"صندوق","en":"box"},{"ar":"كان","en":"was"},{"ar":"بانتظاره","en":"waiting"},{"ar":"أمام","en":"outside"},{"ar":"طارق","en":"Tariq''s"},{"ar":"باب","en":"door"},{"ar":"حين","en":"when"},{"ar":"هو","en":"he"},{"ar":"عاد","en":"got"},{"ar":"المنزل،","en":"home,"},{"ar":"رغم","en":"though"},{"ar":"أنه","en":"he"},{"ar":"لم","en":"hadn''t"},{"ar":"يطلب","en":"ordered"},{"ar":"شيئًا.","en":"anything."}]'::jsonb, updated_at = now() where id = 'story-9-s1';
update sentences set en = 'His name and address were right there on the label, so he carried it inside anyway.', ar = 'كان اسمه وعنوانه مكتوبين على الملصق، فحملها إلى الداخل رغم ذلك.', word_translations = '[{"ar":"كان","en":"His"},{"ar":"اسمه","en":"name"},{"ar":"و","en":"and"},{"ar":"عنوانه","en":"address"},{"ar":"مكتوبين","en":"were"},{"ar":"تمامًا","en":"right"},{"ar":"هناك","en":"there"},{"ar":"على","en":"on"},{"ar":"الـ","en":"the"},{"ar":"الملصق،","en":"label,"},{"ar":"فـ","en":"so"},{"ar":"هو","en":"he"},{"ar":"حملها","en":"carried"},{"ar":"إلى الداخل","en":"it"},{"ar":"رغم ذلك","en":"inside"},{"ar":"-.","en":"anyway."}]'::jsonb, updated_at = now() where id = 'story-9-s2';
update sentences set en = 'Opening it, he found twelve pairs of impossibly bright socks and a card.', ar = 'عند فتحها، وجد اثني عشر زوجًا من الجوارب الزاهية بشكل غريب وبطاقة.', word_translations = '[{"ar":"عند فتحها،","en":"Opening"},{"ar":"-","en":"it,"},{"ar":"هو","en":"he"},{"ar":"وجد","en":"found"},{"ar":"اثني عشر","en":"twelve"},{"ar":"زوجًا","en":"pairs"},{"ar":"من","en":"of"},{"ar":"بشكل غريب","en":"impossibly"},{"ar":"الزاهية","en":"bright"},{"ar":"الجوارب","en":"socks"},{"ar":"و","en":"and"},{"ar":"-","en":"a"},{"ar":"بطاقة.","en":"card."}]'::jsonb, updated_at = now() where id = 'story-9-s3';
update sentences set en = '"Happy Birthday from your team!" it read — except his birthday wasn''t for another month.', ar = 'كانت البطاقة تقول: "عيد ميلاد سعيد من فريقك!" لكن عيد ميلاده لم يكن قبل شهر آخر.', word_translations = '[{"ar":"\"سعيد","en":"\"Happy"},{"ar":"ميلاد","en":"Birthday"},{"ar":"من","en":"from"},{"ar":"فريقك","en":"your"},{"ar":"!\"","en":"team!\""},{"ar":"ذلك","en":"it"},{"ar":"قرأ","en":"read"},{"ar":"—","en":"—"},{"ar":"إلا","en":"except"},{"ar":"ـه","en":"his"},{"ar":"عيد ميلاده","en":"birthday"},{"ar":"لم يكن","en":"wasn''t"},{"ar":"قبل","en":"for"},{"ar":"آخر","en":"another"},{"ar":"شهر.","en":"month."}]'::jsonb, updated_at = now() where id = 'story-9-s4';
update sentences set en = 'He called the number on the receipt, mostly out of curiosity.', ar = 'اتصل بالرقم المكتوب على الإيصال، بدافع الفضول أكثر من أي شيء آخر.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"اتصل","en":"called"},{"ar":"-","en":"the"},{"ar":"رقم","en":"number"},{"ar":"على","en":"on"},{"ar":"-","en":"the"},{"ar":"الإيصال،","en":"receipt,"},{"ar":"بدافع","en":"mostly"},{"ar":"-","en":"out"},{"ar":"-","en":"of"},{"ar":"الفضول.","en":"curiosity."}]'::jsonb, updated_at = now() where id = 'story-9-s5';
update sentences set en = 'The woman on the phone checked the order and went quiet for a second.', ar = 'تحققت المرأة على الهاتف من الطلب وصمتت للحظة.', word_translations = '[{"ar":"الـ","en":"The"},{"ar":"المرأة","en":"woman"},{"ar":"على","en":"on"},{"ar":"الـ","en":"the"},{"ar":"الهاتف","en":"phone"},{"ar":"تحققت من","en":"checked"},{"ar":"-","en":"the"},{"ar":"الطلب","en":"order"},{"ar":"و","en":"and"},{"ar":"صمتت","en":"went"},{"ar":"هادئ","en":"quiet"},{"ar":"لـ","en":"for"},{"ar":"-","en":"a"},{"ar":"لحظة.","en":"second."}]'::jsonb, updated_at = now() where id = 'story-9-s6';
update sentences set en = '"This was meant for a Tarek, two buildings over," she said. "Same street, wrong door."', ar = 'قالت: "كان هذا مخصصًا لشخص اسمه طارق، على بعد مبنيين من هنا. نفس الشارع، لكن الباب الخطأ."', word_translations = '[{"ar":"\"هذا","en":"\"This"},{"ar":"كان","en":"was"},{"ar":"مخصصًا","en":"meant"},{"ar":"لـ","en":"for"},{"ar":"شخص","en":"a"},{"ar":"اسمه طارق،","en":"Tarek,"},{"ar":"على بعد","en":"two"},{"ar":"مبنيين","en":"buildings"},{"ar":"من هنا.\"","en":"over,\""},{"ar":"هي","en":"she"},{"ar":"قالت.","en":"said."},{"ar":"\"نفس","en":"\"Same"},{"ar":"الشارع،","en":"street,"},{"ar":"لكن","en":"wrong"},{"ar":"الباب الخطأ.\"","en":"door.\""}]'::jsonb, updated_at = now() where id = 'story-9-s7';
update sentences set en = 'She offered to send a courier to collect it and redeliver it properly.', ar = 'عرضت أن ترسل عامل توصيل لاستلامها وإعادة توصيلها بشكل صحيح.', word_translations = '[{"ar":"هي","en":"She"},{"ar":"عرضت","en":"offered"},{"ar":"أن","en":"to"},{"ar":"ترسل","en":"send"},{"ar":"-","en":"a"},{"ar":"عامل توصيل","en":"courier"},{"ar":"لـ","en":"to"},{"ar":"استلامها","en":"collect"},{"ar":"-","en":"it"},{"ar":"و","en":"and"},{"ar":"إعادة توصيلها","en":"redeliver"},{"ar":"-","en":"it"},{"ar":"بشكل صحيح.","en":"properly."}]'::jsonb, updated_at = now() where id = 'story-9-s8';
update sentences set en = 'Tariq said not to bother and posted in the building''s group chat instead: "Anyone know a Tarek nearby?"', ar = 'قال طارق ألا داعي لذلك، ونشر بدلاً منه في مجموعة دردشة المبنى: "هل يعرف أحد طارقًا قريبًا من هنا؟"', word_translations = '[{"ar":"طارق","en":"Tariq"},{"ar":"قال","en":"said"},{"ar":"ألا","en":"not"},{"ar":"داعي","en":"to"},{"ar":"لذلك،","en":"bother"},{"ar":"و","en":"and"},{"ar":"نشر","en":"posted"},{"ar":"بدلاً منه في","en":"in"},{"ar":"-","en":"the"},{"ar":"المبنى","en":"building''s"},{"ar":"مجموعة","en":"group"},{"ar":"دردشة:","en":"chat"},{"ar":"-","en":"instead:"},{"ar":"\"هل","en":"\"Anyone"},{"ar":"يعرف أحد","en":"know"},{"ar":"-","en":"a"},{"ar":"طارقًا","en":"Tarek"},{"ar":"قريبًا من هنا؟\"","en":"nearby?\""}]'::jsonb, updated_at = now() where id = 'story-9-s9';
update sentences set en = 'Within the hour, someone three streets over replied that they knew exactly who that was.', ar = 'خلال ساعة، رد شخص على بعد ثلاثة شوارع قائلاً إنه يعرف بالضبط من يكون.', word_translations = '[{"ar":"خلال","en":"Within"},{"ar":"-","en":"the"},{"ar":"ساعة،","en":"hour,"},{"ar":"شخص","en":"someone"},{"ar":"ثلاثة","en":"three"},{"ar":"شوارع","en":"streets"},{"ar":"على بعد","en":"over"},{"ar":"رد","en":"replied"},{"ar":"قائلاً","en":"that"},{"ar":"إنه","en":"they"},{"ar":"يعرف","en":"knew"},{"ar":"بالضبط","en":"exactly"},{"ar":"من","en":"who"},{"ar":"-","en":"that"},{"ar":"يكون.","en":"was."}]'::jsonb, updated_at = now() where id = 'story-9-s10';
update sentences set en = 'Tariq left the box at the corner shop, with a message telling Tarek where to find it.', ar = 'ترك طارق الصندوق عند البقالة في الزاوية، مع رسالة تخبر طارق أين يجده.', word_translations = '[{"ar":"طارق","en":"Tariq"},{"ar":"ترك","en":"left"},{"ar":"الـ","en":"the"},{"ar":"الصندوق","en":"box"},{"ar":"عند","en":"at"},{"ar":"-","en":"the"},{"ar":"الزاوية","en":"corner"},{"ar":"المتجر،","en":"shop,"},{"ar":"مع","en":"with"},{"ar":"-","en":"a"},{"ar":"رسالة","en":"message"},{"ar":"تخبر","en":"telling"},{"ar":"طارق","en":"Tarek"},{"ar":"أين","en":"where"},{"ar":"-","en":"to"},{"ar":"يجد","en":"find"},{"ar":"ها.","en":"it."}]'::jsonb, updated_at = now() where id = 'story-9-s11';
update sentences set en = 'He never met Tarek, but a week later, one very bright pair of socks appeared on his own doorstep.', ar = 'لم يلتقِ طارق قط، لكن بعد أسبوع، ظهر زوج واحد شديد اللمعان من الجوارب على عتبة بابه هو.', word_translations = '[{"ar":"هو","en":"He"},{"ar":"لم","en":"never"},{"ar":"يلتقِ","en":"met"},{"ar":"طارق،","en":"Tarek,"},{"ar":"لكن","en":"but"},{"ar":"-","en":"a"},{"ar":"أسبوع","en":"week"},{"ar":"بعد،","en":"later,"},{"ar":"واحد","en":"one"},{"ar":"جدًا","en":"very"},{"ar":"لامع","en":"bright"},{"ar":"زوج","en":"pair"},{"ar":"من","en":"of"},{"ar":"الجوارب","en":"socks"},{"ar":"ظهر","en":"appeared"},{"ar":"على","en":"on"},{"ar":"-","en":"his"},{"ar":"الخاص","en":"own"},{"ar":"عتبة بابه.","en":"doorstep."}]'::jsonb, updated_at = now() where id = 'story-9-s12';

-- These two trailing sentences no longer exist in the rewritten (shorter)
-- stories — delete rather than leave stale rows a fresh database would
-- never get from the inserts above. Cascades to any `mistakes` rows tied
-- to these exact sentence ids (see that table's own on-delete-cascade),
-- matching the same trade-off saveLesson's delete-and-reinsert already
-- makes on every admin edit of a shrinking lesson.
delete from sentences where id in ('story-1-s12', 'story-3-s12');

commit;
