-- Word Lists content top-up: adds more words to groups whose topic
-- genuinely supports it, never past 30 per group. Health/Food/Animals
-- get +10 (20->30) as the clearest large everyday domains; every other
-- group gets +5 (20->25). Applied to the live project via
-- scripts/insert-word-lists-topup.ts; captured here for tracking, same
-- precedent as 20250143000000/20250204000000.
begin;

insert into vocabulary_words (id, group_id, order_index, target_word, sentence, hint_ar) values
  ('health-doctor', 'health', 21, 'doctor', 'The ___ checked his blood pressure twice.', 'الطبيب.'),
  ('health-nurse', 'health', 22, 'nurse', 'A kind ___ helped her find the right room.', 'الممرض/الممرضة.'),
  ('health-hospital', 'health', 23, 'hospital', 'They rushed him to the ___ after the accident.', 'المستشفى.'),
  ('health-medicine', 'health', 24, 'medicine', 'Take this ___ twice a day with food.', 'الدواء.'),
  ('health-headache', 'health', 25, 'headache', 'She had a bad ___ after staring at the screen all day.', 'الصداع.'),
  ('health-vaccine', 'health', 26, 'vaccine', 'The clinic offers a free flu ___ every fall.', 'اللقاح.'),
  ('health-surgery', 'health', 27, 'surgery', 'He needs ___ to fix his knee.', 'الجراحة.'),
  ('health-pharmacy', 'health', 28, 'pharmacy', 'I picked up my prescription from the ___.', 'الصيدلية.'),
  ('health-patient', 'health', 29, 'patient', 'The doctor saw every ___ on time today.', 'المريض.'),
  ('health-emergency', 'health', 30, 'emergency', 'Call an ambulance, this is an ___.', 'الحالة الطارئة.'),
  ('food-soup', 'food', 21, 'soup', 'She made a warm ___ for the cold night.', 'الشوربة.'),
  ('food-salad', 'food', 22, 'salad', 'He orders a fresh ___ with almost every meal.', 'السلطة.'),
  ('food-coffee', 'food', 23, 'coffee', 'I can''t start my morning without a cup of ___.', 'القهوة.'),
  ('food-juice', 'food', 24, 'juice', 'She squeezed fresh orange ___ for breakfast.', 'العصير.'),
  ('food-snack', 'food', 25, 'snack', 'He grabbed a quick ___ before the meeting.', 'الوجبة الخفيفة.'),
  ('food-dessert', 'food', 26, 'dessert', 'We shared a chocolate ___ after dinner.', 'الحلوى.'),
  ('food-oven', 'food', 27, 'oven', 'Put the bread in the ___ for twenty minutes.', 'الفرن.'),
  ('food-boil', 'food', 28, 'boil', 'Let the water ___ before adding the pasta.', 'يغلي.'),
  ('food-grocery', 'food', 29, 'grocery', 'I need to do the ___ shopping this weekend.', 'البقالة.'),
  ('food-appetite', 'food', 30, 'appetite', 'A long walk always gives me a big ___.', 'الشهية.'),
  ('animals-whale', 'animals', 21, 'whale', 'A ___ surfaced near the boat for a moment.', 'الحوت.'),
  ('animals-dolphin', 'animals', 22, 'dolphin', 'A ___ jumped out of the water beside the ship.', 'الدلفين.'),
  ('animals-shark', 'animals', 23, 'shark', 'Swimmers were warned about a ___ near the beach.', 'سمك القرش.'),
  ('animals-snake', 'animals', 24, 'snake', 'A ___ was sleeping under a rock in the garden.', 'الثعبان.'),
  ('animals-frog', 'animals', 25, 'frog', 'A small ___ jumped across the wet path.', 'الضفدع.'),
  ('animals-bee', 'animals', 26, 'bee', 'A ___ landed on the flower near the window.', 'النحلة.'),
  ('animals-owl', 'animals', 27, 'owl', 'An ___ called out somewhere in the dark forest.', 'البومة.'),
  ('animals-eagle', 'animals', 28, 'eagle', 'An ___ circled slowly above the mountain.', 'النسر.'),
  ('animals-camel', 'animals', 29, 'camel', 'A ___ can go for days without drinking water.', 'الجمل.'),
  ('animals-giraffe', 'animals', 30, 'giraffe', 'The ___ stretched its neck to reach the leaves.', 'الزرافة.'),
  ('family-spouse', 'family', 21, 'spouse', 'Please bring your ___ to the company dinner.', 'الزوج أو الزوجة.'),
  ('family-widow', 'family', 22, 'widow', 'She became a ___ at a young age.', 'الأرملة.'),
  ('family-orphan', 'family', 23, 'orphan', 'The charity supports every ___ in the village.', 'اليتيم.'),
  ('family-guardian', 'family', 24, 'guardian', 'Her uncle became her legal ___ after the accident.', 'الوصي.'),
  ('family-fiance', 'family', 25, 'fiance', 'She introduced her ___ to the whole family.', 'الخطيب.'),
  ('house-apartment', 'house', 21, 'apartment', 'They just moved into a small ___ downtown.', 'الشقة.'),
  ('house-furniture', 'house', 22, 'furniture', 'All the ___ arrived a week late.', 'الأثاث.'),
  ('house-balcony', 'house', 23, 'balcony', 'We drink coffee on the ___ every morning.', 'الشرفة/البلكونة.'),
  ('house-rent', 'house', 24, 'rent', 'The ___ goes up a little every year here.', 'الإيجار.'),
  ('house-landlord', 'house', 25, 'landlord', 'Our ___ finally fixed the broken heater.', 'المؤجر/صاحب العقار.'),
  ('clothes-sweater', 'clothes', 21, 'sweater', 'Put on a ___, it''s chilly tonight.', 'السترة الصوفية.'),
  ('clothes-jeans', 'clothes', 22, 'jeans', 'He wears the same pair of ___ almost every day.', 'الجينز.'),
  ('clothes-suit', 'clothes', 23, 'suit', 'He wore a dark ___ to the interview.', 'البدلة.'),
  ('clothes-boots', 'clothes', 24, 'boots', 'Her ___ were still muddy from the hike.', 'الحذاء الطويل.'),
  ('clothes-sunglasses', 'clothes', 25, 'sunglasses', 'She forgot her ___ at the beach again.', 'النظارة الشمسية.'),
  ('friendship-kindness', 'friendship', 21, 'kindness', 'Her ___ made a hard week much easier.', 'اللطف/الطيبة.'),
  ('friendship-respect', 'friendship', 22, 'respect', 'Real friendship is built on mutual ___.', 'الاحترام.'),
  ('friendship-encourage', 'friendship', 23, 'encourage', 'A good friend will always ___ you to try again.', 'يشجّع.'),
  ('friendship-confide', 'friendship', 24, 'confide', 'She likes to ___ in her oldest friend.', 'يبوح بسر لشخص يثق به.'),
  ('friendship-rivalry', 'friendship', 25, 'rivalry', 'Their friendly ___ pushed them both to improve.', 'التنافس.'),
  ('shopping-mall', 'shopping', 21, 'mall', 'We spent the whole afternoon at the ___.', 'المركز التجاري.'),
  ('shopping-coupon', 'shopping', 22, 'coupon', 'She used a ___ to get ten percent off.', 'قسيمة الخصم.'),
  ('shopping-brand', 'shopping', 23, 'brand', 'He only buys one ___ of running shoes.', 'العلامة التجارية.'),
  ('shopping-quality', 'shopping', 24, 'quality', 'The ___ of this jacket is really good for the price.', 'الجودة.'),
  ('shopping-checkout', 'shopping', 25, 'checkout', 'The line at the ___ was too long today.', 'منطقة الدفع.'),
  ('weather-hail', 'weather', 21, 'hail', '___ damaged several cars parked outside.', 'البرَد.'),
  ('weather-drizzle', 'weather', 22, 'drizzle', 'A light ___ started as we left the house.', 'رذاذ المطر الخفيف.'),
  ('weather-heatwave', 'weather', 23, 'heatwave', 'A ___ hit the city for almost a week.', 'موجة الحر.'),
  ('weather-overcast', 'weather', 24, 'overcast', 'The sky stayed ___ the whole afternoon.', 'غائم بالكامل.'),
  ('weather-mild', 'weather', 25, 'mild', 'The weather has been ___ for this time of year.', 'معتدل.'),
  ('work-career', 'work', 21, 'career', 'She''s building a solid ___ in design.', 'المسيرة المهنية.'),
  ('work-training', 'work', 22, 'training', 'New employees get a week of ___.', 'التدريب.'),
  ('work-workplace', 'work', 23, 'workplace', 'The company improved safety across the whole ___.', 'مكان العمل.'),
  ('work-manager', 'work', 24, 'manager', 'Her ___ approved the new schedule.', 'المدير المباشر.'),
  ('work-vacation', 'work', 25, 'vacation', 'He''s taking a two-week ___ in August.', 'الإجازة.'),
  ('politics-government', 'politics', 21, 'government', 'The ___ announced new tax rules today.', 'الحكومة.'),
  ('politics-president', 'politics', 22, 'president', 'The ___ gave a speech last night.', 'الرئيس.'),
  ('politics-election', 'politics', 23, 'election', 'The next ___ is scheduled for spring.', 'الانتخابات.'),
  ('politics-vote', 'politics', 24, 'vote', 'Millions of people will ___ this weekend.', 'يصوّت.'),
  ('politics-parliament', 'politics', 25, 'parliament', 'The bill was approved by ___ yesterday.', 'البرلمان.'),
  ('finance-loan', 'finance', 21, 'loan', 'They took out a ___ to buy the car.', 'القرض.'),
  ('finance-debt', 'finance', 22, 'debt', 'It took him years to pay off his ___.', 'الدَّين.'),
  ('finance-savings', 'finance', 23, 'savings', 'She keeps her ___ in a separate account.', 'المدخرات.'),
  ('finance-credit', 'finance', 24, 'credit', 'He paid for the flight using ___.', 'الائتمان.'),
  ('finance-profit', 'finance', 25, 'profit', 'The store made a small ___ this quarter.', 'الربح.'),
  ('technology-password', 'technology', 21, 'password', 'Don''t share your ___ with anyone.', 'كلمة المرور.'),
  ('technology-software', 'technology', 22, 'software', 'The company released new ___ last week.', 'البرمجيات.'),
  ('technology-device', 'technology', 23, 'device', 'Charge your ___ before the trip.', 'الجهاز.'),
  ('technology-internet', 'technology', 24, 'internet', 'The ___ went down for an hour this morning.', 'الإنترنت.'),
  ('technology-download', 'technology', 25, 'download', 'It took a while to ___ the whole file.', 'يُنزّل (ملف).'),
  ('environment-wildlife', 'environment', 21, 'wildlife', 'The reserve protects ___ across a huge area.', 'الحياة البرية.'),
  ('environment-habitat', 'environment', 22, 'habitat', 'Cutting down trees destroys the animals'' ___.', 'الموطن الطبيعي.'),
  ('environment-deforestation', 'environment', 23, 'deforestation', '___ has slowed down in the region this year.', 'إزالة الغابات.'),
  ('environment-solar', 'environment', 24, 'solar', 'They installed ___ panels on the roof.', 'شمسي.'),
  ('environment-landfill', 'environment', 25, 'landfill', 'Most of this waste ends up in a ___.', 'مكب النفايات.'),
  ('education-textbook', 'education', 21, 'textbook', 'She forgot her math ___ at home again.', 'الكتاب المدرسي.'),
  ('education-homework', 'education', 22, 'homework', 'He finished his ___ before dinner.', 'الواجب المنزلي.'),
  ('education-quiz', 'education', 23, 'quiz', 'We have a short ___ at the start of class.', 'اختبار قصير.'),
  ('education-campus', 'education', 24, 'campus', 'The ___ was quiet during the summer break.', 'الحرم الجامعي.'),
  ('education-tutor', 'education', 25, 'tutor', 'A private ___ helped her improve her grades.', 'المدرّس الخاص.'),
  ('media-podcast', 'media', 21, 'podcast', 'She listens to a news ___ every morning.', 'البودكاست.'),
  ('media-blog', 'media', 22, 'blog', 'He writes a travel ___ in his free time.', 'المدونة.'),
  ('media-editor', 'media', 23, 'editor', 'The ___ cut the article down by half.', 'المحرر.'),
  ('media-trending', 'media', 24, 'trending', 'The video has been ___ all week.', 'رائج/متصدر.'),
  ('media-hashtag', 'media', 25, 'hashtag', 'The campaign used a simple ___ to spread the message.', 'الهاشتاغ.'),
  ('travel-airport', 'travel', 21, 'airport', 'We arrived at the ___ two hours early.', 'المطار.'),
  ('travel-flight', 'travel', 22, 'flight', 'Our ___ was delayed by an hour.', 'الرحلة الجوية.'),
  ('travel-hotel', 'travel', 23, 'hotel', 'The ___ was right next to the beach.', 'الفندق.'),
  ('travel-tourist', 'travel', 24, 'tourist', 'The old town is full of ___s in summer.', 'السائح.'),
  ('travel-map', 'travel', 25, 'map', 'She checked the ___ before leaving the hotel.', 'الخريطة.'),
  ('colors-navy', 'colors', 21, 'navy', 'He wore a ___ blazer to the wedding.', 'كحلي (أزرق داكن).'),
  ('colors-teal', 'colors', 22, 'teal', 'The walls were painted a calm ___.', 'أزرق مخضر.'),
  ('colors-coral', 'colors', 23, 'coral', 'Her dress was a soft ___ color.', 'لون مرجاني.'),
  ('colors-ivory', 'colors', 24, 'ivory', 'The invitation card was printed on ___ paper.', 'عاجي.'),
  ('colors-bronze', 'colors', 25, 'bronze', 'She won the ___ medal in the race.', 'برونزي.') on conflict (id) do nothing;

commit;
