-- Library expansion round 2: 4 more books — one more Business, one
-- more Biography, and two more History & Society, filling the exact
-- gaps identified after the first round. Applied to the live project
-- via scripts/insert-books-2.ts; captured here for tracking.
begin;

insert into books (id, title, author, description, difficulty_level, is_featured, is_free, status, order_index) values
  ('book-the-lean-startup', 'The Lean Startup', 'Eric Ries', 'An original SentenceStep summary of Eric Ries'' methodology for building startups through rapid experimentation, validated learning, and a build-measure-learn loop instead of guessing what customers want', 2, false, true, 'published', 19),
  ('book-steve-jobs', 'Steve Jobs', 'Walter Isaacson', 'An original SentenceStep summary of Walter Isaacson''s biography of Steve Jobs, tracing his unconventional upbringing, obsessive perfectionism, and the highs and lows of building Apple into one of the world''s most valuable companies', 2, false, true, 'published', 20),
  ('book-guns-germs-and-steel', 'Guns, Germs, and Steel', 'Jared Diamond', 'An original SentenceStep summary of Jared Diamond''s Pulitzer Prize winning explanation for why some societies conquered others, arguing that geography, agriculture, and disease shaped history far more than any innate difference between peoples', 3, false, true, 'published', 21),
  ('book-outliers', 'Outliers', 'Malcolm Gladwell', 'An original SentenceStep summary of Malcolm Gladwell''s argument that extraordinary success comes less from raw individual talent and more from hidden advantages, timing, culture, and thousands of hours of practice', 2, false, true, 'published', 22) on conflict (id) do nothing;

insert into book_categories (book_id, category_id, is_primary) values
  ('book-the-lean-startup', 'category-business', true),
  ('book-the-lean-startup', 'category-productivity', false),
  ('book-steve-jobs', 'category-biography', true),
  ('book-steve-jobs', 'category-business', false),
  ('book-guns-germs-and-steel', 'category-history', true),
  ('book-guns-germs-and-steel', 'category-philosophy', false),
  ('book-outliers', 'category-history', true),
  ('book-outliers', 'category-psychology', false) on conflict (book_id, category_id) do nothing;

insert into book_sections (id, book_id, order_index, title, description) values
  ('book-the-lean-startup-sec1', 'book-the-lean-startup', 1, 'Why Most Startups Fail', 'Ries'' core claim: startups fail from building the wrong thing, not building it badly'),
  ('book-the-lean-startup-sec2', 'book-the-lean-startup', 2, 'The Build-Measure-Learn Loop', 'The repeating cycle at the center of the whole method'),
  ('book-the-lean-startup-sec3', 'book-the-lean-startup', 3, 'The Minimum Viable Product', 'The smallest experiment that still teaches something real'),
  ('book-the-lean-startup-sec4', 'book-the-lean-startup', 4, 'Validated Learning', 'Measuring progress by what you''ve actually proven, not by activity'),
  ('book-the-lean-startup-sec5', 'book-the-lean-startup', 5, 'Actionable Metrics vs Vanity Metrics', 'Numbers tied to a real, controllable cause versus numbers that just look good'),
  ('book-the-lean-startup-sec6', 'book-the-lean-startup', 6, 'The Pivot', 'Why changing direction is a normal, expected part of the process'),
  ('book-the-lean-startup-sec7', 'book-the-lean-startup', 7, 'Innovation Accounting', 'Turning vague optimism into concrete, testable milestones'),
  ('book-the-lean-startup-sec8', 'book-the-lean-startup', 8, 'Small Batches', 'Why releasing tiny changes often beats releasing big ones'),
  ('book-the-lean-startup-sec9', 'book-the-lean-startup', 9, 'Building an Adaptive Organization', 'Why the method is a way of running a company, not just launching one'),
  ('book-steve-jobs-sec1', 'book-steve-jobs', 1, 'An Adopted Child With Big Questions', 'Jobs'' early life, his adoption, and an intensity that unsettled his teachers'),
  ('book-steve-jobs-sec2', 'book-steve-jobs', 2, 'Dropping Out, Dropping In', 'College, calligraphy, and a search for meaning that later shaped his design instincts'),
  ('book-steve-jobs-sec3', 'book-steve-jobs', 3, 'Building Apple in a Garage', 'How Jobs and Steve Wozniak turned very different talents into one company'),
  ('book-steve-jobs-sec4', 'book-steve-jobs', 4, 'Reality Distortion Field', 'The intensity that produced extraordinary results and exhausted people around him'),
  ('book-steve-jobs-sec5', 'book-steve-jobs', 5, 'Exile From Apple', 'Losing his own company, and the quiet years that reshaped his thinking'),
  ('book-steve-jobs-sec6', 'book-steve-jobs', 6, 'Pixar and a Different Kind of Storytelling', 'A second identity built on patience and long-term creative investment'),
  ('book-steve-jobs-sec7', 'book-steve-jobs', 7, 'The Return to Apple', 'Coming back to a struggling company and radically simplifying it'),
  ('book-steve-jobs-sec8', 'book-steve-jobs', 8, 'iPod, iPhone, and Reinventing Industries', 'Products that didn''t just sell well but reshaped entire industries'),
  ('book-steve-jobs-sec9', 'book-steve-jobs', 9, 'Perfectionism as Both Gift and Cost', 'The uncompromising nature that produced beloved products and strained relationships'),
  ('book-steve-jobs-sec10', 'book-steve-jobs', 10, 'A Legacy Built on Intersection', 'Technology and the liberal arts, and a legacy weighed against real personal flaws'),
  ('book-guns-germs-and-steel-sec1', 'book-guns-germs-and-steel', 1, 'Yali''s Question', 'The simple question that launched Diamond''s search for an honest answer'),
  ('book-guns-germs-and-steel-sec2', 'book-guns-germs-and-steel', 2, 'The Head Start of Farming', 'Why a handful of regions got an early agricultural advantage'),
  ('book-guns-germs-and-steel-sec3', 'book-guns-germs-and-steel', 3, 'Domesticable Animals', 'Why only a handful of large mammals could ever be domesticated at all'),
  ('book-guns-germs-and-steel-sec4', 'book-guns-germs-and-steel', 4, 'Continental Axes', 'How the shape of a continent quietly decided how fast crops could spread'),
  ('book-guns-germs-and-steel-sec5', 'book-guns-germs-and-steel', 5, 'Germs as an Unintended Weapon', 'How disease, not weapons, decided the outcome of entire conquests'),
  ('book-guns-germs-and-steel-sec6', 'book-guns-germs-and-steel', 6, 'Writing and the Spread of Knowledge', 'Why so few societies ever invented writing completely from scratch'),
  ('book-guns-germs-and-steel-sec7', 'book-guns-germs-and-steel', 7, 'From Villages to States', 'The rough path from small bands to organized, centralized states'),
  ('book-guns-germs-and-steel-sec8', 'book-guns-germs-and-steel', 8, 'Steel and the Tools of Conquest', 'How access to metal ore closed the loop of guns, germs, and steel'),
  ('book-guns-germs-and-steel-sec9', 'book-guns-germs-and-steel', 9, 'Rejecting Simple Explanations', 'Replacing old prejudice with a more honest, evidence-based explanation'),
  ('book-outliers-sec1', 'book-outliers', 1, 'The Matthew Effect', 'How a birthday can quietly decide a hockey career before it starts'),
  ('book-outliers-sec2', 'book-outliers', 2, 'The 10,000 Hour Rule', 'Why mastery needs both real ability and thousands of hours of rare opportunity'),
  ('book-outliers-sec3', 'book-outliers', 3, 'The Trouble With Geniuses', 'Why being merely smart enough, plus the right social skills, often wins'),
  ('book-outliers-sec4', 'book-outliers', 4, 'The Importance of Where You''re From', 'How family background quietly teaches children different scripts for confidence'),
  ('book-outliers-sec5', 'book-outliers', 5, 'Rice Paddies and Math', 'A farming tradition''s surprising echo in a modern classroom'),
  ('book-outliers-sec6', 'book-outliers', 6, 'The Culture of Honor', 'How an old herding tradition still echoes generations later'),
  ('book-outliers-sec7', 'book-outliers', 7, 'Korean Air and the Power of Hierarchy', 'How reshaping communication style measurably saved lives'),
  ('book-outliers-sec8', 'book-outliers', 8, 'The Legacy of Meaningful Work', 'Why work that connects effort to reward shapes generations, not just individuals'),
  ('book-outliers-sec9', 'book-outliers', 9, 'Rethinking the Self-Made Story', 'Why every outlier''s story is really about circumstance as much as character') on conflict (id) do nothing;

insert into book_sentences (id, section_id, order_index, en) values
  ('book-the-lean-startup-sec1-s1', 'book-the-lean-startup-sec1', 1, 'Most startups fail not because they build a bad product but because they build something nobody actually wants'),
  ('book-the-lean-startup-sec1-s2', 'book-the-lean-startup-sec1', 2, 'Founders often spend months perfecting a plan before ever testing it against a real customer'),
  ('book-the-lean-startup-sec1-s3', 'book-the-lean-startup-sec1', 3, 'Ries argues that a startup is fundamentally an experiment not a smaller version of a big company'),
  ('book-the-lean-startup-sec1-s4', 'book-the-lean-startup-sec1', 4, 'Traditional business planning assumes a stable market that a young startup rarely actually has'),
  ('book-the-lean-startup-sec1-s5', 'book-the-lean-startup-sec1', 5, 'The real danger is building something efficiently that turns out to be entirely the wrong thing'),
  ('book-the-lean-startup-sec2-s1', 'book-the-lean-startup-sec2', 1, 'Ries proposes a simple repeating cycle called build measure learn'),
  ('book-the-lean-startup-sec2-s2', 'book-the-lean-startup-sec2', 2, 'A team builds a small piece of the product measures how real customers respond then learns from the result'),
  ('book-the-lean-startup-sec2-s3', 'book-the-lean-startup-sec2', 3, 'Each loop should be completed as quickly as possible rather than perfected before release'),
  ('book-the-lean-startup-sec2-s4', 'book-the-lean-startup-sec2', 4, 'Speed through this loop matters more than the size or polish of any single version'),
  ('book-the-lean-startup-sec2-s5', 'book-the-lean-startup-sec2', 5, 'Startups that loop faster than competitors gain a genuine learning advantage over time'),
  ('book-the-lean-startup-sec3-s1', 'book-the-lean-startup-sec3', 1, 'A minimum viable product is the smallest version of an idea that still teaches something real'),
  ('book-the-lean-startup-sec3-s2', 'book-the-lean-startup-sec3', 2, 'It is not a low-quality product but a deliberately limited experiment'),
  ('book-the-lean-startup-sec3-s3', 'book-the-lean-startup-sec3', 3, 'Ries describes early MVPs that were barely more than a landing page or a manual process'),
  ('book-the-lean-startup-sec3-s4', 'book-the-lean-startup-sec3', 4, 'The goal is gathering real evidence not impressing early users with polish'),
  ('book-the-lean-startup-sec3-s5', 'book-the-lean-startup-sec3', 5, 'Many founders resist releasing something so incomplete fearing it will damage their reputation'),
  ('book-the-lean-startup-sec4-s1', 'book-the-lean-startup-sec4', 1, 'Progress in a startup should be measured by validated learning not by activity or output'),
  ('book-the-lean-startup-sec4-s2', 'book-the-lean-startup-sec4', 2, 'A team can stay extremely busy while learning almost nothing useful about its customers'),
  ('book-the-lean-startup-sec4-s3', 'book-the-lean-startup-sec4', 3, 'Validated learning means testing a specific hypothesis and honestly recording what happened'),
  ('book-the-lean-startup-sec4-s4', 'book-the-lean-startup-sec4', 4, 'Vanity metrics like total signups can rise while the underlying business quietly fails'),
  ('book-the-lean-startup-sec4-s5', 'book-the-lean-startup-sec4', 5, 'Ries insists founders track numbers that actually predict future customer behavior'),
  ('book-the-lean-startup-sec5-s1', 'book-the-lean-startup-sec5', 1, 'Vanity metrics look impressive on a slide but rarely explain what caused them to change'),
  ('book-the-lean-startup-sec5-s2', 'book-the-lean-startup-sec5', 2, 'Actionable metrics are tied clearly to a specific cause the team can influence directly'),
  ('book-the-lean-startup-sec5-s3', 'book-the-lean-startup-sec5', 3, 'Ries recommends cohort analysis tracking how each group of new users behaves over time'),
  ('book-the-lean-startup-sec5-s4', 'book-the-lean-startup-sec5', 4, 'This approach reveals whether real product changes are actually improving customer behavior'),
  ('book-the-lean-startup-sec5-s5', 'book-the-lean-startup-sec5', 5, 'Founders who chase vanity metrics often celebrate growth that never becomes a real business'),
  ('book-the-lean-startup-sec6-s1', 'book-the-lean-startup-sec6', 1, 'A pivot is a structured change in strategy while keeping what has already been validated'),
  ('book-the-lean-startup-sec6-s2', 'book-the-lean-startup-sec6', 2, 'Ries argues that pivoting is not failure but a normal expected part of building something new'),
  ('book-the-lean-startup-sec6-s3', 'book-the-lean-startup-sec6', 3, 'Teams that never consider pivoting often keep pouring resources into a proven dead end'),
  ('book-the-lean-startup-sec6-s4', 'book-the-lean-startup-sec6', 4, 'Common pivots include changing the target customer the core feature or the entire business model'),
  ('book-the-lean-startup-sec6-s5', 'book-the-lean-startup-sec6', 5, 'Recognizing the right moment to pivot depends on honestly reviewing the loop''s own data'),
  ('book-the-lean-startup-sec7-s1', 'book-the-lean-startup-sec7', 1, 'Ries proposes innovation accounting a way to measure progress inside deep uncertainty'),
  ('book-the-lean-startup-sec7-s2', 'book-the-lean-startup-sec7', 2, 'Traditional accounting assumes a predictable business which an early startup rarely has'),
  ('book-the-lean-startup-sec7-s3', 'book-the-lean-startup-sec7', 3, 'Instead teams set a baseline then test specific changes meant to move it in one direction'),
  ('book-the-lean-startup-sec7-s4', 'book-the-lean-startup-sec7', 4, 'This turns vague optimism into a series of concrete falsifiable experiments'),
  ('book-the-lean-startup-sec7-s5', 'book-the-lean-startup-sec7', 5, 'Investors and teams can then judge progress by real evidence instead of by confident storytelling'),
  ('book-the-lean-startup-sec8-s1', 'book-the-lean-startup-sec8', 1, 'Ries borrows the idea of small batch production from lean manufacturing'),
  ('book-the-lean-startup-sec8-s2', 'book-the-lean-startup-sec8', 2, 'Releasing tiny changes frequently surfaces problems faster than releasing large batches rarely'),
  ('book-the-lean-startup-sec8-s3', 'book-the-lean-startup-sec8', 3, 'Small batches shrink the distance between a mistake and the feedback that reveals it'),
  ('book-the-lean-startup-sec8-s4', 'book-the-lean-startup-sec8', 4, 'This approach feels slower at first but usually prevents much larger wasted efforts later'),
  ('book-the-lean-startup-sec8-s5', 'book-the-lean-startup-sec8', 5, 'Teams working in small batches can also change direction far more quickly when needed'),
  ('book-the-lean-startup-sec9-s1', 'book-the-lean-startup-sec9', 1, 'The Lean Startup is not just a launch strategy but a way of running an ongoing organization'),
  ('book-the-lean-startup-sec9-s2', 'book-the-lean-startup-sec9', 2, 'Ries argues large companies can use these same methods to keep innovating internally'),
  ('book-the-lean-startup-sec9-s3', 'book-the-lean-startup-sec9', 3, 'Building adaptive processes matters more than any single brilliant idea a team starts with'),
  ('book-the-lean-startup-sec9-s4', 'book-the-lean-startup-sec9', 4, 'Discipline around experimentation not raw inspiration is what sustains innovation over years'),
  ('book-the-lean-startup-sec9-s5', 'book-the-lean-startup-sec9', 5, 'The book closes by urging every team large or small to treat uncertainty as something to test not guess'),
  ('book-steve-jobs-sec1-s1', 'book-steve-jobs-sec1', 1, 'Steve Jobs was given up for adoption at birth and raised by Paul and Clara Jobs in California'),
  ('book-steve-jobs-sec1-s2', 'book-steve-jobs-sec1', 2, 'Knowing he was adopted shaped a lifelong sense of being chosen but also somehow apart'),
  ('book-steve-jobs-sec1-s3', 'book-steve-jobs-sec1', 3, 'He showed an early intensity and impatience that unsettled many of his teachers'),
  ('book-steve-jobs-sec1-s4', 'book-steve-jobs-sec1', 4, 'His adoptive father''s careful garage craftsmanship left a lasting impression on him'),
  ('book-steve-jobs-sec1-s5', 'book-steve-jobs-sec1', 5, 'Even as a child Jobs expected the people and things around him to meet his own high standards'),
  ('book-steve-jobs-sec2-s1', 'book-steve-jobs-sec2', 1, 'Jobs enrolled at Reed College but dropped out after only one semester'),
  ('book-steve-jobs-sec2-s2', 'book-steve-jobs-sec2', 2, 'He kept auditing classes he found interesting including a calligraphy course'),
  ('book-steve-jobs-sec2-s3', 'book-steve-jobs-sec2', 3, 'That calligraphy class later shaped his obsession with beautiful typography on the Macintosh'),
  ('book-steve-jobs-sec2-s4', 'book-steve-jobs-sec2', 4, 'He experimented with a strict diet meditation and a trip to India seeking deeper meaning'),
  ('book-steve-jobs-sec2-s5', 'book-steve-jobs-sec2', 5, 'These wandering years exposed him to ideas about simplicity that never really left him'),
  ('book-steve-jobs-sec3-s1', 'book-steve-jobs-sec3', 1, 'Jobs partnered with his friend Steve Wozniak a brilliant and quieter engineer'),
  ('book-steve-jobs-sec3-s2', 'book-steve-jobs-sec3', 2, 'Wozniak built the technical genius behind the Apple I and Apple II computers'),
  ('book-steve-jobs-sec3-s3', 'book-steve-jobs-sec3', 3, 'Jobs supplied the relentless drive salesmanship and design instincts the young company needed'),
  ('book-steve-jobs-sec3-s4', 'book-steve-jobs-sec3', 4, 'Apple grew explosively turning both founders into visible symbols of the new computer age'),
  ('book-steve-jobs-sec3-s5', 'book-steve-jobs-sec3', 5, 'Their partnership combined two very different temperaments into one unusually effective team'),
  ('book-steve-jobs-sec4-s1', 'book-steve-jobs-sec4', 1, 'Colleagues described Jobs as having a reality distortion field around difficult conversations'),
  ('book-steve-jobs-sec4-s2', 'book-steve-jobs-sec4', 2, 'Through sheer conviction he could persuade people that an impossible deadline was still doable'),
  ('book-steve-jobs-sec4-s3', 'book-steve-jobs-sec4', 3, 'This intensity produced extraordinary results but also left many collaborators exhausted'),
  ('book-steve-jobs-sec4-s4', 'book-steve-jobs-sec4', 4, 'Jobs was famous for blunt sometimes harsh feedback he considered simply being honest'),
  ('book-steve-jobs-sec4-s5', 'book-steve-jobs-sec4', 5, 'Isaacson presents both the brilliance and real personal cost behind that same relentless drive'),
  ('book-steve-jobs-sec5-s1', 'book-steve-jobs-sec5', 1, 'A power struggle with Apple''s board eventually pushed Jobs out of his own company'),
  ('book-steve-jobs-sec5-s2', 'book-steve-jobs-sec5', 2, 'He described the experience as devastating even though it later reshaped his whole outlook'),
  ('book-steve-jobs-sec5-s3', 'book-steve-jobs-sec5', 3, 'Jobs founded NeXT a new computer company built around his exacting standards'),
  ('book-steve-jobs-sec5-s4', 'book-steve-jobs-sec5', 4, 'He also purchased a small animation studio that would eventually become Pixar'),
  ('book-steve-jobs-sec5-s5', 'book-steve-jobs-sec5', 5, 'These years outside Apple quietly prepared the ideas he would later bring back with him'),
  ('book-steve-jobs-sec6-s1', 'book-steve-jobs-sec6', 1, 'Under Jobs'' ownership Pixar developed groundbreaking computer animated films'),
  ('book-steve-jobs-sec6-s2', 'book-steve-jobs-sec6', 2, 'Toy Story became the first entirely computer animated feature film ever released'),
  ('book-steve-jobs-sec6-s3', 'book-steve-jobs-sec6', 3, 'Pixar''s success gave Jobs a rare second identity beyond the world of computers'),
  ('book-steve-jobs-sec6-s4', 'book-steve-jobs-sec6', 4, 'He learned patient long-term investment in a creative vision that took years to pay off'),
  ('book-steve-jobs-sec6-s5', 'book-steve-jobs-sec6', 5, 'This experience deepened his belief that great products come from genuine artistic care'),
  ('book-steve-jobs-sec7-s1', 'book-steve-jobs-sec7', 1, 'Apple struggling badly by the mid-1990s acquired NeXT and brought Jobs back'),
  ('book-steve-jobs-sec7-s2', 'book-steve-jobs-sec7', 2, 'He quickly moved from advisor to interim then permanent chief executive again'),
  ('book-steve-jobs-sec7-s3', 'book-steve-jobs-sec7', 3, 'Jobs radically simplified Apple''s confusing product line down to a handful of focused products'),
  ('book-steve-jobs-sec7-s4', 'book-steve-jobs-sec7', 4, 'The colorful iMac signaled a dramatic turnaround in both design and company morale'),
  ('book-steve-jobs-sec7-s5', 'book-steve-jobs-sec7', 5, 'His return marked the beginning of Apple''s transformation into a design-driven company'),
  ('book-steve-jobs-sec8-s1', 'book-steve-jobs-sec8', 1, 'The iPod combined hardware software and the iTunes store into one seamless experience'),
  ('book-steve-jobs-sec8-s2', 'book-steve-jobs-sec8', 2, 'Jobs insisted on controlling every detail from the chip inside to the packaging outside'),
  ('book-steve-jobs-sec8-s3', 'book-steve-jobs-sec8', 3, 'The iPhone later merged a phone an iPod and an internet device into a single product'),
  ('book-steve-jobs-sec8-s4', 'book-steve-jobs-sec8', 4, 'Each launch followed the same pattern obsessive secrecy followed by a dramatic public reveal'),
  ('book-steve-jobs-sec8-s5', 'book-steve-jobs-sec8', 5, 'These products didn''t just sell well they reshaped entire industries around Apple''s vision'),
  ('book-steve-jobs-sec9-s1', 'book-steve-jobs-sec9', 1, 'Jobs'' insistence on simplicity often meant removing features that seemed obviously convenient'),
  ('book-steve-jobs-sec9-s2', 'book-steve-jobs-sec9', 2, 'He would reject nearly finished designs at the last moment over details others considered minor'),
  ('book-steve-jobs-sec9-s3', 'book-steve-jobs-sec9', 3, 'This perfectionism frustrated many engineers even as it consistently produced beloved products'),
  ('book-steve-jobs-sec9-s4', 'book-steve-jobs-sec9', 4, 'Isaacson shows how the same uncompromising nature strained Jobs'' relationships throughout his life'),
  ('book-steve-jobs-sec9-s5', 'book-steve-jobs-sec9', 5, 'Colleagues often said working with him was simultaneously the hardest and most rewarding experience of their careers'),
  ('book-steve-jobs-sec10-s1', 'book-steve-jobs-sec10', 1, 'Jobs often described his best work as sitting at the intersection of technology and the liberal arts'),
  ('book-steve-jobs-sec10-s2', 'book-steve-jobs-sec10', 2, 'He battled cancer for years while continuing to lead Apple through major product launches'),
  ('book-steve-jobs-sec10-s3', 'book-steve-jobs-sec10', 3, 'Even in his final years he remained deeply involved in Apple''s design decisions'),
  ('book-steve-jobs-sec10-s4', 'book-steve-jobs-sec10', 4, 'Isaacson''s biography closes by weighing his enormous impact against his considerable personal flaws'),
  ('book-steve-jobs-sec10-s5', 'book-steve-jobs-sec10', 5, 'Jobs left behind not just products but a lasting standard for combining engineering with genuine beauty'),
  ('book-guns-germs-and-steel-sec1-s1', 'book-guns-germs-and-steel-sec1', 1, 'Diamond opens with a question a New Guinean politician named Yali once asked him directly'),
  ('book-guns-germs-and-steel-sec1-s2', 'book-guns-germs-and-steel-sec1', 2, 'Yali wanted to know why Europeans had so much cargo while his own people had comparatively little'),
  ('book-guns-germs-and-steel-sec1-s3', 'book-guns-germs-and-steel-sec1', 3, 'The book is Diamond''s attempt to answer that deceptively simple question honestly'),
  ('book-guns-germs-and-steel-sec1-s4', 'book-guns-germs-and-steel-sec1', 4, 'He firmly rejects the old racist idea that some peoples are simply more capable than others'),
  ('book-guns-germs-and-steel-sec1-s5', 'book-guns-germs-and-steel-sec1', 5, 'Instead he searches for environmental factors that shaped different societies'' historical paths'),
  ('book-guns-germs-and-steel-sec2-s1', 'book-guns-germs-and-steel-sec2', 1, 'Diamond argues that farming not intelligence gave certain regions an early historical head start'),
  ('book-guns-germs-and-steel-sec2-s2', 'book-guns-germs-and-steel-sec2', 2, 'Only a small number of wild plant and animal species were ever suitable for domestication'),
  ('book-guns-germs-and-steel-sec2-s3', 'book-guns-germs-and-steel-sec2', 3, 'The Fertile Crescent happened to contain an unusually rich concentration of these species'),
  ('book-guns-germs-and-steel-sec2-s4', 'book-guns-germs-and-steel-sec2', 4, 'Early farming allowed populations to grow denser and store surplus food for the first time'),
  ('book-guns-germs-and-steel-sec2-s5', 'book-guns-germs-and-steel-sec2', 5, 'That surplus eventually freed some people to specialize in tools writing and government'),
  ('book-guns-germs-and-steel-sec3-s1', 'book-guns-germs-and-steel-sec3', 1, 'Diamond explains why only a handful of large mammal species were ever successfully domesticated'),
  ('book-guns-germs-and-steel-sec3-s2', 'book-guns-germs-and-steel-sec3', 2, 'A domesticable animal needed the right temperament diet growth rate and social structure'),
  ('book-guns-germs-and-steel-sec3-s3', 'book-guns-germs-and-steel-sec3', 3, 'Regions like Eurasia happened to have far more of these suitable animal candidates'),
  ('book-guns-germs-and-steel-sec3-s4', 'book-guns-germs-and-steel-sec3', 4, 'Domesticated animals provided meat labor transportation and fertilizer for growing farms'),
  ('book-guns-germs-and-steel-sec3-s5', 'book-guns-germs-and-steel-sec3', 5, 'Societies without domesticable animals faced real unavoidable limits on their own development'),
  ('book-guns-germs-and-steel-sec4-s1', 'book-guns-germs-and-steel-sec4', 1, 'Diamond highlights the different shapes of Eurasia Africa and the Americas as continents'),
  ('book-guns-germs-and-steel-sec4-s2', 'book-guns-germs-and-steel-sec4', 2, 'Eurasia''s east-west axis let crops and livestock spread easily across similar climates'),
  ('book-guns-germs-and-steel-sec4-s3', 'book-guns-germs-and-steel-sec4', 3, 'Africa and the Americas stretch north-south crossing many very different climate zones'),
  ('book-guns-germs-and-steel-sec4-s4', 'book-guns-germs-and-steel-sec4', 4, 'Crops adapted to one region often failed when carried across these harsher climate boundaries'),
  ('book-guns-germs-and-steel-sec4-s5', 'book-guns-germs-and-steel-sec4', 5, 'This simple geographic difference slowed the spread of agriculture on some continents significantly'),
  ('book-guns-germs-and-steel-sec5-s1', 'book-guns-germs-and-steel-sec5', 1, 'Living closely with domesticated animals exposed farming societies to many new diseases'),
  ('book-guns-germs-and-steel-sec5-s2', 'book-guns-germs-and-steel-sec5', 2, 'Over centuries these populations built up partial immunity to smallpox measles and more'),
  ('book-guns-germs-and-steel-sec5-s3', 'book-guns-germs-and-steel-sec5', 3, 'When Europeans reached the Americas they carried these diseases to populations with no immunity'),
  ('book-guns-germs-and-steel-sec5-s4', 'book-guns-germs-and-steel-sec5', 4, 'Diamond argues these germs killed far more people than any European weapon ever did'),
  ('book-guns-germs-and-steel-sec5-s5', 'book-guns-germs-and-steel-sec5', 5, 'This devastating largely accidental biological advantage reshaped the outcome of entire conquests'),
  ('book-guns-germs-and-steel-sec6-s1', 'book-guns-germs-and-steel-sec6', 1, 'Dense agricultural societies eventually developed writing to track debts trade and history'),
  ('book-guns-germs-and-steel-sec6-s2', 'book-guns-germs-and-steel-sec6', 2, 'Written knowledge could travel and accumulate across many more generations than spoken memory alone'),
  ('book-guns-germs-and-steel-sec6-s3', 'book-guns-germs-and-steel-sec6', 3, 'Diamond traces how few independent centers ever invented writing completely from scratch'),
  ('book-guns-germs-and-steel-sec6-s4', 'book-guns-germs-and-steel-sec6', 4, 'Once invented writing systems often spread rapidly to neighboring societies through contact'),
  ('book-guns-germs-and-steel-sec6-s5', 'book-guns-germs-and-steel-sec6', 5, 'Literate societies could coordinate plan and later document conquest more effectively than others'),
  ('book-guns-germs-and-steel-sec7-s1', 'book-guns-germs-and-steel-sec7', 1, 'Diamond traces a rough pattern from small bands to villages chiefdoms and eventually states'),
  ('book-guns-germs-and-steel-sec7-s2', 'book-guns-germs-and-steel-sec7', 2, 'Denser populations required new forms of organization to manage conflict and resources fairly'),
  ('book-guns-germs-and-steel-sec7-s3', 'book-guns-germs-and-steel-sec7', 3, 'Centralized states could raise armies taxes and public projects far beyond a village''s ability'),
  ('book-guns-germs-and-steel-sec7-s4', 'book-guns-germs-and-steel-sec7', 4, 'This organizational advantage compounded alongside the advantages of farming animals and germs'),
  ('book-guns-germs-and-steel-sec7-s5', 'book-guns-germs-and-steel-sec7', 5, 'Societies that reached statehood earlier gained a further head start over their neighbors'),
  ('book-guns-germs-and-steel-sec8-s1', 'book-guns-germs-and-steel-sec8', 1, 'Access to metal ores and the resources to smelt them shaped which societies developed steel weapons'),
  ('book-guns-germs-and-steel-sec8-s2', 'book-guns-germs-and-steel-sec8', 2, 'Steel tools and weapons gave a decisive practical advantage in both farming and warfare'),
  ('book-guns-germs-and-steel-sec8-s3', 'book-guns-germs-and-steel-sec8', 3, 'Diamond connects this technological edge back to the same earlier agricultural and geographic advantages'),
  ('book-guns-germs-and-steel-sec8-s4', 'book-guns-germs-and-steel-sec8', 4, 'Societies without steel weapons faced conquerors whose equipment they simply could not match'),
  ('book-guns-germs-and-steel-sec8-s5', 'book-guns-germs-and-steel-sec8', 5, 'None of this reflected any difference in intelligence between the peoples involved'),
  ('book-guns-germs-and-steel-sec9-s1', 'book-guns-germs-and-steel-sec9', 1, 'Diamond closes by insisting environmental history explains far more than any racial theory ever could'),
  ('book-guns-germs-and-steel-sec9-s2', 'book-guns-germs-and-steel-sec9', 2, 'He acknowledges his framework as one important lens rather than a complete final answer'),
  ('book-guns-germs-and-steel-sec9-s3', 'book-guns-germs-and-steel-sec9', 3, 'The book argues history''s big winners benefited enormously from accidents of geography and biology'),
  ('book-guns-germs-and-steel-sec9-s4', 'book-guns-germs-and-steel-sec9', 4, 'Understanding these historical accidents replaces old prejudice with a more honest explanation'),
  ('book-guns-germs-and-steel-sec9-s5', 'book-guns-germs-and-steel-sec9', 5, 'Guns Germs and Steel ultimately asks readers to rethink assumptions about why history unfolded as it did'),
  ('book-outliers-sec1-s1', 'book-outliers-sec1', 1, 'Gladwell opens with Canadian hockey players noticing many share birthdays early in the year'),
  ('book-outliers-sec1-s2', 'book-outliers-sec1', 2, 'Youth hockey cutoff dates meant older kids within an age group looked more physically developed'),
  ('book-outliers-sec1-s3', 'book-outliers-sec1', 3, 'Coaches picked these slightly older kids for elite teams giving them better coaching early on'),
  ('book-outliers-sec1-s4', 'book-outliers-sec1', 4, 'That early advantage compounded over years into a real measurable difference in skill'),
  ('book-outliers-sec1-s5', 'book-outliers-sec1', 5, 'Small initial advantages Gladwell argues often snowball into outcomes that look purely like talent'),
  ('book-outliers-sec2-s1', 'book-outliers-sec2', 1, 'Gladwell popularizes research suggesting true mastery often requires around ten thousand hours of practice'),
  ('book-outliers-sec2-s2', 'book-outliers-sec2', 2, 'He traces how The Beatles played thousands of grueling hours in Hamburg clubs before fame'),
  ('book-outliers-sec2-s3', 'book-outliers-sec2', 3, 'Bill Gates gained rare early access to computer programming time most teenagers never had'),
  ('book-outliers-sec2-s4', 'book-outliers-sec2', 4, 'Neither raw talent nor sheer luck alone explained these outcomes without also examining opportunity'),
  ('book-outliers-sec2-s5', 'book-outliers-sec2', 5, 'Extraordinary achievement in this view requires both real ability and unusually favorable circumstances'),
  ('book-outliers-sec3-s1', 'book-outliers-sec3', 1, 'Gladwell examines Christopher Langan a man with an extraordinarily high measured IQ'),
  ('book-outliers-sec3-s2', 'book-outliers-sec3', 2, 'Despite his brilliance Langan struggled to navigate universities and secure institutional support'),
  ('book-outliers-sec3-s3', 'book-outliers-sec3', 3, 'Gladwell contrasts him with Robert Oppenheimer who effectively charmed his way past serious trouble'),
  ('book-outliers-sec3-s4', 'book-outliers-sec3', 4, 'Practical intelligence often shaped by upbringing mattered as much as raw analytical intelligence'),
  ('book-outliers-sec3-s5', 'book-outliers-sec3', 5, 'Being merely smart enough paired with the right social skills often outperforms pure genius alone'),
  ('book-outliers-sec4-s1', 'book-outliers-sec4', 1, 'Gladwell explores how family background quietly shapes a child''s practical confidence'),
  ('book-outliers-sec4-s2', 'book-outliers-sec4', 2, 'Wealthier parents often taught children to negotiate comfortably with teachers and institutions'),
  ('book-outliers-sec4-s3', 'book-outliers-sec4', 3, 'Poorer families frequently taught respectful deference that could limit opportunities later on'),
  ('book-outliers-sec4-s4', 'book-outliers-sec4', 4, 'These inherited habits learned early shaped very different paths through school and career'),
  ('book-outliers-sec4-s5', 'book-outliers-sec4', 5, 'Cultural legacies of this kind often outlast the specific circumstances that first created them'),
  ('book-outliers-sec5-s1', 'book-outliers-sec5', 1, 'Gladwell links strong math performance among some Asian students to a rice farming heritage'),
  ('book-outliers-sec5-s2', 'book-outliers-sec5', 2, 'Rice cultivation traditionally demanded extraordinary sustained effort across the entire year'),
  ('book-outliers-sec5-s3', 'book-outliers-sec5', 3, 'This cultural legacy of tireless persistent work he argues transferred naturally into schooling'),
  ('book-outliers-sec5-s4', 'book-outliers-sec5', 4, 'Meaningful demanding work historically shaped cultural attitudes toward effort and persistence'),
  ('book-outliers-sec5-s5', 'book-outliers-sec5', 5, 'Success again reflects inherited cultural patterns as much as any purely individual trait'),
  ('book-outliers-sec6-s1', 'book-outliers-sec6', 1, 'Gladwell examines patterns of violence in parts of the American South tied to herding traditions'),
  ('book-outliers-sec6-s2', 'book-outliers-sec6', 2, 'Herding communities historically needed to defend livestock fiercely without relying on formal law'),
  ('book-outliers-sec6-s3', 'book-outliers-sec6', 3, 'That inherited culture of honor persisted long after the original herding economy had disappeared'),
  ('book-outliers-sec6-s4', 'book-outliers-sec6', 4, 'He connects this cultural legacy to a real tragic airline disaster involving communication failures'),
  ('book-outliers-sec6-s5', 'book-outliers-sec6', 5, 'Deeply ingrained cultural habits Gladwell shows can quietly shape behavior generations later'),
  ('book-outliers-sec7-s1', 'book-outliers-sec7', 1, 'Gladwell examines a period when Korean Air experienced an unusually high rate of plane crashes'),
  ('book-outliers-sec7-s2', 'book-outliers-sec7', 2, 'Cultural deference toward senior pilots sometimes discouraged junior crew from voicing urgent concerns'),
  ('book-outliers-sec7-s3', 'book-outliers-sec7', 3, 'Investigators found this hierarchy occasionally delayed critical safety warnings during real emergencies'),
  ('book-outliers-sec7-s4', 'book-outliers-sec7', 4, 'The airline eventually retrained crews specifically to communicate more directly regardless of rank'),
  ('book-outliers-sec7-s5', 'book-outliers-sec7', 5, 'Crash rates dropped sharply afterward showing how cultural patterns can be deliberately reshaped'),
  ('book-outliers-sec8-s1', 'book-outliers-sec8', 1, 'Gladwell argues satisfying work generally combines autonomy complexity and a clear connection between effort and reward'),
  ('book-outliers-sec8-s2', 'book-outliers-sec8', 2, 'Immigrant garment workers he profiles found real pride and eventual success through demanding structured labor'),
  ('book-outliers-sec8-s3', 'book-outliers-sec8', 3, 'That same combination he argues predicts long-term satisfaction across very different occupations'),
  ('book-outliers-sec8-s4', 'book-outliers-sec8', 4, 'Meaningful work not merely well-paid work shapes families'' opportunities across later generations'),
  ('book-outliers-sec8-s5', 'book-outliers-sec8', 5, 'These patterns often echo forward shaping the outlooks of children who never did that original work themselves'),
  ('book-outliers-sec9-s1', 'book-outliers-sec9', 1, 'Gladwell closes by questioning the popular myth of the purely self-made individual success story'),
  ('book-outliers-sec9-s2', 'book-outliers-sec9', 2, 'Every outlier he profiles benefited from specific often overlooked advantages of timing and culture'),
  ('book-outliers-sec9-s3', 'book-outliers-sec9', 3, 'None of this diminishes real talent and effort both of which clearly still matter enormously'),
  ('book-outliers-sec9-s4', 'book-outliers-sec9', 4, 'Recognizing hidden advantages he argues could help societies extend similar opportunities more widely'),
  ('book-outliers-sec9-s5', 'book-outliers-sec9', 5, 'Outliers ultimately reframes extraordinary success as a story about circumstance as much as character') on conflict (id) do nothing;

commit;
