-- Stories Library redesign: 6 stories x 12 sentences each, replacing the
-- previous 2 stories x 24 sentences. Distributed across all 3 levels
-- (2 per level) so the new library's three level filters each have real
-- content. Normal-mode and Conversation content are untouched.
--
-- Generated from the same TypeScript source the app reads locally
-- (src/data/lessons/stories.ts) by a one-off script mirroring
-- scripts/generate-content-seed.ts's approach.
--
-- No order_index collision risk here (unlike the earlier normal-mode
-- migration): story-1 keeps order_index 1, story-2 moves from 2 to 3
-- (currently unoccupied, since only 2 stories exist today), and the 4
-- new stories take order_index 2, 4, 5, 6 -- none of which any existing
-- row currently holds. Wrapped in a transaction regardless, so a failure
-- rolls back cleanly instead of leaving a half-migrated state.
begin;

-- Lessons: full replacement of the stories-mode library
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('story-1', 'stories', (select id from levels where mode = 'stories' and index = 1), 1, 'A New Neighbor', 'جارة جديدة', 'Layla meets the new neighbor moving in next door — and a friendship begins.', 'تلتقي ليلى بالجارة الجديدة التي تنتقل إلى الشقة المجاورة، وتبدأ صداقة.', true, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('story-3', 'stories', (select id from levels where mode = 'stories' and index = 1), 2, 'The Missing Shoe', 'الحذاء المفقود', 'A frantic morning search ends with the last suspect Ali expected.', 'ينتهي بحث محموم في الصباح باكتشاف لم يكن عليّ يتوقعه إطلاقاً.', true, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('story-2', 'stories', (select id from levels where mode = 'stories' and index = 2), 3, 'The Job Interview', 'مقابلة العمل', 'Ahmed prepares for an important interview and learns that preparation pays off.', 'يستعد أحمد لمقابلة عمل مهمة، ويكتشف أن التحضير الجيد يُثمر.', true, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('story-4', 'stories', (select id from levels where mode = 'stories' and index = 2), 4, 'A Night at the Airport', 'ليلة في المطار', 'A long delay turns into an unexpectedly memorable night with a stranger.', 'يتحول تأخير طويل إلى ليلة لا تُنسى مع شخص غريب.', false, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('story-5', 'stories', (select id from levels where mode = 'stories' and index = 3), 5, 'The Old Photograph', 'الصورة القديمة', 'A photograph tucked inside an old book reveals a side of her grandmother she never knew.', 'تكشف صورة داخل كتاب قديم جانباً من جدتها لم تكن تعرفه.', false, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('story-6', 'stories', (select id from levels where mode = 'stories' and index = 3), 6, 'A Very Bad First Date', 'موعد أول كارثي', 'Everything that could go wrong does — and somehow, that''s what makes it work.', 'كل ما يمكن أن يسوء يسوء، لكن ذلك بالتحديد ما يجعل الموعد ناجحاً بطريقته الخاصة.', false, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();

-- Sentences
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s1', 'story-1', 0, 'Layla lived alone in a quiet building', 'كانت ليلى تعيش وحدها في بناية هادئة.', null, '[{"en":"Layla","ar":"ليلى"},{"en":"lived","ar":"كانت تعيش"},{"en":"alone","ar":"وحدها"},{"en":"in","ar":"في"},{"en":"a","ar":"واحدة"},{"en":"quiet","ar":"هادئة"},{"en":"building","ar":"بناية"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s2', 'story-1', 1, 'One morning, she heard noise next door', 'في صباح أحد الأيام، سمعت ضجيجاً من الجيران.', null, '[{"en":"One","ar":"أحد"},{"en":"morning,","ar":"الأيام،"},{"en":"she","ar":"هي"},{"en":"heard","ar":"سمعت"},{"en":"noise","ar":"ضجيجاً"},{"en":"next","ar":"المجاورة"},{"en":"door","ar":"الباب"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s3', 'story-1', 2, 'A new family was moving in', 'كانت عائلة جديدة تنتقل للسكن هناك.', null, '[{"en":"A","ar":"واحدة"},{"en":"new","ar":"جديدة"},{"en":"family","ar":"عائلة"},{"en":"was","ar":"كانت"},{"en":"moving","ar":"تنتقل"},{"en":"in","ar":"للسكن"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s4', 'story-1', 3, 'Layla opened her door to look', 'فتحت ليلى بابها لتنظر.', null, '[{"en":"Layla","ar":"ليلى"},{"en":"opened","ar":"فتحت"},{"en":"her","ar":"لها"},{"en":"door","ar":"بابها"},{"en":"to","ar":"لـ"},{"en":"look","ar":"تنظر"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s5', 'story-1', 4, 'A woman was carrying heavy boxes', 'كانت امرأة تحمل صناديق ثقيلة.', null, '[{"en":"A","ar":"واحدة"},{"en":"woman","ar":"امرأة"},{"en":"was","ar":"كانت"},{"en":"carrying","ar":"تحمل"},{"en":"heavy","ar":"ثقيلة"},{"en":"boxes","ar":"صناديق"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s6', 'story-1', 5, 'Layla asked if she needed help', 'سألت ليلى إن كانت بحاجة إلى مساعدة.', null, '[{"en":"Layla","ar":"ليلى"},{"en":"asked","ar":"سألت"},{"en":"if","ar":"إن"},{"en":"she","ar":"كانت"},{"en":"needed","ar":"بحاجة"},{"en":"help","ar":"مساعدة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s7', 'story-1', 6, 'The woman smiled and said yes', 'ابتسمت المرأة وقالت نعم.', null, '[{"en":"The","ar":"الـ"},{"en":"woman","ar":"المرأة"},{"en":"smiled","ar":"ابتسمت"},{"en":"and","ar":"و"},{"en":"said","ar":"قالت"},{"en":"yes","ar":"نعم"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s8', 'story-1', 7, 'Her name was Noor, new to the city', 'كان اسمها نور، وهي جديدة في المدينة.', null, '[{"en":"Her","ar":"لها"},{"en":"name","ar":"اسم"},{"en":"was","ar":"كان"},{"en":"Noor,","ar":"نور،"},{"en":"new","ar":"جديدة"},{"en":"to","ar":"في"},{"en":"the","ar":"الـ"},{"en":"city","ar":"المدينة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s9', 'story-1', 8, 'Layla helped carry the last boxes inside', 'ساعدت ليلى في حمل الصناديق الأخيرة إلى الداخل.', null, '[{"en":"Layla","ar":"ليلى"},{"en":"helped","ar":"ساعدت"},{"en":"carry","ar":"حمل"},{"en":"the","ar":"الـ"},{"en":"last","ar":"الأخيرة"},{"en":"boxes","ar":"الصناديق"},{"en":"inside","ar":"إلى الداخل"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s10', 'story-1', 9, 'Noor made two cups of tea', 'أعدت نور كوبين من الشاي.', null, '[{"en":"Noor","ar":"نور"},{"en":"made","ar":"أعدت"},{"en":"two","ar":"كوبين"},{"en":"cups","ar":"أكواب"},{"en":"of","ar":"من"},{"en":"tea","ar":"الشاي"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s11', 'story-1', 10, 'They talked and laughed for an hour', 'تحدثتا وضحكتا لمدة ساعة.', null, '[{"en":"They","ar":"هما"},{"en":"talked","ar":"تحدثتا"},{"en":"and","ar":"و"},{"en":"laughed","ar":"ضحكتا"},{"en":"for","ar":"لمدة"},{"en":"an","ar":"واحدة"},{"en":"hour","ar":"ساعة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-1-s12', 'story-1', 11, 'Layla left with a new friend', 'غادرت ليلى وقد كسبت صديقة جديدة.', null, '[{"en":"Layla","ar":"ليلى"},{"en":"left","ar":"غادرت"},{"en":"with","ar":"مع"},{"en":"a","ar":"واحدة"},{"en":"new","ar":"جديدة"},{"en":"friend","ar":"صديقة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s1', 'story-3', 0, 'Ali was already late for school', 'كان علي متأخراً بالفعل عن المدرسة.', null, '[{"en":"Ali","ar":"علي"},{"en":"was","ar":"كان"},{"en":"already","ar":"بالفعل"},{"en":"late","ar":"متأخراً"},{"en":"for","ar":"عن"},{"en":"school","ar":"المدرسة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s2', 'story-3', 1, 'He looked everywhere for his left shoe', 'بحث في كل مكان عن حذائه الأيسر.', null, '[{"en":"He","ar":"هو"},{"en":"looked","ar":"بحث"},{"en":"everywhere","ar":"في كل مكان"},{"en":"for","ar":"عن"},{"en":"his","ar":"له"},{"en":"left","ar":"الأيسر"},{"en":"shoe","ar":"حذاء"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s3', 'story-3', 2, 'It was not under his bed', 'لم يكن تحت سريره.', null, '[{"en":"It","ar":"هو"},{"en":"was","ar":"كان"},{"en":"not","ar":"ليس"},{"en":"under","ar":"تحت"},{"en":"his","ar":"له"},{"en":"bed","ar":"سريره"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s4', 'story-3', 3, 'It was not behind the door', 'لم يكن خلف الباب.', null, '[{"en":"It","ar":"هو"},{"en":"was","ar":"كان"},{"en":"not","ar":"ليس"},{"en":"behind","ar":"خلف"},{"en":"the","ar":"الـ"},{"en":"door","ar":"الباب"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s5', 'story-3', 4, 'His little sister was strangely quiet', 'كانت أخته الصغيرة هادئة بشكل غريب.', null, '[{"en":"His","ar":"له"},{"en":"little","ar":"الصغيرة"},{"en":"sister","ar":"أخته"},{"en":"was","ar":"كانت"},{"en":"strangely","ar":"بشكل غريب"},{"en":"quiet","ar":"هادئة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s6', 'story-3', 5, 'Ali found her in the kitchen', 'وجدها علي في المطبخ.', null, '[{"en":"Ali","ar":"علي"},{"en":"found","ar":"وجد"},{"en":"her","ar":"ها"},{"en":"in","ar":"في"},{"en":"the","ar":"الـ"},{"en":"kitchen","ar":"المطبخ"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s7', 'story-3', 6, 'She was feeding the shoe to the dog', 'كانت تُطعم الحذاء للكلب.', null, '[{"en":"She","ar":"هي"},{"en":"was","ar":"كانت"},{"en":"feeding","ar":"تُطعم"},{"en":"the","ar":"الـ"},{"en":"shoe","ar":"الحذاء"},{"en":"to","ar":"لـ"},{"en":"the","ar":"الـ"},{"en":"dog","ar":"الكلب"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s8', 'story-3', 7, 'The dog looked very confused', 'بدا الكلب مرتبكاً جداً.', null, '[{"en":"The","ar":"الـ"},{"en":"dog","ar":"الكلب"},{"en":"looked","ar":"بدا"},{"en":"very","ar":"جداً"},{"en":"confused","ar":"مرتبكاً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s9', 'story-3', 8, 'Ali could not stop laughing', 'لم يستطع علي التوقف عن الضحك.', null, '[{"en":"Ali","ar":"علي"},{"en":"could","ar":"استطاع"},{"en":"not","ar":"لم"},{"en":"stop","ar":"يتوقف"},{"en":"laughing","ar":"عن الضحك"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s10', 'story-3', 9, 'He wore his old shoes instead', 'ارتدى حذاءه القديم بدلاً منه.', null, '[{"en":"He","ar":"هو"},{"en":"wore","ar":"ارتدى"},{"en":"his","ar":"له"},{"en":"old","ar":"القديم"},{"en":"shoes","ar":"حذاءه"},{"en":"instead","ar":"بدلاً منه"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s11', 'story-3', 10, 'He told the story to his friends', 'أخبر أصدقاءه بالقصة.', null, '[{"en":"He","ar":"هو"},{"en":"told","ar":"أخبر"},{"en":"the","ar":"الـ"},{"en":"story","ar":"بالقصة"},{"en":"to","ar":"لـ"},{"en":"his","ar":"له"},{"en":"friends","ar":"أصدقاءه"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-3-s12', 'story-3', 11, 'Now everyone calls him Shoe Boy', 'الآن يناديه الجميع بفتى الحذاء.', null, '[{"en":"Now","ar":"الآن"},{"en":"everyone","ar":"الجميع"},{"en":"calls","ar":"يناديه"},{"en":"him","ar":"ه"},{"en":"Shoe","ar":"الحذاء"},{"en":"Boy","ar":"بفتى"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s1', 'story-2', 0, 'Ahmed had an important interview at nine', 'كان لدى أحمد مقابلة مهمة الساعة التاسعة.', null, '[{"en":"Ahmed","ar":"أحمد"},{"en":"had","ar":"كان لديه"},{"en":"an","ar":"واحدة"},{"en":"important","ar":"مهمة"},{"en":"interview","ar":"مقابلة"},{"en":"at","ar":"الساعة"},{"en":"nine","ar":"التاسعة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s2', 'story-2', 1, 'He practiced his answers all week', 'تدرب على إجاباته طوال الأسبوع.', null, '[{"en":"He","ar":"هو"},{"en":"practiced","ar":"تدرب على"},{"en":"his","ar":"له"},{"en":"answers","ar":"إجاباته"},{"en":"all","ar":"طوال"},{"en":"week","ar":"الأسبوع"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s3', 'story-2', 2, 'On the morning of the interview, he overslept', 'في صباح المقابلة، استيقظ متأخراً.', null, '[{"en":"On","ar":"في"},{"en":"the","ar":"الـ"},{"en":"morning","ar":"صباح"},{"en":"of","ar":"الـ"},{"en":"the","ar":"الـ"},{"en":"interview,","ar":"المقابلة،"},{"en":"he","ar":"هو"},{"en":"overslept","ar":"استيقظ متأخراً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s4', 'story-2', 3, 'He rushed out without eating breakfast', 'خرج مسرعاً دون تناول الفطور.', null, '[{"en":"He","ar":"هو"},{"en":"rushed","ar":"خرج مسرعاً"},{"en":"out","ar":"للخارج"},{"en":"without","ar":"دون"},{"en":"eating","ar":"تناول"},{"en":"breakfast","ar":"الفطور"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s5', 'story-2', 4, 'Traffic was heavier than he expected', 'كان الازدحام أكثر مما توقع.', null, '[{"en":"Traffic","ar":"الازدحام"},{"en":"was","ar":"كان"},{"en":"heavier","ar":"أكثر"},{"en":"than","ar":"مما"},{"en":"he","ar":"هو"},{"en":"expected","ar":"توقع"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s6', 'story-2', 5, 'He arrived just two minutes early', 'وصل قبل الموعد بدقيقتين فقط.', null, '[{"en":"He","ar":"هو"},{"en":"arrived","ar":"وصل"},{"en":"just","ar":"فقط"},{"en":"two","ar":"بدقيقتين"},{"en":"minutes","ar":"دقائق"},{"en":"early","ar":"مبكراً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s7', 'story-2', 6, 'His hands were shaking as he sat down', 'كانت يداه ترتجفان وهو يجلس.', null, '[{"en":"His","ar":"له"},{"en":"hands","ar":"يداه"},{"en":"were","ar":"كانتا"},{"en":"shaking","ar":"ترتجفان"},{"en":"as","ar":"بينما"},{"en":"he","ar":"هو"},{"en":"sat","ar":"يجلس"},{"en":"down","ar":"أسفل"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s8', 'story-2', 7, 'The interviewer asked about his experience', 'سأله القائم بالمقابلة عن خبرته.', null, '[{"en":"The","ar":"الـ"},{"en":"interviewer","ar":"القائم بالمقابلة"},{"en":"asked","ar":"سأل"},{"en":"about","ar":"عن"},{"en":"his","ar":"له"},{"en":"experience","ar":"خبرته"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s9', 'story-2', 8, 'Ahmed answered clearly and confidently', 'أجاب أحمد بوضوح وثقة.', null, '[{"en":"Ahmed","ar":"أحمد"},{"en":"answered","ar":"أجاب"},{"en":"clearly","ar":"بوضوح"},{"en":"and","ar":"و"},{"en":"confidently","ar":"بثقة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s10', 'story-2', 9, 'He mentioned a project he was proud of', 'ذكر مشروعاً كان فخوراً به.', null, '[{"en":"He","ar":"هو"},{"en":"mentioned","ar":"ذكر"},{"en":"a","ar":"واحداً"},{"en":"project","ar":"مشروعاً"},{"en":"he","ar":"هو"},{"en":"was","ar":"كان"},{"en":"proud","ar":"فخوراً"},{"en":"of","ar":"به"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s11', 'story-2', 10, 'The interviewer smiled and nodded', 'ابتسم القائم بالمقابلة وأومأ برأسه.', null, '[{"en":"The","ar":"الـ"},{"en":"interviewer","ar":"القائم بالمقابلة"},{"en":"smiled","ar":"ابتسم"},{"en":"and","ar":"و"},{"en":"nodded","ar":"أومأ برأسه"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-2-s12', 'story-2', 11, 'A week later, Ahmed got the job', 'بعد أسبوع، حصل أحمد على الوظيفة.', null, '[{"en":"A","ar":"واحد"},{"en":"week","ar":"أسبوع"},{"en":"later,","ar":"بعد،"},{"en":"Ahmed","ar":"أحمد"},{"en":"got","ar":"حصل على"},{"en":"the","ar":"الـ"},{"en":"job","ar":"الوظيفة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s1', 'story-4', 0, 'Sara''s flight was delayed by six hours', 'تأخرت رحلة سارة ست ساعات.', null, '[{"en":"Sara''s","ar":"لسارة"},{"en":"flight","ar":"رحلة"},{"en":"was","ar":"تأخرت"},{"en":"delayed","ar":"متأخرة"},{"en":"by","ar":"بمقدار"},{"en":"six","ar":"ست"},{"en":"hours","ar":"ساعات"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s2', 'story-4', 1, 'She had never spent a night in an airport', 'لم تقضِ ليلة في مطار من قبل.', null, '[{"en":"She","ar":"هي"},{"en":"had","ar":"لم"},{"en":"never","ar":"أبداً"},{"en":"spent","ar":"تقضِ"},{"en":"a","ar":"واحدة"},{"en":"night","ar":"ليلة"},{"en":"in","ar":"في"},{"en":"an","ar":"واحد"},{"en":"airport","ar":"مطار"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s3', 'story-4', 2, 'Every seat near her gate was taken', 'كانت كل المقاعد قرب بوابتها مشغولة.', null, '[{"en":"Every","ar":"كل"},{"en":"seat","ar":"مقعد"},{"en":"near","ar":"قرب"},{"en":"her","ar":"لها"},{"en":"gate","ar":"بوابتها"},{"en":"was","ar":"كانت"},{"en":"taken","ar":"مشغولة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s4', 'story-4', 3, 'She found a quiet corner near a window', 'وجدت زاوية هادئة قرب نافذة.', null, '[{"en":"She","ar":"هي"},{"en":"found","ar":"وجدت"},{"en":"a","ar":"واحدة"},{"en":"quiet","ar":"هادئة"},{"en":"corner","ar":"زاوية"},{"en":"near","ar":"قرب"},{"en":"a","ar":"واحدة"},{"en":"window","ar":"نافذة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s5', 'story-4', 4, 'A stranger offered her half of his sandwich', 'عرض عليها غريب نصف شطيرته.', null, '[{"en":"A","ar":"واحد"},{"en":"stranger","ar":"غريب"},{"en":"offered","ar":"عرض"},{"en":"her","ar":"عليها"},{"en":"half","ar":"نصف"},{"en":"of","ar":"من"},{"en":"his","ar":"له"},{"en":"sandwich","ar":"شطيرته"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s6', 'story-4', 5, 'They started talking to pass the time', 'بدآ الحديث لتمضية الوقت.', null, '[{"en":"They","ar":"هما"},{"en":"started","ar":"بدآ"},{"en":"talking","ar":"الحديث"},{"en":"to","ar":"لـ"},{"en":"pass","ar":"تمضية"},{"en":"the","ar":"الـ"},{"en":"time","ar":"الوقت"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s7', 'story-4', 6, 'He was flying home after two years abroad', 'كان عائداً إلى وطنه بعد عامين في الخارج.', null, '[{"en":"He","ar":"هو"},{"en":"was","ar":"كان"},{"en":"flying","ar":"عائداً"},{"en":"home","ar":"إلى وطنه"},{"en":"after","ar":"بعد"},{"en":"two","ar":"عامين"},{"en":"years","ar":"سنوات"},{"en":"abroad","ar":"في الخارج"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s8', 'story-4', 7, 'Sara told him about her upcoming job', 'أخبرته سارة عن وظيفتها القادمة.', null, '[{"en":"Sara","ar":"سارة"},{"en":"told","ar":"أخبرت"},{"en":"him","ar":"ه"},{"en":"about","ar":"عن"},{"en":"her","ar":"لها"},{"en":"upcoming","ar":"القادمة"},{"en":"job","ar":"وظيفتها"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s9', 'story-4', 8, 'Hours passed without either of them noticing', 'مرت الساعات دون أن يلاحظا.', null, '[{"en":"Hours","ar":"الساعات"},{"en":"passed","ar":"مرت"},{"en":"without","ar":"دون"},{"en":"either","ar":"أي"},{"en":"of","ar":"من"},{"en":"them","ar":"هما"},{"en":"noticing","ar":"أن يلاحظا"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s10', 'story-4', 9, 'Her flight was finally called at dawn', 'أُعلن أخيراً عن رحلتها عند الفجر.', null, '[{"en":"Her","ar":"لها"},{"en":"flight","ar":"رحلتها"},{"en":"was","ar":"أُعلن"},{"en":"finally","ar":"أخيراً"},{"en":"called","ar":"عنها"},{"en":"at","ar":"عند"},{"en":"dawn","ar":"الفجر"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s11', 'story-4', 10, 'They exchanged numbers before boarding', 'تبادلا أرقام الهاتف قبل الصعود إلى الطائرة.', null, '[{"en":"They","ar":"هما"},{"en":"exchanged","ar":"تبادلا"},{"en":"numbers","ar":"أرقام الهاتف"},{"en":"before","ar":"قبل"},{"en":"boarding","ar":"الصعود إلى الطائرة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-4-s12', 'story-4', 11, 'It turned out to be a night worth remembering', 'تبين أنها ليلة تستحق أن تُذكر.', null, '[{"en":"It","ar":"هي"},{"en":"turned","ar":"تبين"},{"en":"out","ar":"أنها"},{"en":"to","ar":"أن"},{"en":"be","ar":"تكون"},{"en":"a","ar":"واحدة"},{"en":"night","ar":"ليلة"},{"en":"worth","ar":"تستحق"},{"en":"remembering","ar":"أن تُذكر"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s1', 'story-5', 0, 'I found the photograph inside an old book', 'وجدت الصورة داخل كتاب قديم.', null, '[{"en":"I","ar":"أنا"},{"en":"found","ar":"وجدت"},{"en":"the","ar":"الـ"},{"en":"photograph","ar":"الصورة"},{"en":"inside","ar":"داخل"},{"en":"an","ar":"واحد"},{"en":"old","ar":"قديم"},{"en":"book","ar":"كتاب"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s2', 'story-5', 1, 'It showed my grandmother standing by the sea', 'أظهرت جدتي واقفة عند البحر.', null, '[{"en":"It","ar":"هي"},{"en":"showed","ar":"أظهرت"},{"en":"my","ar":"لي"},{"en":"grandmother","ar":"جدتي"},{"en":"standing","ar":"واقفة"},{"en":"by","ar":"عند"},{"en":"the","ar":"الـ"},{"en":"sea","ar":"البحر"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s3', 'story-5', 2, 'She looked impossibly young, barely older than me', 'بدت صغيرة السن بشكل يصعب تصديقه، بالكاد أكبر مني.', null, '[{"en":"She","ar":"هي"},{"en":"looked","ar":"بدت"},{"en":"impossibly","ar":"بشكل يصعب تصديقه"},{"en":"young,","ar":"صغيرة السن،"},{"en":"barely","ar":"بالكاد"},{"en":"older","ar":"أكبر"},{"en":"than","ar":"من"},{"en":"me","ar":"مني"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s4', 'story-5', 3, 'On the back, someone had written a date and a name', 'على الظهر، كتب أحدهم تاريخاً واسماً.', null, '[{"en":"On","ar":"على"},{"en":"the","ar":"الـ"},{"en":"back,","ar":"الظهر،"},{"en":"someone","ar":"أحدهم"},{"en":"had","ar":"قد"},{"en":"written","ar":"كتب"},{"en":"a","ar":"واحداً"},{"en":"date","ar":"تاريخاً"},{"en":"and","ar":"و"},{"en":"a","ar":"واحداً"},{"en":"name","ar":"اسماً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s5', 'story-5', 4, 'I had never heard that name mentioned at home', 'لم أسمع ذلك الاسم يُذكر في المنزل من قبل.', null, '[{"en":"I","ar":"أنا"},{"en":"had","ar":"لم"},{"en":"never","ar":"أبداً"},{"en":"heard","ar":"أسمع"},{"en":"that","ar":"ذلك"},{"en":"name","ar":"الاسم"},{"en":"mentioned","ar":"يُذكر"},{"en":"at","ar":"في"},{"en":"home","ar":"المنزل"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s6', 'story-5', 5, 'I brought the photo to my grandmother that evening', 'أحضرت الصورة إلى جدتي في تلك الأمسية.', null, '[{"en":"I","ar":"أنا"},{"en":"brought","ar":"أحضرت"},{"en":"the","ar":"الـ"},{"en":"photo","ar":"الصورة"},{"en":"to","ar":"إلى"},{"en":"my","ar":"لي"},{"en":"grandmother","ar":"جدتي"},{"en":"that","ar":"تلك"},{"en":"evening","ar":"الأمسية"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s7', 'story-5', 6, 'She stared at it for a long moment in silence', 'حدقت فيها للحظة طويلة بصمت.', null, '[{"en":"She","ar":"هي"},{"en":"stared","ar":"حدقت"},{"en":"at","ar":"في"},{"en":"it","ar":"ها"},{"en":"for","ar":"لـ"},{"en":"a","ar":"واحدة"},{"en":"long","ar":"طويلة"},{"en":"moment","ar":"لحظة"},{"en":"in","ar":"بـ"},{"en":"silence","ar":"صمت"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s8', 'story-5', 7, 'Then she told me about a summer I never knew existed', 'ثم أخبرتني عن صيف لم أكن أعلم بوجوده.', null, '[{"en":"Then","ar":"ثم"},{"en":"she","ar":"هي"},{"en":"told","ar":"أخبرتني"},{"en":"me","ar":"ني"},{"en":"about","ar":"عن"},{"en":"a","ar":"واحد"},{"en":"summer","ar":"صيف"},{"en":"I","ar":"أنا"},{"en":"never","ar":"لم"},{"en":"knew","ar":"أكن أعلم"},{"en":"existed","ar":"بوجوده"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s9', 'story-5', 8, 'It was a story full of choices she rarely spoke of', 'كانت قصة مليئة بخيارات نادراً ما تحدثت عنها.', null, '[{"en":"It","ar":"هي"},{"en":"was","ar":"كانت"},{"en":"a","ar":"واحدة"},{"en":"story","ar":"قصة"},{"en":"full","ar":"مليئة"},{"en":"of","ar":"بـ"},{"en":"choices","ar":"خيارات"},{"en":"she","ar":"هي"},{"en":"rarely","ar":"نادراً"},{"en":"spoke","ar":"تحدثت"},{"en":"of","ar":"عنها"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s10', 'story-5', 9, 'Some details she remembered with surprising clarity', 'بعض التفاصيل تذكرتها بوضوح مفاجئ.', null, '[{"en":"Some","ar":"بعض"},{"en":"details","ar":"التفاصيل"},{"en":"she","ar":"هي"},{"en":"remembered","ar":"تذكرتها"},{"en":"with","ar":"بـ"},{"en":"surprising","ar":"مفاجئ"},{"en":"clarity","ar":"وضوح"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s11', 'story-5', 10, 'Others, she admitted, had faded beyond recovery', 'أما البقية، فاعترفت أنها تلاشت إلى الأبد.', null, '[{"en":"Others,","ar":"البقية،"},{"en":"she","ar":"هي"},{"en":"admitted,","ar":"اعترفت،"},{"en":"had","ar":"قد"},{"en":"faded","ar":"تلاشت"},{"en":"beyond","ar":"إلى"},{"en":"recovery","ar":"الأبد"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-5-s12', 'story-5', 11, 'I left that evening realizing how little I truly knew her', 'غادرت تلك الأمسية مدركاً كم كنت أعرف القليل عنها فعلاً.', null, '[{"en":"I","ar":"أنا"},{"en":"left","ar":"غادرت"},{"en":"that","ar":"تلك"},{"en":"evening","ar":"الأمسية"},{"en":"realizing","ar":"مدركاً"},{"en":"how","ar":"كم"},{"en":"little","ar":"قليلاً"},{"en":"I","ar":"أنا"},{"en":"truly","ar":"فعلاً"},{"en":"knew","ar":"أعرف"},{"en":"her","ar":"عنها"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s1', 'story-6', 0, 'I''d been nervous about this date for an entire week', 'كنت متوتراً بشأن هذا الموعد طوال أسبوع كامل.', null, '[{"en":"I''d","ar":"كنت"},{"en":"been","ar":"قد"},{"en":"nervous","ar":"متوتراً"},{"en":"about","ar":"بشأن"},{"en":"this","ar":"هذا"},{"en":"date","ar":"الموعد"},{"en":"for","ar":"طوال"},{"en":"an","ar":"واحد"},{"en":"entire","ar":"كامل"},{"en":"week","ar":"أسبوع"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s2', 'story-6', 1, 'Naturally, everything that could go wrong did', 'وبطبيعة الحال، حدث كل ما يمكن أن يسوء.', null, '[{"en":"Naturally,","ar":"وبطبيعة الحال،"},{"en":"everything","ar":"كل شيء"},{"en":"that","ar":"الذي"},{"en":"could","ar":"كان يمكن"},{"en":"go","ar":"أن"},{"en":"wrong","ar":"يسوء"},{"en":"did","ar":"حدث"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s3', 'story-6', 2, 'I arrived at the wrong restaurant, twenty minutes late', 'وصلت إلى المطعم الخطأ، متأخراً عشرين دقيقة.', null, '[{"en":"I","ar":"أنا"},{"en":"arrived","ar":"وصلت"},{"en":"at","ar":"إلى"},{"en":"the","ar":"الـ"},{"en":"wrong","ar":"الخطأ"},{"en":"restaurant,","ar":"المطعم،"},{"en":"twenty","ar":"عشرين"},{"en":"minutes","ar":"دقيقة"},{"en":"late","ar":"متأخراً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s4', 'story-6', 3, 'My date was gracious enough not to mention it twice', 'كان شريكي في الموعد لطيفاً بما يكفي ليتجنب ذكر ذلك مرة أخرى.', null, '[{"en":"My","ar":"لي"},{"en":"date","ar":"شريكي"},{"en":"was","ar":"كان"},{"en":"gracious","ar":"لطيفاً"},{"en":"enough","ar":"بما يكفي"},{"en":"not","ar":"ليتجنب"},{"en":"to","ar":"أن"},{"en":"mention","ar":"يذكر"},{"en":"it","ar":"ذلك"},{"en":"twice","ar":"مرة أخرى"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s5', 'story-6', 4, 'Halfway through dinner, I knocked over an entire glass of wine', 'في منتصف العشاء، أسقطت كأس نبيذ كاملاً.', null, '[{"en":"Halfway","ar":"في"},{"en":"through","ar":"منتصف"},{"en":"dinner,","ar":"العشاء،"},{"en":"I","ar":"أنا"},{"en":"knocked","ar":"أسقطت"},{"en":"over","ar":"فوق"},{"en":"an","ar":"واحداً"},{"en":"entire","ar":"كاملاً"},{"en":"glass","ar":"كأس"},{"en":"of","ar":"من"},{"en":"wine","ar":"نبيذ"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s6', 'story-6', 5, 'It landed, with impressive precision, directly in his lap', 'سقط، بدقة مذهلة، مباشرة في حجره.', null, '[{"en":"It","ar":"هو"},{"en":"landed,","ar":"سقط،"},{"en":"with","ar":"بـ"},{"en":"impressive","ar":"مذهلة"},{"en":"precision,","ar":"دقة،"},{"en":"directly","ar":"مباشرة"},{"en":"in","ar":"في"},{"en":"his","ar":"له"},{"en":"lap","ar":"حجره"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s7', 'story-6', 6, 'He laughed it off, which somehow made things worse', 'تجاهل الأمر ضاحكاً، مما جعل الأمور أسوأ نوعاً ما.', null, '[{"en":"He","ar":"هو"},{"en":"laughed","ar":"ضحك"},{"en":"it","ar":"ه"},{"en":"off,","ar":"متجاهلاً،"},{"en":"which","ar":"مما"},{"en":"somehow","ar":"نوعاً ما"},{"en":"made","ar":"جعل"},{"en":"things","ar":"الأمور"},{"en":"worse","ar":"أسوأ"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s8', 'story-6', 7, 'I spent the rest of the evening apologizing profusely', 'أمضيت بقية الأمسية أعتذر بإفراط.', null, '[{"en":"I","ar":"أنا"},{"en":"spent","ar":"أمضيت"},{"en":"the","ar":"الـ"},{"en":"rest","ar":"بقية"},{"en":"of","ar":"من"},{"en":"the","ar":"الـ"},{"en":"evening","ar":"الأمسية"},{"en":"apologizing","ar":"أعتذر"},{"en":"profusely","ar":"بإفراط"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s9', 'story-6', 8, 'By dessert, we''d both given up on making a good impression', 'بحلول وقت الحلوى، كنا قد تخلينا عن محاولة ترك انطباع جيد.', null, '[{"en":"By","ar":"بحلول"},{"en":"dessert,","ar":"الحلوى،"},{"en":"we''d","ar":"كنا"},{"en":"both","ar":"كلانا"},{"en":"given","ar":"تخلينا"},{"en":"up","ar":"عن"},{"en":"on","ar":"محاولة"},{"en":"making","ar":"ترك"},{"en":"a","ar":"واحد"},{"en":"good","ar":"جيد"},{"en":"impression","ar":"انطباع"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s10', 'story-6', 9, 'Oddly enough, that''s when the conversation actually got interesting', 'والغريب أن الحديث أصبح مثيراً للاهتمام حينها فعلاً.', null, '[{"en":"Oddly","ar":"والغريب"},{"en":"enough,","ar":"أن،"},{"en":"that''s","ar":"هذا"},{"en":"when","ar":"عندما"},{"en":"the","ar":"الـ"},{"en":"conversation","ar":"الحديث"},{"en":"actually","ar":"فعلاً"},{"en":"got","ar":"أصبح"},{"en":"interesting","ar":"مثيراً للاهتمام"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s11', 'story-6', 10, 'We ended up talking for three hours past closing time', 'انتهى بنا الأمر بالحديث لثلاث ساعات بعد وقت الإغلاق.', null, '[{"en":"We","ar":"نحن"},{"en":"ended","ar":"انتهى"},{"en":"up","ar":"بنا"},{"en":"talking","ar":"بالحديث"},{"en":"for","ar":"لمدة"},{"en":"three","ar":"ثلاث"},{"en":"hours","ar":"ساعات"},{"en":"past","ar":"بعد"},{"en":"closing","ar":"الإغلاق"},{"en":"time","ar":"وقت"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('story-6-s12', 'story-6', 11, 'Disasters, it turns out, make surprisingly good icebreakers', 'تبين أن الكوارث تصنع وسيلة رائعة بشكل مفاجئ لكسر الجليد.', null, '[{"en":"Disasters,","ar":"الكوارث،"},{"en":"it","ar":"أن"},{"en":"turns","ar":"تبين"},{"en":"out,","ar":"ذلك،"},{"en":"make","ar":"تصنع"},{"en":"surprisingly","ar":"بشكل مفاجئ"},{"en":"good","ar":"رائعة"},{"en":"icebreakers","ar":"لكسر الجليد"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();

-- Cleanup: story-1 and story-2 previously had 24 sentences (order_index 0-23); remove the now-stale trailing twelve.
delete from sentences where lesson_id in ('story-1', 'story-2') and order_index >= 12;

commit;
