-- Stories content expansion: 12 new lessons (4 per tier), three genuine
-- 4-episode arcs with the same recurring characters/setting across each
-- arc — unlike the existing 68 stories (each an independent one-off with
-- a new cast every time). Applied to the live project via
-- scripts/insert-stories-series.ts; captured here for tracking.
begin;

insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free) values
  ('story-67', 'stories', '420c7cc5-d17c-4862-858e-73e5ddbbb07d', 69, 'The First Cup', 'الفنجان الأول', 'Sami opens his tiny coffee cart and waits nervously for his very first customer', 'يفتح سامي عربة قهوته الصغيرة وينتظر بقلق أول زبون له', true),
  ('story-68', 'stories', '420c7cc5-d17c-4862-858e-73e5ddbbb07d', 70, 'The Regular', 'الزبون الدائم', 'The old man from the first morning becomes Sami''s most loyal customer', 'يصبح الرجل العجوز من الصباح الأول أكثر زبائن سامي وفاءً', false),
  ('story-69', 'stories', '420c7cc5-d17c-4862-858e-73e5ddbbb07d', 71, 'The Rainy Morning', 'الصباح الماطر', 'A storm keeps every customer away except the one Sami least expected', 'تُبعد العاصفة كل الزبائن باستثناء من لم يتوقعه سامي', false),
  ('story-70', 'stories', '420c7cc5-d17c-4862-858e-73e5ddbbb07d', 72, 'The Line Around the Corner', 'الطابور حول الزاوية', 'Months later Sami''s little cart has become the whole street''s favorite stop', 'بعد أشهر، أصبحت عربة سامي الصغيرة المحطة المفضلة للشارع بأكمله', false),
  ('story-71', 'stories', 'ae3a34f5-14bf-427f-b9b3-78ac7702842e', 73, 'The Interview', 'المقابلة', 'Dana walks into a small bookstore for an interview she''s determined not to blow', 'تدخل دانا إلى مكتبة صغيرة لمقابلة عمل عازمة على ألا تفسدها', true),
  ('story-72', 'stories', 'ae3a34f5-14bf-427f-b9b3-78ac7702842e', 74, 'The Difficult Customer', 'الزبون الصعب', 'A furious customer tests Dana''s very first week and teaches her something unexpected', 'يختبر زبون غاضب أسبوع دانا الأول ويعلّمها شيئاً غير متوقع', false),
  ('story-73', 'stories', 'ae3a34f5-14bf-427f-b9b3-78ac7702842e', 75, 'The Book Club Idea', 'فكرة نادي الكتاب', 'Dana pitches an idea to save the quiet bookstore and Mr Farouk isn''t easily convinced', 'تطرح دانا فكرة لإنقاذ المكتبة الهادئة والسيد فاروق ليس سهل الإقناع', false),
  ('story-74', 'stories', 'ae3a34f5-14bf-427f-b9b3-78ac7702842e', 76, 'Opening Night', 'ليلة الافتتاح', 'The first book club meeting arrives and Dana isn''t sure anyone will actually show up', 'تصل أول جلسة لنادي الكتاب ودانا غير متأكدة أن أحداً سيحضر فعلاً', false),
  ('story-75', 'stories', 'e6bf826a-a0e4-4da4-81d4-5cca26c51463', 77, 'The Voicemail', 'الرسالة الصوتية', 'An unfamiliar number leaves a voicemail I almost don''t listen to', 'رقم غير مألوف يترك رسالة صوتية كدت لا أستمع إليها', true),
  ('story-76', 'stories', 'e6bf826a-a0e4-4da4-81d4-5cca26c51463', 78, 'The Call', 'الاتصال', 'I finally call the number back and neither of us knows how to start', 'أتصل أخيراً بالرقم ولا أحد منا يعرف كيف يبدأ', false),
  ('story-77', 'stories', 'e6bf826a-a0e4-4da4-81d4-5cca26c51463', 79, 'The Visit', 'الزيارة', 'We finally sit across from each other and the silence says almost everything', 'نجلس أخيراً وجهاً لوجه والصمت يقول كل شيء تقريباً', false),
  ('story-78', 'stories', 'e6bf826a-a0e4-4da4-81d4-5cca26c51463', 80, 'What We Didn''t Say', 'ما لم نقله', 'Months later I realize the relationship didn''t need every question answered to heal', 'بعد أشهر، أدرك أن العلاقة لم تكن بحاجة لإجابة كل سؤال كي تُشفى', false) on conflict (id) do nothing;

insert into sentences (id, lesson_id, order_index, en, ar) values
  ('story-67-s1', 'story-67', 1, 'Sami woke up before the sun on his very first day', 'استيقظ سامي قبل شروق الشمس في أول يوم له.'),
  ('story-67-s2', 'story-67', 2, 'He had saved money for months to buy his little coffee cart', 'كان قد ادخر المال لأشهر ليشتري عربة القهوة الصغيرة.'),
  ('story-67-s3', 'story-67', 3, 'He pushed it to the corner near the old park', 'دفعها إلى الزاوية القريبة من الحديقة القديمة.'),
  ('story-67-s4', 'story-67', 4, 'His hands were shaking as he made the first cup', 'كانت يداه ترتجفان وهو يعد الفنجان الأول.'),
  ('story-67-s5', 'story-67', 5, 'An hour passed and no one stopped by his cart', 'مرت ساعة ولم يتوقف أحد عند عربته.'),
  ('story-67-s6', 'story-67', 6, 'He started to think this was a big mistake', 'بدأ يعتقد أن هذا كان خطأً كبيراً.'),
  ('story-67-s7', 'story-67', 7, 'Then an old man in a gray coat walked up slowly', 'ثم اقترب رجل عجوز يرتدي معطفاً رمادياً ببطء.'),
  ('story-67-s8', 'story-67', 8, 'One coffee please the old man said with a small smile', 'قال الرجل العجوز بابتسامة صغيرة: "قهوة واحدة من فضلك."'),
  ('story-67-s9', 'story-67', 9, 'Sami''s hands stopped shaking as he poured the first cup', 'توقفت يدا سامي عن الارتجاف وهو يسكب الفنجان الأول.'),
  ('story-67-s10', 'story-67', 10, 'The old man took one sip and nodded slowly', 'أخذ الرجل العجوز رشفة واحدة وأومأ برأسه ببطء.'),
  ('story-67-s11', 'story-67', 11, 'This is the best coffee on this street he said', 'قال: "هذه أفضل قهوة في هذا الشارع."'),
  ('story-68-s1', 'story-68', 1, 'The old man came back again the very next morning', 'عاد الرجل العجوز مرة أخرى في صباح اليوم التالي.'),
  ('story-68-s2', 'story-68', 2, 'His name was Mr Adel and he lived nearby', 'كان اسمه السيد عادل وكان يسكن قريباً.'),
  ('story-68-s3', 'story-68', 3, 'He always ordered the same coffee at the same time', 'كان دائماً يطلب نفس القهوة في نفس الوقت.'),
  ('story-68-s4', 'story-68', 4, 'Sami began to prepare it before Mr Adel even arrived', 'بدأ سامي يحضّرها قبل أن يصل السيد عادل حتى.'),
  ('story-68-s5', 'story-68', 5, 'Slowly a few more customers started to notice the little cart', 'بدأ بضعة زبائن آخرين يلاحظون العربة الصغيرة تدريجياً.'),
  ('story-68-s6', 'story-68', 6, 'Mr Adel always sat on the same bench nearby', 'كان السيد عادل يجلس دائماً على نفس المقعد القريب.'),
  ('story-68-s7', 'story-68', 7, 'He watched the street and talked with Sami between customers', 'كان يراقب الشارع ويتحدث مع سامي بين الزبائن.'),
  ('story-68-s8', 'story-68', 8, 'He told Sami stories about the neighborhood many years ago', 'أخبر سامي بقصص عن الحي منذ سنوات عديدة.'),
  ('story-68-s9', 'story-68', 9, 'Sami started looking forward to their morning conversation', 'بدأ سامي يتشوق لحديثهما الصباحي.'),
  ('story-68-s10', 'story-68', 10, 'You remind me of my son Mr Adel said one day', 'قال السيد عادل ذات يوم: "أنت تذكرني بابني."'),
  ('story-68-s11', 'story-68', 11, 'Sami didn''t know what to say so he just smiled', 'لم يعرف سامي ماذا يقول فابتسم فقط.'),
  ('story-69-s1', 'story-69', 1, 'Dark clouds filled the sky on a cold Tuesday morning', 'ملأت الغيوم الداكنة السماء في صباح ثلاثاء بارد.'),
  ('story-69-s2', 'story-69', 2, 'Sami pushed his cart to the corner anyway', 'دفع سامي عربته إلى الزاوية رغم ذلك.'),
  ('story-69-s3', 'story-69', 3, 'The rain started before he could even open the umbrella', 'بدأ المطر قبل أن يتمكن حتى من فتح المظلة.'),
  ('story-69-s4', 'story-69', 4, 'The street stayed completely empty for almost two hours', 'بقي الشارع فارغاً تماماً لما يقارب الساعتين.'),
  ('story-69-s5', 'story-69', 5, 'Sami sat down and wondered if he should just go home', 'جلس سامي وتساءل إن كان عليه العودة إلى المنزل فحسب.'),
  ('story-69-s6', 'story-69', 6, 'Then he saw a familiar gray coat coming through the rain', 'ثم رأى معطفاً رمادياً مألوفاً قادماً عبر المطر.'),
  ('story-69-s7', 'story-69', 7, 'Mr Adel walked up holding one large umbrella', 'اقترب السيد عادل حاملاً مظلة كبيرة واحدة.'),
  ('story-69-s8', 'story-69', 8, 'I figured you''d still be here he said cheerfully', 'قال بمرح: "توقعت أنك ما زلت هنا."'),
  ('story-69-s9', 'story-69', 9, 'He held the umbrella over the cart while Sami made the coffee', 'أمسك المظلة فوق العربة بينما كان سامي يعد القهوة.'),
  ('story-69-s10', 'story-69', 10, 'They laughed together as the rain grew even louder', 'ضحكا معاً بينما ازداد صوت المطر.'),
  ('story-69-s11', 'story-69', 11, 'Some days Mr Adel said the coffee matters less than the company', 'قال السيد عادل: "في بعض الأيام، القهوة أقل أهمية من الرفقة."'),
  ('story-70-s1', 'story-70', 1, 'Six months later the cart had a line every single morning', 'بعد ستة أشهر، صار للعربة طابور كل صباح.'),
  ('story-70-s2', 'story-70', 2, 'Sami had to wake up even earlier to prepare everything', 'كان على سامي أن يستيقظ أبكر لتحضير كل شيء.'),
  ('story-70-s3', 'story-70', 3, 'He hired a young helper to keep up with the orders', 'وظّف مساعداً شاباً لمواكبة الطلبات.'),
  ('story-70-s4', 'story-70', 4, 'Mr Adel still came every morning at the very same time', 'ما زال السيد عادل يأتي كل صباح في نفس الوقت بالضبط.'),
  ('story-70-s5', 'story-70', 5, 'He never had to wait in the long line anymore', 'لم يعد عليه الانتظار في الطابور الطويل بعد الآن.'),
  ('story-70-s6', 'story-70', 6, 'Sami always had his coffee ready before he reached the front', 'كان سامي دائماً يجهّز قهوته قبل أن يصل إلى المقدمة.'),
  ('story-70-s7', 'story-70', 7, 'A local newspaper even wrote a short story about the cart', 'كتبت صحيفة محلية حتى قصة قصيرة عن العربة.'),
  ('story-70-s8', 'story-70', 8, 'Sami kept the little clipping taped inside the cart', 'احتفظ سامي بالقصاصة الصغيرة ملصقة داخل العربة.'),
  ('story-70-s9', 'story-70', 9, 'None of this would have happened without that first rainy morning he said', 'قال: "لم يكن أي من هذا ليحدث لولا ذلك الصباح الماطر الأول."'),
  ('story-70-s10', 'story-70', 10, 'Mr Adel just smiled and raised his cup', 'ابتسم السيد عادل فقط ورفع فنجانه.'),
  ('story-70-s11', 'story-70', 11, 'To the best coffee on this street he said again', 'قال مجدداً: "لأفضل قهوة في هذا الشارع."'),
  ('story-71-s1', 'story-71', 1, 'Dana had read about the bookstore online the night before', 'قرأت دانا عن المكتبة على الإنترنت في الليلة السابقة.'),
  ('story-71-s2', 'story-71', 2, 'It was small and slightly crowded with towers of books', 'كانت صغيرة ومزدحمة قليلاً بأبراج من الكتب.'),
  ('story-71-s3', 'story-71', 3, 'The owner Mr Farouk barely looked up when she walked in', 'بالكاد رفع السيد فاروق، صاحب المكتبة، نظره حين دخلت.'),
  ('story-71-s4', 'story-71', 4, 'He asked her what she was currently reading', 'سألها عمّا تقرأه حالياً.'),
  ('story-71-s5', 'story-71', 5, 'Dana admitted she hadn''t finished a book in almost a year', 'اعترفت دانا بأنها لم تنهِ كتاباً منذ عام تقريباً.'),
  ('story-71-s6', 'story-71', 6, 'She expected that honesty to end the interview immediately', 'توقعت أن ينهي هذا الصدق المقابلة على الفور.'),
  ('story-71-s7', 'story-71', 7, 'Instead Mr Farouk finally looked up and smiled slightly', 'بدلاً من ذلك، رفع السيد فاروق نظره أخيراً وابتسم قليلاً.'),
  ('story-71-s8', 'story-71', 8, 'At least you''re not pretending he said', 'قال: "على الأقل أنتِ لا تتظاهرين."'),
  ('story-71-s9', 'story-71', 9, 'He handed her a worn paperback and asked her to read the first page', 'أعطاها كتاباً ورقياً بالياً وطلب منها قراءة الصفحة الأولى.'),
  ('story-71-s10', 'story-71', 10, 'She read it slowly and something in her actually relaxed', 'قرأتها ببطء، وشعرت بشيء ما بداخلها يرتاح فعلاً.'),
  ('story-71-s11', 'story-71', 11, 'Can you start on Monday Mr Farouk asked', 'سأل السيد فاروق: "هل يمكنك البدء يوم الاثنين؟"'),
  ('story-72-s1', 'story-72', 1, 'By Wednesday Dana finally felt comfortable behind the counter', 'بحلول الأربعاء، شعرت دانا أخيراً بالراحة خلف الطاولة.'),
  ('story-72-s2', 'story-72', 2, 'Then a man stormed in demanding a refund for a torn book', 'ثم اقتحم رجل المكان مطالباً باسترداد ثمن كتاب ممزق.'),
  ('story-72-s3', 'story-72', 3, 'Dana explained calmly that the store couldn''t refund used books', 'أوضحت دانا بهدوء أن المكتبة لا تسترد ثمن الكتب المستعملة.'),
  ('story-72-s4', 'story-72', 4, 'The man raised his voice and several customers turned to look', 'رفع الرجل صوته والتفت عدة زبائن للنظر.'),
  ('story-72-s5', 'story-72', 5, 'Dana felt her face turning red but kept her voice steady', 'شعرت دانا بوجهها يحمرّ لكنها حافظت على ثبات صوتها.'),
  ('story-72-s6', 'story-72', 6, 'She offered to exchange the book for a new copy instead', 'عرضت استبدال الكتاب بنسخة جديدة بدلاً من ذلك.'),
  ('story-72-s7', 'story-72', 7, 'The man paused clearly not expecting that response', 'توقف الرجل، ومن الواضح أنه لم يتوقع ذلك الرد.'),
  ('story-72-s8', 'story-72', 8, 'He took the new copy and left without another word', 'أخذ النسخة الجديدة وغادر دون كلمة أخرى.'),
  ('story-72-s9', 'story-72', 9, 'Mr Farouk had watched the entire exchange from the back shelf', 'كان السيد فاروق قد راقب الموقف بأكمله من الرف الخلفي.'),
  ('story-72-s10', 'story-72', 10, 'You didn''t apologize for something that wasn''t your fault he noted', 'لاحظ قائلاً: "لم تعتذري عن شيء ليس خطأك."'),
  ('story-72-s11', 'story-72', 11, 'That''s exactly the kind of thing I hired you for he added', 'أضاف: "هذا بالضبط نوع الأشياء التي وظفتك من أجلها."'),
  ('story-73-s1', 'story-73', 1, 'Sales had been slow for the past several weeks', 'كانت المبيعات بطيئة خلال الأسابيع الماضية.'),
  ('story-73-s2', 'story-73', 2, 'Dana noticed the same regular customers browsing without buying much', 'لاحظت دانا نفس الزبائن الدائمين يتصفحون دون شراء الكثير.'),
  ('story-73-s3', 'story-73', 3, 'She suggested starting a small evening book club', 'اقترحت بدء نادي كتاب مسائي صغير.'),
  ('story-73-s4', 'story-73', 4, 'Mr Farouk raised an eyebrow and said people don''t read anymore', 'رفع السيد فاروق حاجباً وقال إن الناس لم يعودوا يقرأون.'),
  ('story-73-s5', 'story-73', 5, 'Dana argued that people still wanted to talk about books together', 'جادلت دانا بأن الناس ما زالوا يريدون التحدث عن الكتب معاً.'),
  ('story-73-s6', 'story-73', 6, 'He finally agreed to let her try it just once', 'وافق أخيراً على أن تجربها لمرة واحدة فقط.'),
  ('story-73-s7', 'story-73', 7, 'Dana spent the whole week designing a small flyer', 'قضت دانا الأسبوع كله في تصميم منشور صغير.'),
  ('story-73-s8', 'story-73', 8, 'She picked a short novel that she genuinely loved herself', 'اختارت رواية قصيرة أحبتها هي بصدق.'),
  ('story-73-s9', 'story-73', 9, 'Only three people signed up by Friday afternoon', 'سجّل ثلاثة أشخاص فقط بحلول عصر الجمعة.'),
  ('story-73-s10', 'story-73', 10, 'Mr Farouk said that was three more than he expected', 'قال السيد فاروق إن هذا أكثر بثلاثة مما توقع.'),
  ('story-73-s11', 'story-73', 11, 'Dana decided that Wednesday night she would find out for sure', 'قررت دانا أنها ستكتشف الحقيقة مساء الأربعاء.'),
  ('story-74-s1', 'story-74', 1, 'Dana arranged eight chairs in a small circle near the window', 'رتبت دانا ثمانية كراسٍ في دائرة صغيرة قرب النافذة.'),
  ('story-74-s2', 'story-74', 2, 'Only three chairs were needed but she wanted to feel hopeful', 'كانت هناك حاجة لثلاثة كراسٍ فقط لكنها أرادت أن تشعر بالأمل.'),
  ('story-74-s3', 'story-74', 3, 'At six o''clock exactly the three members walked in together', 'في تمام الساعة السادسة، دخل الأعضاء الثلاثة معاً.'),
  ('story-74-s4', 'story-74', 4, 'Behind them two more people Dana didn''t recognize walked in too', 'خلفهم، دخل شخصان آخران لم تعرفهما دانا أيضاً.'),
  ('story-74-s5', 'story-74', 5, 'They had seen the flyer taped to the coffee shop window', 'كانا قد رأيا المنشور الملصق على نافذة المقهى.'),
  ('story-74-s6', 'story-74', 6, 'By six fifteen every single chair in the circle was filled', 'بحلول السادسة وربعاً، امتلأت كل الكراسي في الدائرة.'),
  ('story-74-s7', 'story-74', 7, 'The conversation started slowly then grew louder and more excited', 'بدأ الحديث ببطء ثم ازداد صوتاً وحماساً.'),
  ('story-74-s8', 'story-74', 8, 'Mr Farouk stood quietly by the register just watching and listening', 'وقف السيد فاروق بهدوء قرب الصندوق يراقب ويستمع فقط.'),
  ('story-74-s9', 'story-74', 9, 'When the last member left he was still smiling', 'عندما غادر آخر عضو، كان لا يزال يبتسم.'),
  ('story-74-s10', 'story-74', 10, 'Order sixteen more copies for next month he told Dana', 'قال لدانا: "اطلبي ستة عشر نسخة إضافية للشهر القادم."'),
  ('story-74-s11', 'story-74', 11, 'Dana smiled and started writing down the list immediately', 'ابتسمت دانا وبدأت بكتابة القائمة فوراً.'),
  ('story-75-s1', 'story-75', 1, 'The voicemail notification sat there for almost two full days', 'بقي إشعار الرسالة الصوتية معلقاً لما يقارب يومين كاملين.'),
  ('story-75-s2', 'story-75', 2, 'I recognized the voice before he''d even said his name', 'تعرفت على الصوت قبل أن يذكر اسمه حتى.'),
  ('story-75-s3', 'story-75', 3, 'We hadn''t spoken in nearly four years by that point', 'لم نتحدث منذ ما يقارب أربع سنوات حتى تلك اللحظة.'),
  ('story-75-s4', 'story-75', 4, 'His voice sounded older tired somehow smaller than I remembered', 'بدا صوته أكبر سناً، متعباً، وبطريقة ما أصغر مما أتذكر.'),
  ('story-75-s5', 'story-75', 5, 'He said our mother had asked about me again recently', 'قال إن والدتنا سألت عني مجدداً مؤخراً.'),
  ('story-75-s6', 'story-75', 6, 'He didn''t apologize and honestly I hadn''t expected him to', 'لم يعتذر، وبصراحة لم أكن أتوقع منه ذلك.'),
  ('story-75-s7', 'story-75', 7, 'He simply left his number and said call whenever', 'ترك رقمه فقط وقال اتصل في أي وقت تشاء.'),
  ('story-75-s8', 'story-75', 8, 'I played the message three more times after that', 'شغّلت الرسالة ثلاث مرات إضافية بعد ذلك.'),
  ('story-75-s9', 'story-75', 9, 'Every old argument I remembered started replaying in my head', 'بدأت كل الخلافات القديمة التي أتذكرها تعيد نفسها في ذهني.'),
  ('story-75-s10', 'story-75', 10, 'I still couldn''t decide if I was angry or just relieved', 'ما زلت غير قادر على تحديد إن كنت غاضباً أم مرتاحاً فقط.'),
  ('story-75-s11', 'story-75', 11, 'I saved his number but didn''t call back that night', 'حفظت رقمه لكنني لم أتصل به تلك الليلة.'),
  ('story-76-s1', 'story-76', 1, 'I waited another full week before I actually dialed the number', 'انتظرت أسبوعاً كاملاً آخر قبل أن أتصل بالرقم فعلاً.'),
  ('story-76-s2', 'story-76', 2, 'He picked up on the second ring which surprised me', 'رد بعد الرنة الثانية، وهو ما فاجأني.'),
  ('story-76-s3', 'story-76', 3, 'Neither of us said anything for what felt like a long moment', 'لم يقل أي منا شيئاً لما بدا لحظة طويلة.'),
  ('story-76-s4', 'story-76', 4, 'He finally asked how work was going these days', 'سأل أخيراً كيف يسير العمل هذه الأيام.'),
  ('story-76-s5', 'story-76', 5, 'It was such a small question for four years of silence', 'كان سؤالاً صغيراً جداً مقابل أربع سنوات من الصمت.'),
  ('story-76-s6', 'story-76', 6, 'I answered anyway because the silence felt worse than talking', 'أجبت رغم ذلك لأن الصمت بدا أسوأ من الحديث.'),
  ('story-76-s7', 'story-76', 7, 'Slowly the conversation moved to safer smaller topics', 'انتقل الحديث تدريجياً إلى مواضيع أصغر وأكثر أماناً.'),
  ('story-76-s8', 'story-76', 8, 'Neither of us mentioned the reason we''d stopped speaking at all', 'لم يذكر أي منا سبب توقفنا عن الحديث أصلاً.'),
  ('story-76-s9', 'story-76', 9, 'Near the end he asked if I wanted to meet in person', 'قرب النهاية، سألني إن كنت أرغب باللقاء شخصياً.'),
  ('story-76-s10', 'story-76', 10, 'I said maybe which was the most honest answer I had', 'قلت ربما، وكانت أصدق إجابة أملكها.'),
  ('story-76-s11', 'story-76', 11, 'We hung up without solving anything and somehow that felt fine', 'أنهينا الاتصال دون حل أي شيء، وبطريقة ما شعرت أن هذا مقبول.'),
  ('story-77-s1', 'story-77', 1, 'We agreed to meet at a quiet cafe neither of us had chosen before', 'اتفقنا على اللقاء في مقهى هادئ لم يختره أي منا من قبل.'),
  ('story-77-s2', 'story-77', 2, 'I arrived early and immediately regretted arriving early', 'وصلت مبكراً وندمت فوراً على وصولي مبكراً.'),
  ('story-77-s3', 'story-77', 3, 'When he walked in he looked smaller than his voice had suggested', 'عندما دخل، بدا أصغر مما أوحى به صوته.'),
  ('story-77-s4', 'story-77', 4, 'We shook hands awkwardly then sat down across from each other', 'تصافحنا بحرج ثم جلسنا وجهاً لوجه.'),
  ('story-77-s5', 'story-77', 5, 'For a while we talked about nothing that actually mattered', 'لفترة، تحدثنا عن أشياء لا تهم فعلاً.'),
  ('story-77-s6', 'story-77', 6, 'Then he mentioned our father''s old house almost by accident', 'ثم ذكر منزل والدنا القديم كأنه بالصدفة.'),
  ('story-77-s7', 'story-77', 7, 'Something in his voice cracked slightly on that one sentence', 'انكسر شيء ما في صوته قليلاً عند تلك الجملة.'),
  ('story-77-s8', 'story-77', 8, 'I realized he had been carrying this as long as I had', 'أدركت أنه كان يحمل هذا لمدة طويلة مثلي تماماً.'),
  ('story-77-s9', 'story-77', 9, 'Neither of us fully explained the years we had lost', 'لم يشرح أي منا بالكامل السنوات التي خسرناها.'),
  ('story-77-s10', 'story-77', 10, 'We didn''t need to really we both already understood', 'لم نكن بحاجة لذلك فعلاً، كلانا فهم بالفعل.'),
  ('story-77-s11', 'story-77', 11, 'Before leaving he hugged me and it lasted longer than expected', 'قبل أن يغادر، عانقني، ودامت العناقة أطول مما توقعت.'),
  ('story-78-s1', 'story-78', 1, 'Months have passed since that first awkward cup of coffee', 'مرت أشهر منذ ذلك الفنجان الأول المحرج من القهوة.'),
  ('story-78-s2', 'story-78', 2, 'We talk almost every week now usually about small things', 'نتحدث تقريباً كل أسبوع الآن، عادة عن أمور صغيرة.'),
  ('story-78-s3', 'story-78', 3, 'We still haven''t discussed the exact reason we stopped speaking', 'ما زلنا لم نناقش السبب الدقيق لتوقفنا عن الحديث.'),
  ('story-78-s4', 'story-78', 4, 'For a long time I thought that conversation was necessary', 'لفترة طويلة، ظننت أن ذلك الحديث كان ضرورياً.'),
  ('story-78-s5', 'story-78', 5, 'Now I''m genuinely not sure it ever needs to happen', 'الآن، لست متأكداً حقاً أنه بحاجة للحدوث أبداً.'),
  ('story-78-s6', 'story-78', 6, 'Some wounds it turns out don''t require a full explanation', 'يبدو أن بعض الجروح لا تتطلب تفسيراً كاملاً.'),
  ('story-78-s7', 'story-78', 7, 'They only require someone willing to show up again', 'إنها تتطلب فقط شخصاً مستعداً للحضور مجدداً.'),
  ('story-78-s8', 'story-78', 8, 'My brother calls more often than I ever expected him to', 'يتصل أخي أكثر بكثير مما توقعت منه يوماً.'),
  ('story-78-s9', 'story-78', 9, 'Last week he asked if I wanted to visit our mother together', 'الأسبوع الماضي سألني إن كنت أرغب بزيارة والدتنا معاً.'),
  ('story-78-s10', 'story-78', 10, 'I said yes without thinking twice about it at all', 'قلت نعم دون التفكير مرتين في الأمر إطلاقاً.'),
  ('story-78-s11', 'story-78', 11, 'Some doors it turns out were never fully closed at all', 'يبدو أن بعض الأبواب لم تُغلق بالكامل أبداً.') on conflict (id) do nothing;

commit;
