-- Word Lists content seed (9 groups, 180 words) — applied directly to
-- production out-of-band (see the repo root's former apply-word-lists.sql)
-- alongside the already-tracked 20250119000000_word_lists.sql schema
-- migration, but never itself captured as a real migration until now.
-- `on conflict (id) do nothing` makes this safe to run again without
-- clobbering any admin edits made to this content since.
begin;

insert into word_groups (id, level, order_index, title, title_ar, description, description_ar, is_free, status) values
  ('family', 1, 1, 'Family', 'العائلة', 'The people you call family, in words you''ll actually use.', 'الأشخاص الذين تسميهم عائلة، بكلمات ستستخدمها فعلاً.', true, 'published'),
  ('colors', 1, 2, 'Colors', 'الألوان', 'Everyday colors, the way people actually describe things.', 'ألوان يومية، بالطريقة التي يصف بها الناس الأشياء فعلاً.', false, 'published'),
  ('animals', 1, 3, 'Animals', 'الحيوانات', 'The animals that actually come up in everyday conversation.', 'الحيوانات التي تُذكر فعلاً في الأحاديث اليومية.', false, 'published'),
  ('friendship', 2, 4, 'Friendship', 'الصداقة', 'The language of real friendships — the good parts and the hard ones.', 'لغة الصداقات الحقيقية — الجوانب الجميلة والصعبة على حد سواء.', false, 'published'),
  ('travel', 2, 5, 'Travel', 'السفر', 'Real trip vocabulary, not just airport signs.', 'مفردات سفر حقيقية، وليست فقط لافتات المطار.', false, 'published'),
  ('health', 2, 6, 'Health', 'الصحة', 'How people actually talk about feeling sick or getting better.', 'كيف يتحدث الناس فعلاً عن المرض أو التعافي.', false, 'published'),
  ('politics', 3, 7, 'Politics', 'السياسة', 'The vocabulary of real political conversation, not a textbook glossary.', 'مفردات الحديث السياسي الحقيقي، وليست قائمة مصطلحات من كتاب مدرسي.', false, 'published'),
  ('finance', 3, 8, 'Finance', 'المال والاقتصاد', 'Money vocabulary that shows up in the news, not just a classroom.', 'مفردات مالية تظهر في الأخبار، وليست فقط في الصف الدراسي.', false, 'published'),
  ('technology', 3, 9, 'Technology', 'التكنولوجيا', 'The words that come up when people actually talk about tech, not a spec sheet.', 'الكلمات التي يستخدمها الناس فعلاً عند الحديث عن التقنية.', false, 'published') on conflict (id) do nothing;

insert into vocabulary_words (id, group_id, order_index, target_word, sentence, hint_ar) values
  ('family-aunt', 'family', 1, 'aunt', 'My ___ gives me cookies when I visit her.', 'العمة أو الخالة: أخت والدك أو والدتك.'),
  ('family-uncle', 'family', 2, 'uncle', 'Every summer, my ___ teaches us how to fish.', 'العم أو الخال: أخو والدك أو والدتك.'),
  ('family-cousin', 'family', 3, 'cousin', 'My ___ and I used to build Lego houses together.', 'ابن أو ابنة العم/العمة/الخال/الخالة.'),
  ('family-nephew', 'family', 4, 'nephew', 'There''s a five-year-old dinosaur expert in the family — my ___.', 'ابن الأخ أو الأخت.'),
  ('family-niece', 'family', 5, 'niece', 'No one in this house can beat my ___ at video games.', 'ابنة الأخ أو الأخت.'),
  ('family-grandmother', 'family', 6, 'grandmother', 'Even now, my ___ remembers every word of that old song.', 'الجدة: والدة والدك أو والدتك.'),
  ('family-grandfather', 'family', 7, 'grandfather', 'Ask my ___ about fishing and you''ll be there for an hour.', 'الجد: والد والدك أو والدتك.'),
  ('family-parents', 'family', 8, 'parents', 'It was at university that my ___ first met.', 'الوالدان: الأب والأم معاً.'),
  ('family-sibling', 'family', 9, 'sibling', 'I''m the only ___ who still lives in our hometown.', 'الأخ أو الأخت، بشكل عام دون تحديد الجنس.'),
  ('family-husband', 'family', 10, 'husband', 'Her ___ cooks dinner every Friday night.', 'الزوج.'),
  ('family-wife', 'family', 11, 'wife', 'His ___ works as a nurse downtown.', 'الزوجة.'),
  ('family-son', 'family', 12, 'son', 'Their ___ just started his first job.', 'الابن.'),
  ('family-daughter', 'family', 13, 'daughter', 'Their ___ wants to be a doctor someday.', 'الابنة.'),
  ('family-relative', 'family', 14, 'relative', 'A distant ___ sent us a wedding invitation.', 'قريب أو فرد من العائلة، بشكل عام.'),
  ('family-twin', 'family', 15, 'twin', 'People still mix her up with her ___ sister.', 'التوأم: أخ أو أخت وُلد في نفس الوقت.'),
  ('family-stepfather', 'family', 16, 'stepfather', 'Her ___ walked her down the aisle at the wedding.', 'زوج الأم، وليس الأب البيولوجي.'),
  ('family-stepmother', 'family', 17, 'stepmother', 'His ___ treats him just like her own son.', 'زوجة الأب، وليست الأم البيولوجية.'),
  ('family-in-laws', 'family', 18, 'in-laws', 'We''re spending the holiday with my ___ this year.', 'أهل الزوج أو الزوجة.'),
  ('family-grandson', 'family', 19, 'grandson', 'Her ___ calls her every Sunday without fail.', 'حفيد الجد أو الجدة (ذكر).'),
  ('family-granddaughter', 'family', 20, 'granddaughter', 'His ___ drew this picture just for him.', 'حفيدة الجد أو الجدة (أنثى).'),
  ('colors-red', 'colors', 1, 'red', 'She painted her front door bright ___.', 'لون أحمر.'),
  ('colors-blue', 'colors', 2, 'blue', 'The sky turned a deep ___ just before sunset.', 'لون أزرق.'),
  ('colors-green', 'colors', 3, 'green', 'He always wears a ___ jacket to work.', 'لون أخضر.'),
  ('colors-yellow', 'colors', 4, 'yellow', 'The taxi outside was a bright ___.', 'لون أصفر.'),
  ('colors-orange', 'colors', 5, 'orange', 'The leaves turn ___ every October here.', 'لون برتقالي.'),
  ('colors-purple', 'colors', 6, 'purple', 'My little sister loves anything ___.', 'لون بنفسجي.'),
  ('colors-pink', 'colors', 7, 'pink', 'The bakery box was tied with a ___ ribbon.', 'لون وردي.'),
  ('colors-brown', 'colors', 8, 'brown', 'He adopted a small ___ puppy last week.', 'لون بني.'),
  ('colors-black', 'colors', 9, 'black', 'She wore a plain ___ dress to the interview.', 'لون أسود.'),
  ('colors-white', 'colors', 10, 'white', 'The walls in his apartment are all ___.', 'لون أبيض.'),
  ('colors-gray', 'colors', 11, 'gray', 'The clouds looked ___ all morning before the rain.', 'لون رمادي.'),
  ('colors-gold', 'colors', 12, 'gold', 'She never takes off her ___ earrings.', 'لون ذهبي.'),
  ('colors-silver', 'colors', 13, 'silver', 'He drives an old ___ pickup truck.', 'لون فضي.'),
  ('colors-beige', 'colors', 14, 'beige', 'The living room walls are a soft ___.', 'لون بيج، بين الأبيض والبني الفاتح.'),
  ('colors-maroon', 'colors', 15, 'maroon', 'The school uniform is ___ and gray.', 'لون كستنائي، أحمر غامق مائل للبني.'),
  ('colors-turquoise', 'colors', 16, 'turquoise', 'The water near the coast looked ___ in the sun.', 'لون فيروزي، بين الأزرق والأخضر.'),
  ('colors-lime', 'colors', 17, 'lime', 'His running shoes are a loud ___ green.', 'لون أخضر ليموني فاتح.'),
  ('colors-violet', 'colors', 18, 'violet', 'The sunset faded from orange to ___.', 'لون بنفسجي مائل للأزرق.'),
  ('colors-cream', 'colors', 19, 'cream', 'We repainted the kitchen a warm ___ color.', 'لون كريمي، أبيض مائل للأصفر الفاتح.'),
  ('colors-tan', 'colors', 20, 'tan', 'He came back from the beach with a deep ___.', 'لون بني فاتح، غالباً لون البشرة بعد الشمس.'),
  ('animals-dog', 'animals', 1, 'dog', 'Our ___ waits by the door every day at five.', 'الكلب.'),
  ('animals-cat', 'animals', 2, 'cat', 'The ___ knocked my glass off the table again.', 'القطة.'),
  ('animals-horse', 'animals', 3, 'horse', 'She learned to ride a ___ when she was six.', 'الحصان.'),
  ('animals-cow', 'animals', 4, 'cow', 'The farmer milks each ___ by hand every morning.', 'البقرة.'),
  ('animals-sheep', 'animals', 5, 'sheep', 'A ___ wandered onto the road near the village.', 'الخروف أو النعجة.'),
  ('animals-goat', 'animals', 6, 'goat', 'The ___ ate right through my grandfather''s fence.', 'الماعز.'),
  ('animals-chicken', 'animals', 7, 'chicken', 'We keep three ___s in the backyard for eggs.', 'الدجاجة.'),
  ('animals-duck', 'animals', 8, 'duck', 'A ___ and her babies crossed the park path.', 'البطة.'),
  ('animals-rabbit', 'animals', 9, 'rabbit', 'A ___ has been eating the vegetables in our garden.', 'الأرنب.'),
  ('animals-mouse', 'animals', 10, 'mouse', 'A tiny ___ ran across the kitchen floor last night.', 'الفأر.'),
  ('animals-elephant', 'animals', 11, 'elephant', 'The ___ at the zoo sprayed water at the visitors.', 'الفيل.'),
  ('animals-lion', 'animals', 12, 'lion', 'The ___ slept in the shade for most of the afternoon.', 'الأسد.'),
  ('animals-tiger', 'animals', 13, 'tiger', 'A ___ can run much faster than most people realize.', 'النمر.'),
  ('animals-bear', 'animals', 14, 'bear', 'Hikers are told to store food away from ___s.', 'الدب.'),
  ('animals-monkey', 'animals', 15, 'monkey', 'A ___ grabbed a banana right out of his hand.', 'القرد.'),
  ('animals-fox', 'animals', 16, 'fox', 'A ___ crossed the yard just after sunset.', 'الثعلب.'),
  ('animals-wolf', 'animals', 17, 'wolf', 'We heard a ___ howling somewhere in the hills.', 'الذئب.'),
  ('animals-deer', 'animals', 18, 'deer', 'A ___ froze in the headlights for a moment.', 'الغزال أو الأيل.'),
  ('animals-squirrel', 'animals', 19, 'squirrel', 'A ___ buried something under our porch this morning.', 'السنجاب.'),
  ('animals-turtle', 'animals', 20, 'turtle', 'The ___ took almost an hour to cross the path.', 'السلحفاة.'),
  ('friendship-trust', 'friendship', 1, 'trust', 'It took years to build the ___ we have now.', 'الثقة.'),
  ('friendship-loyal', 'friendship', 2, 'loyal', 'She''s stayed ___ to the same friends since school.', 'مخلص أو وفي.'),
  ('friendship-betray', 'friendship', 3, 'betray', 'He would never ___ a friend''s secret.', 'يخون أو يفشي سراً.'),
  ('friendship-forgive', 'friendship', 4, 'forgive', 'It took a while, but I finally ___ him.', 'يسامح.'),
  ('friendship-argument', 'friendship', 5, 'argument', 'We had a silly ___ about nothing important.', 'خلاف أو جدال.'),
  ('friendship-reconcile', 'friendship', 6, 'reconcile', 'They finally managed to ___ after months of silence.', 'يتصالح بعد خلاف.'),
  ('friendship-support', 'friendship', 7, 'support', 'My friends showed up to ___ me at the hospital.', 'يدعم أو يساند.'),
  ('friendship-jealous', 'friendship', 8, 'jealous', 'I felt a little ___ when she got the promotion.', 'غيور.'),
  ('friendship-sincere', 'friendship', 9, 'sincere', 'His apology sounded completely ___.', 'صادق أو مخلص في المشاعر.'),
  ('friendship-reliable', 'friendship', 10, 'reliable', 'She''s the most ___ person I know — always on time.', 'يمكن الاعتماد عليه.'),
  ('friendship-companion', 'friendship', 11, 'companion', 'He''s been my travel ___ on every trip since college.', 'رفيق أو مرافق.'),
  ('friendship-bond', 'friendship', 12, 'bond', 'Living together for a year created a real ___ between them.', 'رابطة أو علاقة وثيقة.'),
  ('friendship-gossip', 'friendship', 13, 'gossip', 'I try not to ___ about people who aren''t there.', 'يتحدث بالنميمة.'),
  ('friendship-apologize', 'friendship', 14, 'apologize', 'He called just to ___ for forgetting my birthday.', 'يعتذر.'),
  ('friendship-comfort', 'friendship', 15, 'comfort', 'She sat with me for hours, just to offer ___.', 'المواساة أو العزاء.'),
  ('friendship-distant', 'friendship', 16, 'distant', 'We''ve grown a bit ___ since he moved away.', 'بعيد أو غير قريب عاطفياً.'),
  ('friendship-reunite', 'friendship', 17, 'reunite', 'The whole group is finally going to ___ this summer.', 'يجتمع مجدداً بعد فراق.'),
  ('friendship-honest', 'friendship', 18, 'honest', 'Be ___ with me — did you actually like the movie?', 'صادق.'),
  ('friendship-grudge', 'friendship', 19, 'grudge', 'She still holds a ___ over something he said years ago.', 'ضغينة أو حقد قديم.'),
  ('friendship-inseparable', 'friendship', 20, 'inseparable', 'The two of them have been ___ since kindergarten.', 'لا يمكن فصلهما، مرتبطان دائماً.'),
  ('travel-itinerary', 'travel', 1, 'itinerary', 'She planned every stop of our ___ months in advance.', 'خطة أو برنامج الرحلة.'),
  ('travel-layover', 'travel', 2, 'layover', 'We had a six-hour ___ in Istanbul.', 'توقف مؤقت بين رحلتين جويتين.'),
  ('travel-journey', 'travel', 3, 'journey', 'The ___ took longer than we expected, but it was worth it.', 'الرحلة، غالباً الطويلة أو المهمة.'),
  ('travel-destination', 'travel', 4, 'destination', 'We still hadn''t picked a ___ by Thursday night.', 'الوجهة، المكان الذي تقصده.'),
  ('travel-luggage', 'travel', 5, 'luggage', 'My ___ didn''t arrive until the next morning.', 'الأمتعة أو الحقائب.'),
  ('travel-passport', 'travel', 6, 'passport', 'I nearly left my ___ at home again.', 'جواز السفر.'),
  ('travel-customs', 'travel', 7, 'customs', 'It took almost an hour to get through ___.', 'الجمارك في المطار أو الحدود.'),
  ('travel-delay', 'travel', 8, 'delay', 'A two-hour ___ meant we missed our connection.', 'التأخير.'),
  ('travel-souvenir', 'travel', 9, 'souvenir', 'I always bring back a small ___ for my mother.', 'هدية تذكارية من السفر.'),
  ('travel-accommodation', 'travel', 10, 'accommodation', 'We booked our ___ just two days before the trip.', 'مكان الإقامة، مثل الفندق أو الشقة.'),
  ('travel-excursion', 'travel', 11, 'excursion', 'The hotel offered a day ___ to the old town.', 'رحلة قصيرة أو جولة.'),
  ('travel-backpack', 'travel', 12, 'backpack', 'He traveled for a month with just one ___.', 'حقيبة الظهر.'),
  ('travel-wanderlust', 'travel', 13, 'wanderlust', 'One trip to Spain was enough to give her ___ for life.', 'شغف السفر واستكشاف أماكن جديدة.'),
  ('travel-detour', 'travel', 14, 'detour', 'We took a ___ through the mountains instead of the highway.', 'طريق بديل أو التفافي.'),
  ('travel-sightseeing', 'travel', 15, 'sightseeing', 'We spent the whole first day just ___.', 'التجول لمشاهدة المعالم.'),
  ('travel-currency', 'travel', 16, 'currency', 'I forgot to exchange ___ before we landed.', 'العملة.'),
  ('travel-visa', 'travel', 17, 'visa', 'Our ___ application took almost three weeks to process.', 'التأشيرة.'),
  ('travel-boarding', 'travel', 18, 'boarding', '___ starts thirty minutes before the flight leaves.', 'الصعود إلى الطائرة.'),
  ('travel-transit', 'travel', 19, 'transit', 'We spent the night in the airport, stuck in ___.', 'العبور أو التنقل بين وجهتين.'),
  ('travel-hospitality', 'travel', 20, 'hospitality', 'We were amazed by the ___ of everyone we met there.', 'كرم الضيافة.'),
  ('health-symptom', 'health', 1, 'symptom', 'A sore throat was the first ___ I noticed.', 'العرض المرضي.'),
  ('health-diagnosis', 'health', 2, 'diagnosis', 'It took two more tests to confirm the ___.', 'التشخيص الطبي.'),
  ('health-prescription', 'health', 3, 'prescription', 'The doctor handed me a ___ and told me to rest.', 'الوصفة الطبية.'),
  ('health-recover', 'health', 4, 'recover', 'It took her almost a month to fully ___.', 'يتعافى أو يشفى.'),
  ('health-exhausted', 'health', 5, 'exhausted', 'I was too ___ to even make dinner last night.', 'منهك أو مرهق جداً.'),
  ('health-allergic', 'health', 6, 'allergic', 'He''s ___ to anything with peanuts in it.', 'لديه حساسية من شيء ما.'),
  ('health-infection', 'health', 7, 'infection', 'The cut on my hand developed a small ___.', 'الالتهاب أو العدوى.'),
  ('health-appointment', 'health', 8, 'appointment', 'I had to reschedule my ___ twice this month.', 'الموعد الطبي.'),
  ('health-treatment', 'health', 9, 'treatment', 'The new ___ made a real difference within days.', 'العلاج.'),
  ('health-injury', 'health', 10, 'injury', 'He''s been out of the game since his knee ___.', 'الإصابة.'),
  ('health-immune', 'health', 11, 'immune', 'A good night''s sleep really helps your ___ system.', 'المناعة.'),
  ('health-fever', 'health', 12, 'fever', 'She stayed home with a mild ___ all week.', 'الحمى.'),
  ('health-dizzy', 'health', 13, 'dizzy', 'I felt ___ after standing up too quickly.', 'دوار أو دوخة.'),
  ('health-nutrition', 'health', 14, 'nutrition', 'The doctor asked a lot of questions about my ___.', 'التغذية.'),
  ('health-therapy', 'health', 15, 'therapy', 'He''s been going to physical ___ twice a week.', 'العلاج الطبيعي أو النفسي.'),
  ('health-chronic', 'health', 16, 'chronic', 'She''s managed a ___ back problem for years.', 'مزمن، حالة تستمر لفترة طويلة.'),
  ('health-checkup', 'health', 17, 'checkup', 'It''s just a routine ___ — nothing to worry about.', 'الفحص الدوري.'),
  ('health-remedy', 'health', 18, 'remedy', 'My grandmother swears by an old home ___ for colds.', 'العلاج أو الدواء، غالباً منزلي أو تقليدي.'),
  ('health-insomnia', 'health', 19, 'insomnia', 'Stress at work has been giving me ___ all month.', 'الأرق، صعوبة النوم.'),
  ('health-wellbeing', 'health', 20, 'wellbeing', 'The company started caring more about employee ___.', 'الرفاهية أو الصحة العامة.'),
  ('politics-democracy', 'politics', 1, 'democracy', 'For all its flaws, he still believes strongly in ___.', 'الديمقراطية.'),
  ('politics-legislation', 'politics', 2, 'legislation', 'The new ___ won''t take effect until next year.', 'التشريع أو القانون.'),
  ('politics-campaign', 'politics', 3, 'campaign', 'Her ___ focused almost entirely on housing costs.', 'الحملة الانتخابية.'),
  ('politics-referendum', 'politics', 4, 'referendum', 'The government finally agreed to hold a ___ on the issue.', 'الاستفتاء الشعبي.'),
  ('politics-diplomacy', 'politics', 5, 'diplomacy', 'Years of quiet ___ finally ended the dispute.', 'الدبلوماسية.'),
  ('politics-sovereignty', 'politics', 6, 'sovereignty', 'The treaty raised real questions about national ___.', 'السيادة الوطنية.'),
  ('politics-coalition', 'politics', 7, 'coalition', 'No single party had enough seats without forming a ___.', 'التحالف السياسي.'),
  ('politics-corruption', 'politics', 8, 'corruption', 'The scandal exposed years of quiet ___.', 'الفساد.'),
  ('politics-activism', 'politics', 9, 'activism', 'Her ___ started with a single letter to a local paper.', 'النشاط الحقوقي أو الاجتماعي.'),
  ('politics-bureaucracy', 'politics', 10, 'bureaucracy', 'It took six months to get through the ___.', 'البيروقراطية، الإجراءات الإدارية المعقدة.'),
  ('politics-propaganda', 'politics', 11, 'propaganda', 'Historians still study how effective that ___ campaign really was.', 'الدعاية الموجهة.'),
  ('politics-constituency', 'politics', 12, 'constituency', 'He''s represented the same ___ for over a decade.', 'الدائرة الانتخابية.'),
  ('politics-lobbying', 'politics', 13, 'lobbying', 'The industry spent millions on ___ last year alone.', 'الضغط أو التأثير على صناع القرار.'),
  ('politics-autonomy', 'politics', 14, 'autonomy', 'The region has had a degree of ___ since the agreement.', 'الحكم الذاتي أو الاستقلالية.'),
  ('politics-censorship', 'politics', 15, 'censorship', 'The new law raised concerns about press ___.', 'الرقابة على الإعلام أو المحتوى.'),
  ('politics-dissent', 'politics', 16, 'dissent', 'Even within his own party, there was quiet ___.', 'المعارضة أو الاعتراض.'),
  ('politics-electorate', 'politics', 17, 'electorate', 'The ___ seemed far more divided than the polls suggested.', 'جمهور الناخبين.'),
  ('politics-policy', 'politics', 18, 'policy', 'The new ___ changed almost overnight after the protests.', 'السياسة أو القرار الرسمي.'),
  ('politics-regime', 'politics', 19, 'regime', 'The old ___ collapsed within a matter of weeks.', 'النظام الحاكم.'),
  ('politics-accountability', 'politics', 20, 'accountability', 'Voters were mostly asking for basic ___, not perfection.', 'المساءلة.'),
  ('finance-investment', 'finance', 1, 'investment', 'That old apartment turned out to be his best ___.', 'الاستثمار.'),
  ('finance-inflation', 'finance', 2, 'inflation', '___ has made groceries noticeably more expensive this year.', 'التضخم، ارتفاع الأسعار العام.'),
  ('finance-dividend', 'finance', 3, 'dividend', 'The company pays a small ___ every quarter.', 'توزيعات الأرباح.'),
  ('finance-liability', 'finance', 4, 'liability', 'The old debt is still listed as a ___ on the books.', 'الالتزام المالي أو الدين.'),
  ('finance-portfolio', 'finance', 5, 'portfolio', 'She spread her ___ across several different industries.', 'المحفظة الاستثمارية.'),
  ('finance-equity', 'finance', 6, 'equity', 'He traded a salary cut for ___ in the startup.', 'حصة ملكية في شركة.'),
  ('finance-revenue', 'finance', 7, 'revenue', '___ doubled once they launched the online store.', 'الإيرادات.'),
  ('finance-deficit', 'finance', 8, 'deficit', 'The country''s budget ___ grew larger than expected.', 'العجز المالي.'),
  ('finance-asset', 'finance', 9, 'asset', 'The building is still their most valuable ___.', 'الأصل المالي.'),
  ('finance-mortgage', 'finance', 10, 'mortgage', 'They''ll finish paying off the ___ in three more years.', 'الرهن العقاري، قرض شراء منزل.'),
  ('finance-interest', 'finance', 11, 'interest', 'The bank raised the ___ rate again this month.', 'الفائدة.'),
  ('finance-budget', 'finance', 12, 'budget', 'We went over ___ on the kitchen renovation.', 'الميزانية.'),
  ('finance-leverage', 'finance', 13, 'leverage', 'He used the offer as ___ to negotiate a raise.', 'الاستفادة من موقف لتحقيق ميزة.'),
  ('finance-valuation', 'finance', 14, 'valuation', 'Investors questioned the company''s ___ almost immediately.', 'التقييم المالي لشركة أو أصل.'),
  ('finance-liquidity', 'finance', 15, 'liquidity', 'The business had assets but no real ___.', 'السيولة المالية.'),
  ('finance-subsidy', 'finance', 16, 'subsidy', 'Farmers rely heavily on the government ___.', 'الدعم الحكومي المالي.'),
  ('finance-taxation', 'finance', 17, 'taxation', 'The new ___ policy hit small businesses the hardest.', 'الضرائب.'),
  ('finance-forecast', 'finance', 18, 'forecast', 'This quarter''s ___ was far more optimistic than the last.', 'التوقعات المالية المستقبلية.'),
  ('finance-insolvency', 'finance', 19, 'insolvency', 'The company was just weeks away from ___.', 'الإعسار المالي، عدم القدرة على سداد الديون.'),
  ('finance-diversify', 'finance', 20, 'diversify', 'Her advisor suggested she ___ instead of buying just one stock.', 'ينوّع الاستثمارات لتقليل المخاطر.'),
  ('technology-algorithm', 'technology', 1, 'algorithm', 'The app''s ___ kept recommending the same three songs.', 'الخوارزمية.'),
  ('technology-encryption', 'technology', 2, 'encryption', 'The message is protected by end-to-end ___.', 'التشفير.'),
  ('technology-bandwidth', 'technology', 3, 'bandwidth', 'Too many people on the network slowed our ___ to a crawl.', 'عرض النطاق الترددي، سرعة نقل البيانات.'),
  ('technology-interface', 'technology', 4, 'interface', 'They redesigned the whole ___ to feel simpler.', 'واجهة المستخدم.'),
  ('technology-firmware', 'technology', 5, 'firmware', 'A quick ___ update fixed the connection problem.', 'البرنامج الثابت المدمج في جهاز.'),
  ('technology-cybersecurity', 'technology', 6, 'cybersecurity', 'The company hired an outside team to review its ___.', 'الأمن السيبراني.'),
  ('technology-automation', 'technology', 7, 'automation', '___ cut the process from an hour down to minutes.', 'الأتمتة.'),
  ('technology-scalability', 'technology', 8, 'scalability', 'Investors were more interested in ___ than in current profit.', 'قابلية التوسع.'),
  ('technology-latency', 'technology', 9, 'latency', 'The video call kept freezing because of the ___.', 'زمن الاستجابة أو التأخير في الشبكة.'),
  ('technology-deprecated', 'technology', 10, 'deprecated', 'That feature was quietly ___ two versions ago.', 'مهمل أو تم التخلي عنه تدريجياً.'),
  ('technology-integration', 'technology', 11, 'integration', 'The ___ between the two systems took months to finish.', 'الدمج أو الربط بين أنظمة.'),
  ('technology-backend', 'technology', 12, 'backend', 'The site looked fine, but the ___ kept crashing.', 'الجزء الخلفي من النظام، غير المرئي للمستخدم.'),
  ('technology-deployment', 'technology', 13, 'deployment', 'The team scheduled the ___ for early Monday morning.', 'نشر أو إطلاق تحديث برمجي.'),
  ('technology-glitch', 'technology', 14, 'glitch', 'A strange ___ kept logging users out at random.', 'خلل مؤقت وبسيط.'),
  ('technology-obsolete', 'technology', 15, 'obsolete', 'That whole approach became ___ within a couple of years.', 'قديم أو تجاوزه الزمن.'),
  ('technology-compatibility', 'technology', 16, 'compatibility', 'The old software had serious ___ issues with the new phones.', 'التوافق بين الأنظمة أو الأجهزة.'),
  ('technology-malware', 'technology', 17, 'malware', 'The email attachment turned out to be ___.', 'برمجية خبيثة.'),
  ('technology-protocol', 'technology', 18, 'protocol', 'The two devices communicate using a shared ___.', 'البروتوكول، مجموعة قواعد للاتصال.'),
  ('technology-upgrade', 'technology', 19, 'upgrade', 'The latest ___ finally fixed the battery problem.', 'التحديث أو الترقية.'),
  ('technology-breach', 'technology', 20, 'breach', 'The company had to notify users after the data ___.', 'اختراق أمني.') on conflict (id) do nothing;

commit;
