-- Library expansion round 3: 2 beginner-level (L1) books — the
-- catalog had zero L1 titles until now (16 at L2, 7 at L3). Applied
-- to the live project via scripts/insert-books-3.ts; captured here
-- for tracking.
begin;

insert into books (id, title, author, description, difficulty_level, is_featured, is_free, status, order_index) values
  ('book-the-little-prince', 'The Little Prince', 'Antoine de Saint-Exupery', 'An original SentenceStep summary of Antoine de Saint-Exupery''s beloved story about a young prince who travels from planet to planet, learning simple truths about love, loneliness, and what truly matters in life', 1, false, true, 'published', 23),
  ('book-who-moved-my-cheese', 'Who Moved My Cheese?', 'Spencer Johnson', 'An original SentenceStep summary of Spencer Johnson''s simple parable about four characters in a maze, and what their search for cheese teaches about handling change with less fear', 1, false, true, 'published', 24) on conflict (id) do nothing;

insert into book_categories (book_id, category_id, is_primary) values
  ('book-the-little-prince', 'category-philosophy', true),
  ('book-the-little-prince', 'category-self-development', false),
  ('book-who-moved-my-cheese', 'category-self-development', true),
  ('book-who-moved-my-cheese', 'category-business', false) on conflict (book_id, category_id) do nothing;

insert into book_sections (id, book_id, order_index, title, description) values
  ('book-the-little-prince-sec1', 'book-the-little-prince', 1, 'A Pilot in the Desert', 'A pilot crashes in the Sahara and meets a strange little boy'),
  ('book-the-little-prince-sec2', 'book-the-little-prince', 2, 'The Little Prince''s Planet', 'A tiny planet with three volcanoes, a proud flower, and daily chores'),
  ('book-the-little-prince-sec3', 'book-the-little-prince', 3, 'The Rose He Loved', 'A beautiful, proud rose, and the sadness of leaving her behind'),
  ('book-the-little-prince-sec4', 'book-the-little-prince', 4, 'Strange Grown-Ups on Other Planets', 'A king, a vain man, and a businessman who all seem stranger than the last'),
  ('book-the-little-prince-sec5', 'book-the-little-prince', 5, 'The Fox and Its Secret', 'A clever fox teaches him what it means to truly see'),
  ('book-the-little-prince-sec6', 'book-the-little-prince', 6, 'Remembering the Rose', 'Why his one rose matters more than any other flower'),
  ('book-the-little-prince-sec7', 'book-the-little-prince', 7, 'Meeting the Pilot', 'A quiet friendship grows in the desert'),
  ('book-the-little-prince-sec8', 'book-the-little-prince', 8, 'Going Home to the Stars', 'A gentle goodbye, and a reminder to look closely at what matters'),
  ('book-who-moved-my-cheese-sec1', 'book-who-moved-my-cheese', 1, 'Four Characters in a Maze', 'Two mice and two tiny people, all searching for cheese'),
  ('book-who-moved-my-cheese-sec2', 'book-who-moved-my-cheese', 2, 'Finding Cheese Station C', 'A big supply of cheese, and two very different reactions to it'),
  ('book-who-moved-my-cheese-sec3', 'book-who-moved-my-cheese', 3, 'The Cheese Disappears', 'One morning, the cheese is simply gone'),
  ('book-who-moved-my-cheese-sec4', 'book-who-moved-my-cheese', 4, 'Fear of the Unknown', 'One friend waits, the other decides to search again'),
  ('book-who-moved-my-cheese-sec5', 'book-who-moved-my-cheese', 5, 'Writing on the Wall', 'Small written reminders that slowly build his courage'),
  ('book-who-moved-my-cheese-sec6', 'book-who-moved-my-cheese', 6, 'Enjoying the Journey', 'Why imagining success early makes the search feel lighter'),
  ('book-who-moved-my-cheese-sec7', 'book-who-moved-my-cheese', 7, 'Finding New Cheese', 'A wonderful discovery, and a wish that his friend had come too'),
  ('book-who-moved-my-cheese-sec8', 'book-who-moved-my-cheese', 8, 'What the Cheese Really Means', 'The lesson Haw leaves behind for whoever follows') on conflict (id) do nothing;

insert into book_sentences (id, section_id, order_index, en) values
  ('book-the-little-prince-sec1-s1', 'book-the-little-prince-sec1', 1, 'A pilot crash-lands his plane alone in the Sahara Desert'),
  ('book-the-little-prince-sec1-s2', 'book-the-little-prince-sec1', 2, 'He has very little water and must fix his engine fast'),
  ('book-the-little-prince-sec1-s3', 'book-the-little-prince-sec1', 3, 'A strange small boy appears and asks him to draw a sheep'),
  ('book-the-little-prince-sec1-s4', 'book-the-little-prince-sec1', 4, 'The pilot is surprised because no one lives near this empty place'),
  ('book-the-little-prince-sec1-s5', 'book-the-little-prince-sec1', 5, 'The boy says he has come from a very small planet far away'),
  ('book-the-little-prince-sec2-s1', 'book-the-little-prince-sec2', 1, 'The little prince lives on a tiny planet called Asteroid B-612'),
  ('book-the-little-prince-sec2-s2', 'book-the-little-prince-sec2', 2, 'His planet is so small he can watch the sunset many times a day'),
  ('book-the-little-prince-sec2-s3', 'book-the-little-prince-sec2', 3, 'Three small volcanoes and one proud flower grow on his planet'),
  ('book-the-little-prince-sec2-s4', 'book-the-little-prince-sec2', 4, 'Every morning he pulls out small trees called baobabs before they grow too big'),
  ('book-the-little-prince-sec2-s5', 'book-the-little-prince-sec2', 5, 'He takes great care of his tiny world every single day'),
  ('book-the-little-prince-sec3-s1', 'book-the-little-prince-sec3', 1, 'One day a beautiful rose grows on the little prince''s planet'),
  ('book-the-little-prince-sec3-s2', 'book-the-little-prince-sec3', 2, 'The rose is proud and often says unkind things to him'),
  ('book-the-little-prince-sec3-s3', 'book-the-little-prince-sec3', 3, 'He loves her deeply but her words hurt his feelings often'),
  ('book-the-little-prince-sec3-s4', 'book-the-little-prince-sec3', 4, 'He decides one day to leave his planet and see other worlds'),
  ('book-the-little-prince-sec3-s5', 'book-the-little-prince-sec3', 5, 'Leaving the rose behind makes him feel both free and very sad'),
  ('book-the-little-prince-sec4-s1', 'book-the-little-prince-sec4', 1, 'The little prince visits several planets before reaching Earth'),
  ('book-the-little-prince-sec4-s2', 'book-the-little-prince-sec4', 2, 'On one planet a king rules over nobody but still gives orders'),
  ('book-the-little-prince-sec4-s3', 'book-the-little-prince-sec4', 3, 'On another planet a man only cares about being admired by others'),
  ('book-the-little-prince-sec4-s4', 'book-the-little-prince-sec4', 4, 'A businessman spends all day counting stars he believes he owns'),
  ('book-the-little-prince-sec4-s5', 'book-the-little-prince-sec4', 5, 'The little prince finds each grown-up stranger than the one before'),
  ('book-the-little-prince-sec5-s1', 'book-the-little-prince-sec5', 1, 'On Earth the little prince meets a clever fox in a field'),
  ('book-the-little-prince-sec5-s2', 'book-the-little-prince-sec5', 2, 'The fox asks the prince to tame him so they can become friends'),
  ('book-the-little-prince-sec5-s3', 'book-the-little-prince-sec5', 3, 'Taming means slowly building trust and understanding between two hearts'),
  ('book-the-little-prince-sec5-s4', 'book-the-little-prince-sec5', 4, 'The fox shares a secret, what matters most is invisible to the eye'),
  ('book-the-little-prince-sec5-s5', 'book-the-little-prince-sec5', 5, 'He says people only truly see well with their heart, not their eyes'),
  ('book-the-little-prince-sec6-s1', 'book-the-little-prince-sec6', 1, 'The fox tells him his rose is special because of the time he gave her'),
  ('book-the-little-prince-sec6-s2', 'book-the-little-prince-sec6', 2, 'The little prince finally understands why she matters more than any other flower'),
  ('book-the-little-prince-sec6-s3', 'book-the-little-prince-sec6', 3, 'He realizes love means the time and care we choose to give'),
  ('book-the-little-prince-sec6-s4', 'book-the-little-prince-sec6', 4, 'This simple idea changes how the little prince sees his whole journey'),
  ('book-the-little-prince-sec6-s5', 'book-the-little-prince-sec6', 5, 'He now understands his rose was never like any other flower at all'),
  ('book-the-little-prince-sec7-s1', 'book-the-little-prince-sec7', 1, 'The little prince finally meets the tired pilot fixing his plane'),
  ('book-the-little-prince-sec7-s2', 'book-the-little-prince-sec7', 2, 'They talk every day while the pilot searches for water and parts'),
  ('book-the-little-prince-sec7-s3', 'book-the-little-prince-sec7', 3, 'The little prince asks the pilot to draw him many more sheep'),
  ('book-the-little-prince-sec7-s4', 'book-the-little-prince-sec7', 4, 'Slowly the pilot begins to understand the boy''s strange gentle world'),
  ('book-the-little-prince-sec7-s5', 'book-the-little-prince-sec7', 5, 'Their friendship grows stronger with every quiet conversation in the desert'),
  ('book-the-little-prince-sec8-s1', 'book-the-little-prince-sec8', 1, 'The little prince says it is time for him to return to his planet'),
  ('book-the-little-prince-sec8-s2', 'book-the-little-prince-sec8', 2, 'He tells the pilot not to feel sad when he is gone'),
  ('book-the-little-prince-sec8-s3', 'book-the-little-prince-sec8', 3, 'He explains that his star will be like a small laughing bell for the pilot'),
  ('book-the-little-prince-sec8-s4', 'book-the-little-prince-sec8', 4, 'The pilot finishes fixing his plane and watches the sky every night after'),
  ('book-the-little-prince-sec8-s5', 'book-the-little-prince-sec8', 5, 'The story ends by asking us to always look closely for what truly matters'),
  ('book-who-moved-my-cheese-sec1-s1', 'book-who-moved-my-cheese-sec1', 1, 'Two mice named Sniff and Scurry live inside a large maze'),
  ('book-who-moved-my-cheese-sec1-s2', 'book-who-moved-my-cheese-sec1', 2, 'Two tiny people named Hem and Haw also live in the very same maze'),
  ('book-who-moved-my-cheese-sec1-s3', 'book-who-moved-my-cheese-sec1', 3, 'All four spend their days searching the maze for cheese to eat'),
  ('book-who-moved-my-cheese-sec1-s4', 'book-who-moved-my-cheese-sec1', 4, 'Cheese in this story stands for anything we want in our life'),
  ('book-who-moved-my-cheese-sec1-s5', 'book-who-moved-my-cheese-sec1', 5, 'Each character searches for cheese in their own very different way'),
  ('book-who-moved-my-cheese-sec2-s1', 'book-who-moved-my-cheese-sec2', 1, 'One day all four finally find a big supply of cheese'),
  ('book-who-moved-my-cheese-sec2-s2', 'book-who-moved-my-cheese-sec2', 2, 'They find it waiting for them inside a place called Cheese Station C'),
  ('book-who-moved-my-cheese-sec2-s3', 'book-who-moved-my-cheese-sec2', 3, 'The mice, Sniff and Scurry, keep their simple daily routine unchanged'),
  ('book-who-moved-my-cheese-sec2-s4', 'book-who-moved-my-cheese-sec2', 4, 'Hem and Haw grow comfortable and begin to relax completely'),
  ('book-who-moved-my-cheese-sec2-s5', 'book-who-moved-my-cheese-sec2', 5, 'They soon believe the cheese will always be there for them'),
  ('book-who-moved-my-cheese-sec3-s1', 'book-who-moved-my-cheese-sec3', 1, 'One morning the cheese at Station C is completely gone'),
  ('book-who-moved-my-cheese-sec3-s2', 'book-who-moved-my-cheese-sec3', 2, 'Sniff and Scurry are not surprised and quickly start searching again'),
  ('book-who-moved-my-cheese-sec3-s3', 'book-who-moved-my-cheese-sec3', 3, 'Hem and Haw are shocked and feel deeply upset by the sudden change'),
  ('book-who-moved-my-cheese-sec3-s4', 'book-who-moved-my-cheese-sec3', 4, 'Hem shouts angrily, certain that this change is simply not fair'),
  ('book-who-moved-my-cheese-sec3-s5', 'book-who-moved-my-cheese-sec3', 5, 'Haw feels scared but quietly begins to wonder what they should do next'),
  ('book-who-moved-my-cheese-sec4-s1', 'book-who-moved-my-cheese-sec4', 1, 'Hem refuses to leave Station C, hoping the cheese will simply return'),
  ('book-who-moved-my-cheese-sec4-s2', 'book-who-moved-my-cheese-sec4', 2, 'Haw grows hungrier and slowly realizes that waiting will not help them'),
  ('book-who-moved-my-cheese-sec4-s3', 'book-who-moved-my-cheese-sec4', 3, 'He understands that fear of change is often worse than change itself'),
  ('book-who-moved-my-cheese-sec4-s4', 'book-who-moved-my-cheese-sec4', 4, 'Haw finally decides to step back into the maze and search again'),
  ('book-who-moved-my-cheese-sec4-s5', 'book-who-moved-my-cheese-sec4', 5, 'He writes messages on the maze walls to help guide his friend Hem'),
  ('book-who-moved-my-cheese-sec5-s1', 'book-who-moved-my-cheese-sec5', 1, 'Haw writes simple short sayings on the walls as he explores further'),
  ('book-who-moved-my-cheese-sec5-s2', 'book-who-moved-my-cheese-sec5', 2, 'One message reads plainly, if you do not change, you can become extinct'),
  ('book-who-moved-my-cheese-sec5-s3', 'book-who-moved-my-cheese-sec5', 3, 'Another message asks him what he would do if he were not afraid'),
  ('book-who-moved-my-cheese-sec5-s4', 'book-who-moved-my-cheese-sec5', 4, 'These small written reminders slowly help him feel braver each day'),
  ('book-who-moved-my-cheese-sec5-s5', 'book-who-moved-my-cheese-sec5', 5, 'He begins to imagine finding new cheese somewhere further in the maze'),
  ('book-who-moved-my-cheese-sec6-s1', 'book-who-moved-my-cheese-sec6', 1, 'As Haw explores he notices he actually enjoys searching again'),
  ('book-who-moved-my-cheese-sec6-s2', 'book-who-moved-my-cheese-sec6', 2, 'He imagines himself already enjoying new cheese, even before finding it'),
  ('book-who-moved-my-cheese-sec6-s3', 'book-who-moved-my-cheese-sec6', 3, 'This small imagined picture in his mind helps him keep moving forward'),
  ('book-who-moved-my-cheese-sec6-s4', 'book-who-moved-my-cheese-sec6', 4, 'He realizes that moving forward, even slowly, feels better than standing still'),
  ('book-who-moved-my-cheese-sec6-s5', 'book-who-moved-my-cheese-sec6', 5, 'Haw begins smiling more, even while he is still searching the maze'),
  ('book-who-moved-my-cheese-sec7-s1', 'book-who-moved-my-cheese-sec7', 1, 'Eventually Haw discovers a wonderful new supply of cheese in the maze'),
  ('book-who-moved-my-cheese-sec7-s2', 'book-who-moved-my-cheese-sec7', 2, 'Sniff and Scurry are already there, having arrived much earlier than him'),
  ('book-who-moved-my-cheese-sec7-s3', 'book-who-moved-my-cheese-sec7', 3, 'Haw finally understands why moving quickly with change matters so much'),
  ('book-who-moved-my-cheese-sec7-s4', 'book-who-moved-my-cheese-sec7', 4, 'He wishes his friend Hem had come with him to see this new place'),
  ('book-who-moved-my-cheese-sec7-s5', 'book-who-moved-my-cheese-sec7', 5, 'He leaves signs behind, hoping Hem will one day follow his path too'),
  ('book-who-moved-my-cheese-sec8-s1', 'book-who-moved-my-cheese-sec8', 1, 'Haw writes his biggest lesson clearly on the new station''s wall'),
  ('book-who-moved-my-cheese-sec8-s2', 'book-who-moved-my-cheese-sec8', 2, 'He notes that change keeps happening whether we expect it or not'),
  ('book-who-moved-my-cheese-sec8-s3', 'book-who-moved-my-cheese-sec8', 3, 'Watching for small changes early can help us adapt before it''s too late'),
  ('book-who-moved-my-cheese-sec8-s4', 'book-who-moved-my-cheese-sec8', 4, 'Moving in a new direction can actually feel exciting instead of frightening'),
  ('book-who-moved-my-cheese-sec8-s5', 'book-who-moved-my-cheese-sec8', 5, 'The story ends by reminding us that new cheese is always somewhere out there') on conflict (id) do nothing;

commit;
