-- Word Lists content expansion: 9 new groups (3 per tier), 20 words each,
-- bringing every tier from 3 groups to 6. Same shape as
-- 20250143000000_word_lists_seed_content.sql; themes deliberately distinct
-- from the existing 9 groups (Family/Colors/Animals, Friendship/Travel/
-- Health, Politics/Finance/Technology) and from each other. Applied to
-- the live project via scripts/insert-word-lists-expansion.ts; captured
-- here as a real, idempotent migration (on conflict do nothing) for
-- tracking, same precedent as that earlier out-of-band seed.
begin;

insert into word_groups (id, level, order_index, title, title_ar, description, description_ar, is_free, status) values
  ('food', 1, 10, 'Food', 'الطعام', 'Everyday food words for meals, groceries, and eating out.', 'مفردات طعام يومية للوجبات والتسوق وتناول الطعام خارج المنزل.', false, 'published'),
  ('house', 1, 11, 'House', 'المنزل', 'The rooms and everyday things around a home.', 'غرف المنزل والأشياء اليومية الموجودة فيه.', false, 'published'),
  ('clothes', 1, 12, 'Clothes', 'الملابس', 'What people actually wear, and the words for talking about it.', 'ما يرتديه الناس فعلاً، والكلمات المستخدمة للحديث عنه.', false, 'published'),
  ('shopping', 2, 13, 'Shopping', 'التسوق', 'The vocabulary of buying things — in a store or online.', 'مفردات شراء الأشياء — من متجر أو عبر الإنترنت.', false, 'published'),
  ('weather', 2, 14, 'Weather', 'الطقس', 'How people actually talk about the weather, day to day.', 'كيف يتحدث الناس فعلاً عن الطقس، يوماً بعد يوم.', false, 'published'),
  ('work', 2, 15, 'Work', 'العمل', 'The everyday language of jobs, offices, and getting things done.', 'اللغة اليومية للوظائف والمكاتب وإنجاز المهام.', false, 'published'),
  ('environment', 3, 16, 'Environment', 'البيئة', 'The vocabulary that shows up whenever people discuss the planet.', 'المفردات التي تظهر دائماً عند الحديث عن كوكب الأرض.', false, 'published'),
  ('education', 3, 17, 'Education', 'التعليم', 'School, university, and everything that comes with studying seriously.', 'المدرسة والجامعة وكل ما يرافق الدراسة الجادة.', false, 'published'),
  ('media', 3, 18, 'Media', 'الإعلام', 'News, social platforms, and how information actually spreads today.', 'الأخبار ومنصات التواصل وكيف تنتشر المعلومات فعلاً اليوم.', false, 'published') on conflict (id) do nothing;

insert into vocabulary_words (id, group_id, order_index, target_word, sentence, hint_ar) values
  ('food-bread', 'food', 1, 'bread', 'Could you pass me the ___, please?', 'الخبز.'),
  ('food-rice', 'food', 2, 'rice', 'We usually have ___ with dinner.', 'الأرز.'),
  ('food-water', 'food', 3, 'water', 'Can I get a glass of ___?', 'الماء.'),
  ('food-milk', 'food', 4, 'milk', 'He drinks a glass of ___ every morning.', 'الحليب.'),
  ('food-egg', 'food', 5, 'egg', 'She boiled an ___ for breakfast.', 'البيضة.'),
  ('food-cheese', 'food', 6, 'cheese', 'This sandwich needs more ___.', 'الجبن.'),
  ('food-meat', 'food', 7, 'meat', 'He doesn''t eat ___ on Fridays.', 'اللحم.'),
  ('food-chicken', 'food', 8, 'chicken', 'We''re having grilled ___ tonight.', 'الدجاج (كطعام).'),
  ('food-fish', 'food', 9, 'fish', 'The restaurant serves fresh ___ every day.', 'السمك (كطعام).'),
  ('food-vegetable', 'food', 10, 'vegetable', 'Try to eat at least one ___ with lunch.', 'الخضار.'),
  ('food-fruit', 'food', 11, 'fruit', 'She packed some ___ for the trip.', 'الفاكهة.'),
  ('food-sugar', 'food', 12, 'sugar', 'He takes his tea with a little ___.', 'السكر.'),
  ('food-salt', 'food', 13, 'salt', 'This soup needs a pinch of ___.', 'الملح.'),
  ('food-breakfast', 'food', 14, 'breakfast', 'We never skip ___ in this house.', 'وجبة الفطور.'),
  ('food-lunch', 'food', 15, 'lunch', 'Let''s grab ___ together tomorrow.', 'وجبة الغداء.'),
  ('food-dinner', 'food', 16, 'dinner', '___ is ready, come to the table.', 'وجبة العشاء.'),
  ('food-restaurant', 'food', 17, 'restaurant', 'They opened a new ___ downtown.', 'المطعم.'),
  ('food-menu', 'food', 18, 'menu', 'Can I see the ___, please?', 'قائمة الطعام.'),
  ('food-recipe', 'food', 19, 'recipe', 'She found the ___ online last night.', 'وصفة الطبخ.'),
  ('food-hungry', 'food', 20, 'hungry', 'I''m too ___ to wait any longer.', 'جائع.'),
  ('house-kitchen', 'house', 1, 'kitchen', 'She''s cooking dinner in the ___.', 'المطبخ.'),
  ('house-bedroom', 'house', 2, 'bedroom', 'His ___ is upstairs, next to the bathroom.', 'غرفة النوم.'),
  ('house-bathroom', 'house', 3, 'bathroom', 'The ___ light stopped working this morning.', 'الحمام.'),
  ('house-window', 'house', 4, 'window', 'Open the ___, it''s warm in here.', 'النافذة.'),
  ('house-door', 'house', 5, 'door', 'Please close the ___ behind you.', 'الباب.'),
  ('house-table', 'house', 6, 'table', 'We put the flowers on the ___.', 'الطاولة.'),
  ('house-chair', 'house', 7, 'chair', 'Pull up a ___ and join us.', 'الكرسي.'),
  ('house-bed', 'house', 8, 'bed', 'The cat sleeps on my ___ every night.', 'السرير.'),
  ('house-sofa', 'house', 9, 'sofa', 'He fell asleep on the ___ watching TV.', 'الأريكة.'),
  ('house-key', 'house', 10, 'key', 'I can''t find my house ___ anywhere.', 'المفتاح.'),
  ('house-roof', 'house', 11, 'roof', 'Rain was hitting the ___ all night.', 'السقف.'),
  ('house-garden', 'house', 12, 'garden', 'They grow tomatoes in the ___ every summer.', 'الحديقة.'),
  ('house-stairs', 'house', 13, 'stairs', 'Watch your step going down the ___.', 'الدرج.'),
  ('house-mirror', 'house', 14, 'mirror', 'She checked her hair in the ___.', 'المرآة.'),
  ('house-lamp', 'house', 15, 'lamp', 'Turn on the ___, it''s getting dark.', 'المصباح.'),
  ('house-curtain', 'house', 16, 'curtain', 'Could you close the ___, the sun is bright.', 'الستارة.'),
  ('house-neighbor', 'house', 17, 'neighbor', 'Our ___ waters our plants when we travel.', 'الجار.'),
  ('house-address', 'house', 18, 'address', 'Can you send me your ___?', 'العنوان.'),
  ('house-clean', 'house', 19, 'clean', 'We ___ the whole house every Saturday.', 'ينظف.'),
  ('house-move', 'house', 20, 'move', 'They''re going to ___ to a bigger place next month.', 'ينتقل (للسكن).'),
  ('clothes-shirt', 'clothes', 1, 'shirt', 'He spilled coffee on his new ___.', 'القميص.'),
  ('clothes-pants', 'clothes', 2, 'pants', 'These ___ are too long for me.', 'البنطال.'),
  ('clothes-dress', 'clothes', 3, 'dress', 'She wore a blue ___ to the party.', 'الفستان.'),
  ('clothes-shoes', 'clothes', 4, 'shoes', 'My ___ got wet in the rain.', 'الحذاء.'),
  ('clothes-socks', 'clothes', 5, 'socks', 'I can never find matching ___.', 'الجوارب.'),
  ('clothes-jacket', 'clothes', 6, 'jacket', 'Bring a ___, it gets cold at night.', 'السترة/الجاكيت.'),
  ('clothes-hat', 'clothes', 7, 'hat', 'He wore a ___ to block the sun.', 'القبعة.'),
  ('clothes-scarf', 'clothes', 8, 'scarf', 'She wrapped a warm ___ around her neck.', 'الوشاح.'),
  ('clothes-gloves', 'clothes', 9, 'gloves', 'Put your ___ on, it''s freezing outside.', 'القفازات.'),
  ('clothes-belt', 'clothes', 10, 'belt', 'His pants need a ___ to stay up.', 'الحزام.'),
  ('clothes-size', 'clothes', 11, 'size', 'What ___ do you wear in shoes?', 'المقاس.'),
  ('clothes-fit', 'clothes', 12, 'fit', 'These jeans don''t ___ me anymore.', 'يلائم/يناسب (بالمقاس).'),
  ('clothes-outfit', 'clothes', 13, 'outfit', 'She wore a stylish ___ to the interview.', 'الزي/الإطلالة الكاملة.'),
  ('clothes-wear', 'clothes', 14, 'wear', 'What are you going to ___ tonight?', 'يرتدي.'),
  ('clothes-cotton', 'clothes', 15, 'cotton', 'This shirt is made of pure ___.', 'القطن.'),
  ('clothes-wool', 'clothes', 16, 'wool', 'The sweater is warm because it''s ___.', 'الصوف.'),
  ('clothes-laundry', 'clothes', 17, 'laundry', 'I need to do the ___ this weekend.', 'الغسيل.'),
  ('clothes-iron', 'clothes', 18, 'iron', 'Could you ___ this shirt for me?', 'يكوي.'),
  ('clothes-button', 'clothes', 19, 'button', 'A ___ came off my coat yesterday.', 'الزر.'),
  ('clothes-pocket', 'clothes', 20, 'pocket', 'He keeps his phone in his back ___.', 'الجيب.'),
  ('shopping-store', 'shopping', 1, 'store', 'The ___ closes at nine on weekdays.', 'المتجر.'),
  ('shopping-price', 'shopping', 2, 'price', 'The ___ went up again this month.', 'السعر.'),
  ('shopping-cash', 'shopping', 3, 'cash', 'He paid in ___ instead of card.', 'النقد.'),
  ('shopping-receipt', 'shopping', 4, 'receipt', 'Keep the ___ in case you need to return it.', 'الإيصال.'),
  ('shopping-discount', 'shopping', 5, 'discount', 'We got a nice ___ on the jacket.', 'الخصم.'),
  ('shopping-sale', 'shopping', 6, 'sale', 'The store is having a big ___ this weekend.', 'التخفيضات.'),
  ('shopping-expensive', 'shopping', 7, 'expensive', 'That watch looked way too ___ for me.', 'غالٍ.'),
  ('shopping-cheap', 'shopping', 8, 'cheap', 'This market sells vegetables ___er than the mall.', 'رخيص.'),
  ('shopping-cart', 'shopping', 9, 'cart', 'She filled her ___ with groceries.', 'عربة التسوق.'),
  ('shopping-bag', 'shopping', 10, 'bag', 'Do you need a ___ for that?', 'الكيس/الحقيبة.'),
  ('shopping-refund', 'shopping', 11, 'refund', 'They gave me a full ___ for the broken item.', 'استرداد المبلغ.'),
  ('shopping-exchange', 'shopping', 12, 'exchange', 'Can I ___ this for a different color?', 'يستبدل.'),
  ('shopping-customer', 'shopping', 13, 'customer', 'The ___ asked to speak with a manager.', 'الزبون.'),
  ('shopping-cashier', 'shopping', 14, 'cashier', 'The ___ scanned each item quickly.', 'أمين الصندوق.'),
  ('shopping-online', 'shopping', 15, 'online', 'I did most of my shopping ___ this year.', 'عبر الإنترنت.'),
  ('shopping-delivery', 'shopping', 16, 'delivery', '___ usually takes about three days.', 'التوصيل.'),
  ('shopping-order', 'shopping', 17, 'order', 'I placed an ___ for new shoes last night.', 'الطلب.'),
  ('shopping-budget', 'shopping', 18, 'budget', 'We''re trying to stay within our ___ this month.', 'الميزانية.'),
  ('shopping-afford', 'shopping', 19, 'afford', 'I don''t think we can ___ that right now.', 'يستطيع تحمل التكلفة.'),
  ('shopping-wallet', 'shopping', 20, 'wallet', 'He left his ___ at the checkout counter.', 'المحفظة.'),
  ('weather-sunny', 'weather', 1, 'sunny', 'It''s been ___ all week.', 'مشمس.'),
  ('weather-cloudy', 'weather', 2, 'cloudy', 'The sky turned ___ around noon.', 'غائم.'),
  ('weather-rainy', 'weather', 3, 'rainy', 'Bring an umbrella, it looks ___ today.', 'ممطر.'),
  ('weather-windy', 'weather', 4, 'windy', 'It was too ___ to fly a kite.', 'عاصف (رياح قوية).'),
  ('weather-storm', 'weather', 5, 'storm', 'A ___ knocked out the power last night.', 'العاصفة.'),
  ('weather-thunder', 'weather', 6, 'thunder', 'The kids got scared by the ___.', 'الرعد.'),
  ('weather-lightning', 'weather', 7, 'lightning', '___ lit up the whole sky for a second.', 'البرق.'),
  ('weather-snow', 'weather', 8, 'snow', 'The kids played in the ___ all afternoon.', 'الثلج.'),
  ('weather-fog', 'weather', 9, 'fog', 'Drive carefully, there''s ___ on the road.', 'الضباب.'),
  ('weather-temperature', 'weather', 10, 'temperature', 'The ___ dropped a lot after sunset.', 'درجة الحرارة.'),
  ('weather-degree', 'weather', 11, 'degree', 'It''s about thirty ___s outside right now.', 'درجة (قياس حرارة).'),
  ('weather-humid', 'weather', 12, 'humid', 'Summers here are hot and ___.', 'رطب.'),
  ('weather-freezing', 'weather', 13, 'freezing', 'It''s ___ out there, wear a coat.', 'شديد البرودة.'),
  ('weather-forecast', 'weather', 14, 'forecast', 'The ___ says it''ll rain tomorrow.', 'توقعات الطقس.'),
  ('weather-umbrella', 'weather', 15, 'umbrella', 'I forgot my ___ at the office again.', 'المظلة.'),
  ('weather-season', 'weather', 16, 'season', 'Autumn is my favorite ___.', 'الفصل (فصول السنة).'),
  ('weather-climate', 'weather', 17, 'climate', 'The ___ here is dry most of the year.', 'المناخ.'),
  ('weather-breeze', 'weather', 18, 'breeze', 'A cool ___ came in through the window.', 'النسيم.'),
  ('weather-flood', 'weather', 19, 'flood', 'Heavy rain caused a ___ downtown.', 'الفيضان.'),
  ('weather-drought', 'weather', 20, 'drought', 'The region has struggled with ___ for years.', 'الجفاف.'),
  ('work-job', 'work', 1, 'job', 'She just started a new ___ this week.', 'الوظيفة.'),
  ('work-office', 'work', 2, 'office', 'He spends most of his day at the ___.', 'المكتب.'),
  ('work-boss', 'work', 3, 'boss', 'My ___ asked me to finish the report today.', 'المدير/الرئيس بالعمل.'),
  ('work-colleague', 'work', 4, 'colleague', 'I grabbed lunch with a ___ from work.', 'الزميل.'),
  ('work-meeting', 'work', 5, 'meeting', 'We have a team ___ at ten.', 'الاجتماع.'),
  ('work-deadline', 'work', 6, 'deadline', 'The ___ for this project is Friday.', 'الموعد النهائي.'),
  ('work-salary', 'work', 7, 'salary', 'Her ___ went up after the promotion.', 'الراتب.'),
  ('work-interview', 'work', 8, 'interview', 'He has a job ___ tomorrow morning.', 'المقابلة (وظيفية).'),
  ('work-resume', 'work', 9, 'resume', 'She updated her ___ before applying.', 'السيرة الذاتية.'),
  ('work-hire', 'work', 10, 'hire', 'The company plans to ___ five more people.', 'يوظّف.'),
  ('work-fire', 'work', 11, 'fire', 'They had to ___ him after the incident.', 'يفصل من العمل.'),
  ('work-promotion', 'work', 12, 'promotion', 'He got a ___ after two years there.', 'الترقية.'),
  ('work-schedule', 'work', 13, 'schedule', 'Can you check your ___ for next week?', 'الجدول الزمني.'),
  ('work-task', 'work', 14, 'task', 'I still have three ___s left today.', 'المهمة.'),
  ('work-project', 'work', 15, 'project', 'We''re behind schedule on this ___.', 'المشروع.'),
  ('work-client', 'work', 16, 'client', 'The ___ asked for a few changes.', 'العميل (بالأعمال).'),
  ('work-email', 'work', 17, 'email', 'I''ll send you an ___ with the details.', 'البريد الإلكتروني.'),
  ('work-overtime', 'work', 18, 'overtime', 'He worked ___ to finish the report.', 'العمل الإضافي.'),
  ('work-resign', 'work', 19, 'resign', 'She decided to ___ at the end of the month.', 'يستقيل.'),
  ('work-teamwork', 'work', 20, 'teamwork', 'Good ___ made the project finish early.', 'العمل الجماعي.'),
  ('environment-environment', 'environment', 1, 'environment', 'We need to protect the ___ for future generations.', 'البيئة.'),
  ('environment-pollution', 'environment', 2, 'pollution', 'Air ___ is getting worse in big cities.', 'التلوث.'),
  ('environment-climate', 'environment', 3, 'climate', 'Scientists warn that the ___ is changing quickly.', 'المناخ.'),
  ('environment-recycle', 'environment', 4, 'recycle', 'We ___ paper and plastic at home.', 'يعيد التدوير.'),
  ('environment-plastic', 'environment', 5, 'plastic', 'This store stopped using ___ bags last year.', 'البلاستيك.'),
  ('environment-waste', 'environment', 6, 'waste', 'The factory produces a lot of ___.', 'النفايات.'),
  ('environment-energy', 'environment', 7, 'energy', 'Solar panels turn sunlight into ___.', 'الطاقة.'),
  ('environment-renewable', 'environment', 8, 'renewable', 'Wind is a ___ source of energy.', 'متجدد.'),
  ('environment-oil', 'environment', 9, 'oil', 'Cars that run on ___ produce more pollution.', 'النفط.'),
  ('environment-emission', 'environment', 10, 'emission', 'New laws aim to cut carbon ___s.', 'الانبعاثات.'),
  ('environment-forest', 'environment', 11, 'forest', 'A large ___ was destroyed by the fire.', 'الغابة.'),
  ('environment-species', 'environment', 12, 'species', 'This ___ only lives in one part of the world.', 'النوع (كائن حي).'),
  ('environment-extinct', 'environment', 13, 'extinct', 'That bird has been ___ for decades.', 'منقرض.'),
  ('environment-drought', 'environment', 14, 'drought', 'The ___ affected crops across the region.', 'الجفاف.'),
  ('environment-sustainable', 'environment', 15, 'sustainable', 'The company switched to more ___ packaging.', 'مستدام.'),
  ('environment-conservation', 'environment', 16, 'conservation', 'The park focuses on wildlife ___.', 'الحفاظ (على البيئة).'),
  ('environment-ecosystem', 'environment', 17, 'ecosystem', 'Removing one species can harm the whole ___.', 'النظام البيئي.'),
  ('environment-carbon', 'environment', 18, 'carbon', 'Flights add a lot of ___ to the air.', 'الكربون.'),
  ('environment-glacier', 'environment', 19, 'glacier', 'The ___ has shrunk noticeably in ten years.', 'النهر الجليدي.'),
  ('environment-awareness', 'environment', 20, 'awareness', 'The campaign raised ___ about ocean pollution.', 'الوعي/التوعية.'),
  ('education-university', 'education', 1, 'university', 'She''s studying medicine at ___.', 'الجامعة.'),
  ('education-degree', 'education', 2, 'degree', 'He earned his ___ after four years.', 'الشهادة الجامعية.'),
  ('education-scholarship', 'education', 3, 'scholarship', 'She received a full ___ to study abroad.', 'المنحة الدراسية.'),
  ('education-exam', 'education', 4, 'exam', 'The final ___ is next Monday.', 'الامتحان.'),
  ('education-grade', 'education', 5, 'grade', 'He got a good ___ on his essay.', 'الدرجة/العلامة.'),
  ('education-lecture', 'education', 6, 'lecture', 'The professor''s ___ ran twenty minutes late.', 'المحاضرة.'),
  ('education-classroom', 'education', 7, 'classroom', 'Our ___ was too small for thirty students.', 'الصف الدراسي.'),
  ('education-curriculum', 'education', 8, 'curriculum', 'The school updated its ___ this year.', 'المنهج الدراسي.'),
  ('education-assignment', 'education', 9, 'assignment', 'I still need to finish my history ___.', 'الواجب الدراسي.'),
  ('education-graduate', 'education', 10, 'graduate', 'She''ll ___ from college next spring.', 'يتخرج.'),
  ('education-tuition', 'education', 11, 'tuition', '___ at that university is very high.', 'الرسوم الدراسية.'),
  ('education-major', 'education', 12, 'major', 'His ___ is computer science.', 'التخصص الجامعي.'),
  ('education-semester', 'education', 13, 'semester', 'This ___ has been busier than the last.', 'الفصل الدراسي.'),
  ('education-professor', 'education', 14, 'professor', 'The ___ answered every question patiently.', 'الأستاذ الجامعي.'),
  ('education-research', 'education', 15, 'research', 'Her ___ focuses on renewable energy.', 'البحث العلمي.'),
  ('education-skill', 'education', 16, 'skill', 'Public speaking is a useful ___ to have.', 'المهارة.'),
  ('education-knowledge', 'education', 17, 'knowledge', 'Reading is a great way to gain ___.', 'المعرفة.'),
  ('education-literacy', 'education', 18, 'literacy', 'The program aims to improve adult ___.', 'محو الأمية.'),
  ('education-discipline', 'education', 19, 'discipline', 'It takes ___ to study every day after work.', 'الانضباط.'),
  ('education-mentor', 'education', 20, 'mentor', 'Her ___ helped her plan her whole career.', 'المرشد/الموجّه.'),
  ('media-news', 'media', 1, 'news', 'Did you see the ___ this morning?', 'الأخبار.'),
  ('media-journalist', 'media', 2, 'journalist', 'The ___ interviewed three witnesses at the scene.', 'الصحفي.'),
  ('media-article', 'media', 3, 'article', 'She wrote an ___ about local schools.', 'المقال.'),
  ('media-headline', 'media', 4, 'headline', 'The ___ caught everyone''s attention right away.', 'العنوان الرئيسي (خبر).'),
  ('media-broadcast', 'media', 5, 'broadcast', 'The event was ___ live on national TV.', 'البث (المباشر).'),
  ('media-channel', 'media', 6, 'channel', 'He switched to a different news ___.', 'القناة.'),
  ('media-interview', 'media', 7, 'interview', 'The actor gave an ___ about her new film.', 'المقابلة (إعلامية).'),
  ('media-source', 'media', 8, 'source', 'A reliable ___ confirmed the story.', 'المصدر.'),
  ('media-audience', 'media', 9, 'audience', 'The show has a huge young ___.', 'الجمهور.'),
  ('media-platform', 'media', 10, 'platform', 'The app became a popular ___ for creators.', 'المنصة.'),
  ('media-influencer', 'media', 11, 'influencer', 'An ___ promoted the product online.', 'المؤثر (سوشيال ميديا).'),
  ('media-content', 'media', 12, 'content', 'She posts new ___ every single day.', 'المحتوى.'),
  ('media-viral', 'media', 13, 'viral', 'The video went ___ within a few hours.', 'منتشر بسرعة.'),
  ('media-comment', 'media', 14, 'comment', 'He left a kind ___ under her post.', 'التعليق.'),
  ('media-subscribe', 'media', 15, 'subscribe', '___ to the channel for weekly updates.', 'يشترك (بمتابعة قناة).'),
  ('media-censorship', 'media', 16, 'censorship', 'The report criticized government ___.', 'الرقابة/الحجب.'),
  ('media-bias', 'media', 17, 'bias', 'Readers accused the paper of political ___.', 'التحيّز.'),
  ('media-rumor', 'media', 18, 'rumor', 'Social media makes a ___ spread faster.', 'الشائعة.'),
  ('media-privacy', 'media', 19, 'privacy', 'People worry about their online ___.', 'الخصوصية.'),
  ('media-coverage', 'media', 20, 'coverage', 'The election got heavy media ___.', 'التغطية (الإعلامية).') on conflict (id) do nothing;

commit;
