-- Start Simple redesign: lesson descriptions, level preview sentences, and
-- the rewritten normal-mode content library (12 lessons x 9 sentences,
-- replacing the previous 8 lessons x 12 sentences).
--
-- Generated from the same TypeScript source the app reads locally
-- (src/data/lessons/normal.ts, src/data/units.ts) by a one-off script
-- mirroring scripts/generate-content-seed.ts's approach: one authored
-- copy of the content, not two hand-kept-in-sync copies.
--
-- Idempotent and additive-only for everything except the 12 known
-- normal-mode lesson ids listed below: upserts key on stable ids (levels:
-- mode+index; lessons/sentences: their existing slug-style id), and the
-- stale-sentence cleanup near the end only ever deletes rows beyond the
-- new 9-sentence count for those same 12 ids. Stories, Conversation,
-- profiles, progress, XP, streaks, and subscriptions are never referenced
-- or touched anywhere in this file.
--
-- Wrapped in an explicit transaction: if any statement fails, everything
-- in this file rolls back together and the database is left exactly as it
-- was before this ran. Run the verification queries at the bottom of this
-- file separately, after this migration commits, to confirm the result.
begin;

alter table lessons
  add column if not exists description text,
  add column if not exists description_ar text;

alter table levels
  add column if not exists preview_sentences jsonb not null default '[]'::jsonb;

-- Levels: renamed to Beginner/Intermediate/Advanced, with Start Simple previews
insert into levels (mode, index, title, title_ar, preview_sentences) values ('normal', 1, 'Beginner — A1', 'مبتدئ — A1', '[{"en":"My phone died right before my bus arrived.","ar":"توقف هاتفي عن العمل قبل وصول الحافلة مباشرة."},{"en":"I ordered coffee, but they gave me tea.","ar":"طلبت قهوة، لكنهم أعطوني شايًا."},{"en":"She found ten dollars on the street.","ar":"وجدت عشرة دولارات في الشارع."},{"en":"We waited an hour for a table.","ar":"انتظرنا ساعة للحصول على طاولة."},{"en":"He forgot his password again.","ar":"نسي كلمة المرور مرة أخرى."}]'::jsonb) on conflict (mode, index) do update set title = excluded.title, title_ar = excluded.title_ar, preview_sentences = excluded.preview_sentences;
insert into levels (mode, index, title, title_ar, preview_sentences) values ('normal', 2, 'Intermediate — A2-B1', 'متوسط — A2-B1', '[{"en":"I almost missed my flight because of the traffic.","ar":"كدت أفوت رحلتي بسبب الازدحام المروري."},{"en":"She''s been learning English for six months now.","ar":"إنها تتعلم الإنجليزية منذ ستة أشهر الآن."},{"en":"We couldn''t agree on where to go for dinner.","ar":"لم نستطع الاتفاق على أين نذهب لتناول العشاء."},{"en":"He quit his job to travel for a year.","ar":"استقال من وظيفته ليسافر لمدة عام."},{"en":"I''ve started saving money instead of spending it all.","ar":"بدأت أدخر المال بدلاً من إنفاقه كله."}]'::jsonb) on conflict (mode, index) do update set title = excluded.title, title_ar = excluded.title_ar, preview_sentences = excluded.preview_sentences;
insert into levels (mode, index, title, title_ar, preview_sentences) values ('normal', 3, 'Advanced — B2+', 'متقدم — B2+', '[{"en":"I used to dread public speaking, but I''ve slowly gotten the hang of it.","ar":"كنت أخشى التحدث أمام الجمهور، لكنني أتقنت الأمر تدريجيًا."},{"en":"Looking back, quitting that job was the best decision I ever made.","ar":"بالنظر إلى الماضي، كانت الاستقالة من تلك الوظيفة أفضل قرار اتخذته في حياتي."},{"en":"She has a knack for turning awkward situations into something funny.","ar":"لديها موهبة في تحويل المواقف المحرجة إلى شيء مضحك."},{"en":"The plan sounded great on paper, but it fell apart within a week.","ar":"بدت الخطة رائعة على الورق، لكنها انهارت خلال أسبوع."},{"en":"He''s not lazy, exactly — he just prioritizes things differently than most people.","ar":"إنه ليس كسولًا بالضبط، بل يرتب أولوياته بشكل مختلف عن معظم الناس."}]'::jsonb) on conflict (mode, index) do update set title = excluded.title, title_ar = excluded.title_ar, preview_sentences = excluded.preview_sentences;

-- Lessons: full replacement of the normal-mode library, by id.
--
-- The lessons table has a unique constraint on (mode, order_index). The
-- live database already has the pre-redesign rows normal-1..normal-8 at
-- order_index 1-8, and this migration both reassigns order_index for those
-- and introduces normal-9..normal-12 at order_index values an old row may
-- still be sitting on (for example normal-9 below targets order_index 8,
-- which the old normal-8 row occupies until its own upsert further down).
-- Upserting one lesson at a time in target order collides with a
-- not-yet-moved sibling row and raises error 23505.
--
-- Fix: move exactly the 12 lesson ids this migration owns out of the
-- order_index range it is about to assign (1 through 12), before touching
-- any of them, matched by id, not by an order_index range and not by a
-- bare mode filter. This is deliberately narrower than either option: it
-- can never move a lesson this migration does not know about (for example
-- one created later through the admin CMS), and it correctly moves all 12
-- target ids regardless of whatever order_index each currently holds,
-- including normal-9 through normal-12 if an earlier partial attempt
-- already created them. Once every one of these 12 rows is parked at 1000
-- or above, none of the order_index values 1 through 12 are held by
-- anyone, so the upserts below can assign them in any order with zero
-- collision risk, including on a rerun after a failed attempt, in
-- whatever state that attempt left things in, committed or not.
update lessons
set order_index = order_index + 1000
where mode = 'normal'
  and id in (
    'normal-1', 'normal-2', 'normal-3', 'normal-4',
    'normal-5', 'normal-6', 'normal-7', 'normal-8',
    'normal-9', 'normal-10', 'normal-11', 'normal-12'
  );

insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-1', 'normal', (select id from levels where mode = 'normal' and index = 1), 1, 'The Wrong Order', 'الطلب الخطأ', 'A quick coffee run turns into a small mix-up at the counter.', 'تتحول رحلة سريعة لشراء القهوة إلى ارتباك بسيط عند الطاولة.', true, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-2', 'normal', (select id from levels where mode = 'normal' and index = 1), 2, 'The Missed Bus', 'الحافلة الفائتة', 'A slow morning turns into a race against the clock.', 'يتحول صباح بطيء إلى سباق مع الوقت.', true, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-3', 'normal', (select id from levels where mode = 'normal' and index = 1), 3, 'A Message from a Friend', 'رسالة من صديق', 'An old friend reaches out, and old plans suddenly feel new again.', 'يتواصل صديق قديم، وفجأة تبدو الخطط القديمة جديدة من جديد.', true, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-4', 'normal', (select id from levels where mode = 'normal' and index = 1), 4, 'The Broken Phone', 'الهاتف المكسور', 'A cracked screen sends one Saturday afternoon completely off plan.', 'تُحوّل شاشة مكسورة بعد ظهر يوم سبت عن مسارها تماماً.', true, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-5', 'normal', (select id from levels where mode = 'normal' and index = 2), 5, 'A Long Layover', 'توقف طويل', 'A delayed connection turns a routine trip into an unplanned adventure.', 'تتحول رحلة اعتيادية إلى مغامرة غير مخطط لها بسبب رحلة متأخرة.', true, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-6', 'normal', (select id from levels where mode = 'normal' and index = 2), 6, 'Changing Habits', 'تغيير العادات', 'One small change at breakfast quietly reshapes an entire routine.', 'يُعيد تغيير صغير في الفطور تشكيل روتين كامل بهدوء.', true, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-7', 'normal', (select id from levels where mode = 'normal' and index = 2), 7, 'The Roommate Problem', 'مشكلة زميل السكن', 'A messy kitchen turns into an awkward conversation neither roommate wants to start.', 'يتحول مطبخ فوضوي إلى حديث محرج لا يرغب أي من الزميلين في بدئه.', false, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-9', 'normal', (select id from levels where mode = 'normal' and index = 2), 8, 'Online Shopping Gone Wrong', 'التسوق الإلكتروني الذي ساء', 'A tempting online deal turns into a lesson about reading the fine print.', 'يتحول عرض إلكتروني مغرٍ إلى درس في قراءة التفاصيل الدقيقة.', false, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-8', 'normal', (select id from levels where mode = 'normal' and index = 3), 9, 'The Interview That Almost Wasn''t', 'المقابلة التي كادت ألا تحدث', 'A canceled interview forces an unexpected reflection on what he really wants.', 'يدفعه إلغاء مقابلة إلى تأمل غير متوقع فيما يريده فعلاً.', false, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-10', 'normal', (select id from levels where mode = 'normal' and index = 3), 10, 'A Falling Out With a Friend', 'خلاف مع صديق', 'One offhand comment quietly ends a friendship neither of them saw coming.', 'يُنهي تعليق عابر صداقة لم يتوقعها أي منهما.', false, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-11', 'normal', (select id from levels where mode = 'normal' and index = 3), 11, 'The Side Project', 'المشروع الجانبي', 'A weekend hobby quietly grows into something he can no longer ignore.', 'تنمو هواية نهاية الأسبوع بهدوء لتصبح شيئاً لا يمكنه تجاهله بعد الآن.', false, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();
insert into lessons (id, mode, level_id, order_index, title, title_ar, description, description_ar, is_free, status, updated_at) values ('normal-12', 'normal', (select id from levels where mode = 'normal' and index = 3), 12, 'Moving Abroad, Sort Of', 'الانتقال للخارج، نوعاً ما', 'A one-year visa turns an easy adventure into a much harder decision.', 'تُحوّل تأشيرة لمدة عام مغامرة سهلة إلى قرار أصعب بكثير.', false, 'published', now()) on conflict (id) do update set level_id = excluded.level_id, order_index = excluded.order_index, title = excluded.title, title_ar = excluded.title_ar, description = excluded.description, description_ar = excluded.description_ar, is_free = excluded.is_free, status = excluded.status, updated_at = now();

-- Sentences (including word_translations, which the original seed migration predates)
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-1-s1', 'normal-1', 0, 'I walked into a small café near my office', 'دخلت مقهى صغيراً قرب مكتبي.', null, '[{"en":"I","ar":"أنا"},{"en":"walked","ar":"مشيت"},{"en":"into","ar":"إلى"},{"en":"a","ar":"واحد"},{"en":"small","ar":"صغير"},{"en":"café","ar":"مقهى"},{"en":"near","ar":"قرب"},{"en":"my","ar":"لي"},{"en":"office","ar":"مكتبي"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-1-s2', 'normal-1', 1, 'I ordered a black coffee and a sandwich', 'طلبت قهوة سوداء وشطيرة.', null, '[{"en":"I","ar":"أنا"},{"en":"ordered","ar":"طلبت"},{"en":"a","ar":"واحدة"},{"en":"black","ar":"سوداء"},{"en":"coffee","ar":"قهوة"},{"en":"and","ar":"و"},{"en":"a","ar":"واحدة"},{"en":"sandwich","ar":"شطيرة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-1-s3', 'normal-1', 2, 'The waiter brought me tea instead of coffee', 'أحضر لي النادل شاياً بدلاً من القهوة.', null, '[{"en":"The","ar":"الـ"},{"en":"waiter","ar":"النادل"},{"en":"brought","ar":"أحضر"},{"en":"me","ar":"لي"},{"en":"tea","ar":"شاي"},{"en":"instead","ar":"بدلاً"},{"en":"of","ar":"من"},{"en":"coffee","ar":"القهوة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-1-s4', 'normal-1', 3, 'I looked at the cup and felt confused', 'نظرت إلى الكوب وشعرت بالحيرة.', null, '[{"en":"I","ar":"أنا"},{"en":"looked","ar":"نظرت"},{"en":"at","ar":"إلى"},{"en":"the","ar":"الـ"},{"en":"cup","ar":"الكوب"},{"en":"and","ar":"و"},{"en":"felt","ar":"شعرت"},{"en":"confused","ar":"بالحيرة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-1-s5', 'normal-1', 4, 'Excuse me, this isn''t what I ordered', 'المعذرة، هذا ليس ما طلبته.', null, '[{"en":"Excuse","ar":"عذراً"},{"en":"me,","ar":"لي،"},{"en":"this","ar":"هذا"},{"en":"isn''t","ar":"ليس"},{"en":"what","ar":"ما"},{"en":"I","ar":"أنا"},{"en":"ordered","ar":"طلبته"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-1-s6', 'normal-1', 5, 'The waiter apologized and checked my order again', 'اعتذر النادل وتحقق من طلبي مرة أخرى.', null, '[{"en":"The","ar":"الـ"},{"en":"waiter","ar":"النادل"},{"en":"apologized","ar":"اعتذر"},{"en":"and","ar":"و"},{"en":"checked","ar":"تحقق"},{"en":"my","ar":"لي"},{"en":"order","ar":"الطلب"},{"en":"again","ar":"مرة أخرى"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-1-s7', 'normal-1', 6, 'He brought the right coffee a few minutes later', 'أحضر القهوة الصحيحة بعد بضع دقائق.', null, '[{"en":"He","ar":"هو"},{"en":"brought","ar":"أحضر"},{"en":"the","ar":"الـ"},{"en":"right","ar":"الصحيحة"},{"en":"coffee","ar":"القهوة"},{"en":"a","ar":"واحد"},{"en":"few","ar":"بضع"},{"en":"minutes","ar":"دقائق"},{"en":"later","ar":"لاحقاً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-1-s8', 'normal-1', 7, 'The sandwich, at least, was perfect', 'الشطيرة، على الأقل، كانت ممتازة.', null, '[{"en":"The","ar":"الـ"},{"en":"sandwich,","ar":"الشطيرة،"},{"en":"at","ar":"على"},{"en":"least,","ar":"الأقل،"},{"en":"was","ar":"كانت"},{"en":"perfect","ar":"ممتازة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-1-s9', 'normal-1', 8, 'I left a good tip and went back to work', 'تركت إكرامية جيدة وعدت إلى العمل.', null, '[{"en":"I","ar":"أنا"},{"en":"left","ar":"تركت"},{"en":"a","ar":"واحدة"},{"en":"good","ar":"جيدة"},{"en":"tip","ar":"إكرامية"},{"en":"and","ar":"و"},{"en":"went","ar":"عدت"},{"en":"back","ar":"رجوعاً"},{"en":"to","ar":"إلى"},{"en":"work","ar":"العمل"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-2-s1', 'normal-2', 0, 'I woke up ten minutes late this morning', 'استيقظت متأخراً عشر دقائق هذا الصباح.', null, '[{"en":"I","ar":"أنا"},{"en":"woke","ar":"استيقظت"},{"en":"up","ar":"فوق"},{"en":"ten","ar":"عشر"},{"en":"minutes","ar":"دقائق"},{"en":"late","ar":"متأخراً"},{"en":"this","ar":"هذا"},{"en":"morning","ar":"الصباح"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-2-s2', 'normal-2', 1, 'I got dressed as fast as I could', 'ارتديت ملابسي بأسرع ما يمكن.', null, '[{"en":"I","ar":"أنا"},{"en":"got","ar":"صرت"},{"en":"dressed","ar":"مرتدياً"},{"en":"as","ar":"بقدر"},{"en":"fast","ar":"سرعة"},{"en":"as","ar":"بقدر"},{"en":"I","ar":"أنا"},{"en":"could","ar":"أستطيع"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-2-s3', 'normal-2', 2, 'I ran to the bus stop across the street', 'ركضت إلى موقف الحافلة عبر الشارع.', null, '[{"en":"I","ar":"أنا"},{"en":"ran","ar":"ركضت"},{"en":"to","ar":"إلى"},{"en":"the","ar":"الـ"},{"en":"bus","ar":"الحافلة"},{"en":"stop","ar":"موقف"},{"en":"across","ar":"عبر"},{"en":"the","ar":"الـ"},{"en":"street","ar":"الشارع"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-2-s4', 'normal-2', 3, 'The bus was already pulling away', 'كانت الحافلة تتحرك بالفعل.', null, '[{"en":"The","ar":"الـ"},{"en":"bus","ar":"الحافلة"},{"en":"was","ar":"كانت"},{"en":"already","ar":"بالفعل"},{"en":"pulling","ar":"تتحرك"},{"en":"away","ar":"مبتعدة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-2-s5', 'normal-2', 4, 'I waved my hand, but the driver didn''t see me', 'لوّحت بيدي، لكن السائق لم يرني.', null, '[{"en":"I","ar":"أنا"},{"en":"waved","ar":"لوّحت"},{"en":"my","ar":"بيدي"},{"en":"hand,","ar":"يد،"},{"en":"but","ar":"لكن"},{"en":"the","ar":"الـ"},{"en":"driver","ar":"السائق"},{"en":"didn''t","ar":"لم"},{"en":"see","ar":"ير"},{"en":"me","ar":"ني"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-2-s6', 'normal-2', 5, 'I had to wait twenty minutes for the next one', 'اضطررت لانتظار عشرين دقيقة للحافلة التالية.', null, '[{"en":"I","ar":"أنا"},{"en":"had","ar":"اضطررت"},{"en":"to","ar":"أن"},{"en":"wait","ar":"أنتظر"},{"en":"twenty","ar":"عشرين"},{"en":"minutes","ar":"دقيقة"},{"en":"for","ar":"من أجل"},{"en":"the","ar":"الـ"},{"en":"next","ar":"التالية"},{"en":"one","ar":"الواحدة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-2-s7', 'normal-2', 6, 'I texted my manager that I would be late', 'راسلت مديري أنني سأتأخر.', null, '[{"en":"I","ar":"أنا"},{"en":"texted","ar":"راسلت"},{"en":"my","ar":"لي"},{"en":"manager","ar":"المدير"},{"en":"that","ar":"بأن"},{"en":"I","ar":"أنا"},{"en":"would","ar":"سوف"},{"en":"be","ar":"أكون"},{"en":"late","ar":"متأخراً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-2-s8', 'normal-2', 7, 'She told me not to worry about it', 'قالت لي ألا أقلق بشأن ذلك.', null, '[{"en":"She","ar":"هي"},{"en":"told","ar":"قالت"},{"en":"me","ar":"لي"},{"en":"not","ar":"ألا"},{"en":"to","ar":"أن"},{"en":"worry","ar":"أقلق"},{"en":"about","ar":"بشأن"},{"en":"it","ar":"ذلك"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-2-s9', 'normal-2', 8, 'I finally arrived at work only fifteen minutes late', 'وصلت أخيراً إلى العمل متأخراً بخمس عشرة دقيقة فقط.', null, '[{"en":"I","ar":"أنا"},{"en":"finally","ar":"أخيراً"},{"en":"arrived","ar":"وصلت"},{"en":"at","ar":"إلى"},{"en":"work","ar":"العمل"},{"en":"only","ar":"فقط"},{"en":"fifteen","ar":"بخمس عشرة"},{"en":"minutes","ar":"دقيقة"},{"en":"late","ar":"متأخراً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-3-s1', 'normal-3', 0, 'My phone buzzed with a message from an old friend', 'رنّ هاتفي برسالة من صديق قديم.', null, '[{"en":"My","ar":"لي"},{"en":"phone","ar":"هاتف"},{"en":"buzzed","ar":"رنّ"},{"en":"with","ar":"بـ"},{"en":"a","ar":"واحدة"},{"en":"message","ar":"رسالة"},{"en":"from","ar":"من"},{"en":"an","ar":"واحد"},{"en":"old","ar":"قديم"},{"en":"friend","ar":"صديق"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-3-s2', 'normal-3', 1, 'We hadn''t spoken in almost two years', 'لم نتحدث منذ ما يقارب عامين.', null, '[{"en":"We","ar":"نحن"},{"en":"hadn''t","ar":"لم"},{"en":"spoken","ar":"نتحدث"},{"en":"in","ar":"منذ"},{"en":"almost","ar":"ما يقارب"},{"en":"two","ar":"عامين"},{"en":"years","ar":"سنوات"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-3-s3', 'normal-3', 2, 'He said he was visiting my city next week', 'قال إنه سيزور مدينتي الأسبوع المقبل.', null, '[{"en":"He","ar":"هو"},{"en":"said","ar":"قال"},{"en":"he","ar":"إنه"},{"en":"was","ar":"كان"},{"en":"visiting","ar":"سيزور"},{"en":"my","ar":"لي"},{"en":"city","ar":"مدينتي"},{"en":"next","ar":"القادم"},{"en":"week","ar":"الأسبوع"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-3-s4', 'normal-3', 3, 'I felt excited and a little nervous', 'شعرت بالحماس وبعض التوتر.', null, '[{"en":"I","ar":"أنا"},{"en":"felt","ar":"شعرت"},{"en":"excited","ar":"بالحماس"},{"en":"and","ar":"و"},{"en":"a","ar":"بعض"},{"en":"little","ar":"قليل"},{"en":"nervous","ar":"التوتر"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-3-s5', 'normal-3', 4, 'We agreed to meet at our favorite restaurant', 'اتفقنا على اللقاء في مطعمنا المفضل.', null, '[{"en":"We","ar":"نحن"},{"en":"agreed","ar":"اتفقنا"},{"en":"to","ar":"أن"},{"en":"meet","ar":"نلتقي"},{"en":"at","ar":"في"},{"en":"our","ar":"لنا"},{"en":"favorite","ar":"المفضل"},{"en":"restaurant","ar":"المطعم"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-3-s6', 'normal-3', 5, 'I arrived early and picked a table by the window', 'وصلت مبكراً واخترت طاولة بجانب النافذة.', null, '[{"en":"I","ar":"أنا"},{"en":"arrived","ar":"وصلت"},{"en":"early","ar":"مبكراً"},{"en":"and","ar":"و"},{"en":"picked","ar":"اخترت"},{"en":"a","ar":"واحدة"},{"en":"table","ar":"طاولة"},{"en":"by","ar":"بجانب"},{"en":"the","ar":"الـ"},{"en":"window","ar":"النافذة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-3-s7', 'normal-3', 6, 'When he walked in, we both started laughing', 'عندما دخل، بدأنا كلانا بالضحك.', null, '[{"en":"When","ar":"عندما"},{"en":"he","ar":"هو"},{"en":"walked","ar":"دخل"},{"en":"in,","ar":"بالداخل،"},{"en":"we","ar":"نحن"},{"en":"both","ar":"كلانا"},{"en":"started","ar":"بدأنا"},{"en":"laughing","ar":"بالضحك"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-3-s8', 'normal-3', 7, 'It felt like no time had passed at all', 'شعرنا وكأن الزمن لم يمر على الإطلاق.', null, '[{"en":"It","ar":"ذلك"},{"en":"felt","ar":"بدا"},{"en":"like","ar":"وكأن"},{"en":"no","ar":"لا"},{"en":"time","ar":"وقت"},{"en":"had","ar":"قد"},{"en":"passed","ar":"مر"},{"en":"at","ar":"على"},{"en":"all","ar":"الإطلاق"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-3-s9', 'normal-3', 8, 'We stayed there talking for almost three hours', 'بقينا هناك نتحدث لما يقارب ثلاث ساعات.', null, '[{"en":"We","ar":"نحن"},{"en":"stayed","ar":"بقينا"},{"en":"there","ar":"هناك"},{"en":"talking","ar":"نتحدث"},{"en":"for","ar":"لمدة"},{"en":"almost","ar":"ما يقارب"},{"en":"three","ar":"ثلاث"},{"en":"hours","ar":"ساعات"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-4-s1', 'normal-4', 0, 'My phone slipped out of my hand this morning', 'انزلق هاتفي من يدي هذا الصباح.', null, '[{"en":"My","ar":"لي"},{"en":"phone","ar":"هاتف"},{"en":"slipped","ar":"انزلق"},{"en":"out","ar":"خارجاً"},{"en":"of","ar":"من"},{"en":"my","ar":"لي"},{"en":"hand","ar":"يدي"},{"en":"this","ar":"هذا"},{"en":"morning","ar":"الصباح"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-4-s2', 'normal-4', 1, 'The screen cracked into three pieces', 'تشققت الشاشة إلى ثلاث قطع.', null, '[{"en":"The","ar":"الـ"},{"en":"screen","ar":"الشاشة"},{"en":"cracked","ar":"تشققت"},{"en":"into","ar":"إلى"},{"en":"three","ar":"ثلاث"},{"en":"pieces","ar":"قطع"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-4-s3', 'normal-4', 2, 'I still couldn''t read any of the messages', 'ما زلت غير قادر على قراءة أي من الرسائل.', null, '[{"en":"I","ar":"أنا"},{"en":"still","ar":"ما زلت"},{"en":"couldn''t","ar":"غير قادر"},{"en":"read","ar":"أقرأ"},{"en":"any","ar":"أي"},{"en":"of","ar":"من"},{"en":"the","ar":"الـ"},{"en":"messages","ar":"الرسائل"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-4-s4', 'normal-4', 3, 'I searched online for a repair shop nearby', 'بحثت على الإنترنت عن محل إصلاح قريب.', null, '[{"en":"I","ar":"أنا"},{"en":"searched","ar":"بحثت"},{"en":"online","ar":"على الإنترنت"},{"en":"for","ar":"عن"},{"en":"a","ar":"واحد"},{"en":"repair","ar":"إصلاح"},{"en":"shop","ar":"محل"},{"en":"nearby","ar":"قريب"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-4-s5', 'normal-4', 4, 'The nearest one was a short walk away', 'كان الأقرب على بُعد مسافة قصيرة سيراً.', null, '[{"en":"The","ar":"الـ"},{"en":"nearest","ar":"الأقرب"},{"en":"one","ar":"الواحد"},{"en":"was","ar":"كان"},{"en":"a","ar":"مسافة"},{"en":"short","ar":"قصيرة"},{"en":"walk","ar":"سيراً"},{"en":"away","ar":"بعيداً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-4-s6', 'normal-4', 5, 'The technician said it would take one hour', 'قال الفني إن الأمر سيستغرق ساعة واحدة.', null, '[{"en":"The","ar":"الـ"},{"en":"technician","ar":"الفني"},{"en":"said","ar":"قال"},{"en":"it","ar":"إنه"},{"en":"would","ar":"سوف"},{"en":"take","ar":"يستغرق"},{"en":"one","ar":"واحدة"},{"en":"hour","ar":"ساعة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-4-s7', 'normal-4', 6, 'I sat in a nearby park and waited', 'جلست في حديقة قريبة وانتظرت.', null, '[{"en":"I","ar":"أنا"},{"en":"sat","ar":"جلست"},{"en":"in","ar":"في"},{"en":"a","ar":"واحدة"},{"en":"nearby","ar":"قريبة"},{"en":"park","ar":"حديقة"},{"en":"and","ar":"و"},{"en":"waited","ar":"انتظرت"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-4-s8', 'normal-4', 7, 'He called to say the screen was fixed', 'اتصل ليخبرني أن الشاشة أُصلحت.', null, '[{"en":"He","ar":"هو"},{"en":"called","ar":"اتصل"},{"en":"to","ar":"لـ"},{"en":"say","ar":"يقول"},{"en":"the","ar":"الـ"},{"en":"screen","ar":"الشاشة"},{"en":"was","ar":"كانت"},{"en":"fixed","ar":"مُصلحة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-4-s9', 'normal-4', 8, 'It looked brand new when I picked it up', 'بدت جديدة تماماً عندما استلمتها.', null, '[{"en":"It","ar":"هي"},{"en":"looked","ar":"بدت"},{"en":"brand","ar":"تماماً"},{"en":"new","ar":"جديدة"},{"en":"when","ar":"عندما"},{"en":"I","ar":"أنا"},{"en":"picked","ar":"استلمت"},{"en":"it","ar":"إياها"},{"en":"up","ar":"فوق"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-5-s1', 'normal-5', 0, 'My connecting flight was delayed by four hours', 'تأخرت رحلتي المتصلة أربع ساعات.', null, '[{"en":"My","ar":"لي"},{"en":"connecting","ar":"المتصلة"},{"en":"flight","ar":"رحلة"},{"en":"was","ar":"كانت"},{"en":"delayed","ar":"متأخرة"},{"en":"by","ar":"بمقدار"},{"en":"four","ar":"أربع"},{"en":"hours","ar":"ساعات"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-5-s2', 'normal-5', 1, 'I had never been to that city before', 'لم أزر تلك المدينة من قبل.', null, '[{"en":"I","ar":"أنا"},{"en":"had","ar":"لم"},{"en":"never","ar":"أبداً"},{"en":"been","ar":"أزر"},{"en":"to","ar":"إلى"},{"en":"that","ar":"تلك"},{"en":"city","ar":"المدينة"},{"en":"before","ar":"من قبل"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-5-s3', 'normal-5', 2, 'Instead of waiting at the gate, I decided to explore', 'بدلاً من الانتظار عند البوابة، قررت الاستكشاف.', null, '[{"en":"Instead","ar":"بدلاً"},{"en":"of","ar":"من"},{"en":"waiting","ar":"الانتظار"},{"en":"at","ar":"عند"},{"en":"the","ar":"الـ"},{"en":"gate,","ar":"البوابة،"},{"en":"I","ar":"أنا"},{"en":"decided","ar":"قررت"},{"en":"to","ar":"أن"},{"en":"explore","ar":"أستكشف"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-5-s4', 'normal-5', 3, 'I found a small café just outside the airport', 'وجدت مقهى صغيراً خارج المطار مباشرة.', null, '[{"en":"I","ar":"أنا"},{"en":"found","ar":"وجدت"},{"en":"a","ar":"واحداً"},{"en":"small","ar":"صغيراً"},{"en":"café","ar":"مقهى"},{"en":"just","ar":"مباشرة"},{"en":"outside","ar":"خارج"},{"en":"the","ar":"الـ"},{"en":"airport","ar":"المطار"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-5-s5', 'normal-5', 4, 'The owner recommended a local dish I had never tried', 'أوصاني صاحب المقهى بطبق محلي لم أجربه من قبل.', null, '[{"en":"The","ar":"الـ"},{"en":"owner","ar":"صاحب المقهى"},{"en":"recommended","ar":"أوصى"},{"en":"a","ar":"واحداً"},{"en":"local","ar":"محلياً"},{"en":"dish","ar":"طبقاً"},{"en":"I","ar":"أنا"},{"en":"had","ar":"لم"},{"en":"never","ar":"أبداً"},{"en":"tried","ar":"أجربه"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-5-s6', 'normal-5', 5, 'It turned out to be one of the best meals I''ve had', 'تبيّن أنها من ألذ الوجبات التي تناولتها.', null, '[{"en":"It","ar":"هي"},{"en":"turned","ar":"تبيّن"},{"en":"out","ar":"أنها"},{"en":"to","ar":"أن"},{"en":"be","ar":"تكون"},{"en":"one","ar":"واحدة"},{"en":"of","ar":"من"},{"en":"the","ar":"الـ"},{"en":"best","ar":"ألذ"},{"en":"meals","ar":"الوجبات"},{"en":"I''ve","ar":"التي"},{"en":"had","ar":"تناولتها"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-5-s7', 'normal-5', 6, 'I lost track of time chatting with the locals', 'نسيت الوقت وأنا أتحدث مع السكان المحليين.', null, '[{"en":"I","ar":"أنا"},{"en":"lost","ar":"نسيت"},{"en":"track","ar":"تتبع"},{"en":"of","ar":"الـ"},{"en":"time","ar":"الوقت"},{"en":"chatting","ar":"وأنا أتحدث"},{"en":"with","ar":"مع"},{"en":"the","ar":"الـ"},{"en":"locals","ar":"السكان المحليين"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-5-s8', 'normal-5', 7, 'I had to rush back to catch my flight', 'اضطررت للعودة مسرعاً للحاق برحلتي.', null, '[{"en":"I","ar":"أنا"},{"en":"had","ar":"اضطررت"},{"en":"to","ar":"أن"},{"en":"rush","ar":"أسرع"},{"en":"back","ar":"بالعودة"},{"en":"to","ar":"لـ"},{"en":"catch","ar":"ألحق"},{"en":"my","ar":"بـ"},{"en":"flight","ar":"رحلتي"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-5-s9', 'normal-5', 8, 'That short layover ended up being the highlight of my trip', 'انتهى ذلك التوقف القصير ليكون أبرز ما في رحلتي.', null, '[{"en":"That","ar":"ذلك"},{"en":"short","ar":"القصير"},{"en":"layover","ar":"التوقف"},{"en":"ended","ar":"انتهى"},{"en":"up","ar":"به"},{"en":"being","ar":"ليكون"},{"en":"the","ar":"الـ"},{"en":"highlight","ar":"أبرز ما"},{"en":"of","ar":"في"},{"en":"my","ar":"لي"},{"en":"trip","ar":"رحلتي"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-6-s1', 'normal-6', 0, 'I used to skip breakfast almost every day', 'كنت أتجاهل الفطور تقريباً كل يوم.', null, '[{"en":"I","ar":"أنا"},{"en":"used","ar":"اعتدت"},{"en":"to","ar":"أن"},{"en":"skip","ar":"أتجاهل"},{"en":"breakfast","ar":"الفطور"},{"en":"almost","ar":"تقريباً"},{"en":"every","ar":"كل"},{"en":"day","ar":"يوم"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-6-s2', 'normal-6', 1, 'A friend convinced me to try eating earlier', 'أقنعني صديق بتجربة الأكل مبكراً.', null, '[{"en":"A","ar":"واحد"},{"en":"friend","ar":"صديق"},{"en":"convinced","ar":"أقنعني"},{"en":"me","ar":"بـ"},{"en":"to","ar":"أن"},{"en":"try","ar":"أجرب"},{"en":"eating","ar":"الأكل"},{"en":"earlier","ar":"مبكراً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-6-s3', 'normal-6', 2, 'At first, I really struggled to wake up on time', 'في البداية، واجهت صعوبة حقيقية في الاستيقاظ في الوقت المحدد.', null, '[{"en":"At","ar":"في"},{"en":"first,","ar":"البداية،"},{"en":"I","ar":"أنا"},{"en":"really","ar":"حقاً"},{"en":"struggled","ar":"واجهت صعوبة"},{"en":"to","ar":"أن"},{"en":"wake","ar":"أستيقظ"},{"en":"up","ar":"فوق"},{"en":"on","ar":"في"},{"en":"time","ar":"الوقت المحدد"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-6-s4', 'normal-6', 3, 'After a week, I started noticing more energy during the day', 'بعد أسبوع، بدأت ألاحظ طاقة أكبر خلال اليوم.', null, '[{"en":"After","ar":"بعد"},{"en":"a","ar":"واحد"},{"en":"week,","ar":"أسبوع،"},{"en":"I","ar":"أنا"},{"en":"started","ar":"بدأت"},{"en":"noticing","ar":"ألاحظ"},{"en":"more","ar":"أكثر"},{"en":"energy","ar":"طاقة"},{"en":"during","ar":"خلال"},{"en":"the","ar":"الـ"},{"en":"day","ar":"اليوم"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-6-s5', 'normal-6', 4, 'I also stopped reaching for sugary snacks by noon', 'توقفت أيضاً عن تناول الوجبات الخفيفة السكرية عند الظهر.', null, '[{"en":"I","ar":"أنا"},{"en":"also","ar":"أيضاً"},{"en":"stopped","ar":"توقفت"},{"en":"reaching","ar":"عن تناول"},{"en":"for","ar":"عن"},{"en":"sugary","ar":"السكرية"},{"en":"snacks","ar":"الوجبات الخفيفة"},{"en":"by","ar":"عند"},{"en":"noon","ar":"الظهر"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-6-s6', 'normal-6', 5, 'My focus at work improved more than I expected', 'تحسّن تركيزي في العمل أكثر مما توقعت.', null, '[{"en":"My","ar":"لي"},{"en":"focus","ar":"تركيز"},{"en":"at","ar":"في"},{"en":"work","ar":"العمل"},{"en":"improved","ar":"تحسّن"},{"en":"more","ar":"أكثر"},{"en":"than","ar":"مما"},{"en":"I","ar":"أنا"},{"en":"expected","ar":"توقعت"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-6-s7', 'normal-6', 6, 'Some days I still forget, and that''s completely fine', 'في بعض الأيام أنسى ذلك، وهذا أمر طبيعي تماماً.', null, '[{"en":"Some","ar":"بعض"},{"en":"days","ar":"الأيام"},{"en":"I","ar":"أنا"},{"en":"still","ar":"ما زلت"},{"en":"forget,","ar":"أنسى،"},{"en":"and","ar":"و"},{"en":"that''s","ar":"هذا"},{"en":"completely","ar":"تماماً"},{"en":"fine","ar":"طبيعي"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-6-s8', 'normal-6', 7, 'Small habits, it turns out, add up over time', 'تبيّن أن العادات الصغيرة تتراكم مع الوقت.', null, '[{"en":"Small","ar":"الصغيرة"},{"en":"habits,","ar":"العادات،"},{"en":"it","ar":"هي"},{"en":"turns","ar":"تبيّن"},{"en":"out,","ar":"أنها،"},{"en":"add","ar":"تتراكم"},{"en":"up","ar":"فوق"},{"en":"over","ar":"مع"},{"en":"time","ar":"الوقت"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-6-s9', 'normal-6', 8, 'I''m not perfect at it, but I''ve definitely changed', 'لست مثالياً في ذلك، لكنني تغيرت بالتأكيد.', null, '[{"en":"I''m","ar":"أنا"},{"en":"not","ar":"لست"},{"en":"perfect","ar":"مثالياً"},{"en":"at","ar":"في"},{"en":"it,","ar":"ذلك،"},{"en":"but","ar":"لكن"},{"en":"I''ve","ar":"أنا"},{"en":"definitely","ar":"بالتأكيد"},{"en":"changed","ar":"تغيرت"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-7-s1', 'normal-7', 0, 'My roommate and I get along most of the time', 'أنا وزميل سكني ننسجم معظم الوقت.', null, '[{"en":"My","ar":"لي"},{"en":"roommate","ar":"زميل السكن"},{"en":"and","ar":"و"},{"en":"I","ar":"أنا"},{"en":"get","ar":"ننسجم"},{"en":"along","ar":"معاً"},{"en":"most","ar":"معظم"},{"en":"of","ar":"من"},{"en":"the","ar":"الـ"},{"en":"time","ar":"الوقت"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-7-s2', 'normal-7', 1, 'Lately, though, the kitchen has been a mess', 'لكن مؤخراً، أصبح المطبخ فوضوياً.', null, '[{"en":"Lately,","ar":"مؤخراً،"},{"en":"though,","ar":"لكن،"},{"en":"the","ar":"الـ"},{"en":"kitchen","ar":"المطبخ"},{"en":"has","ar":"قد"},{"en":"been","ar":"أصبح"},{"en":"a","ar":"واحداً"},{"en":"mess","ar":"فوضوياً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-7-s3', 'normal-7', 2, 'Dishes kept piling up in the sink for days', 'تراكمت الأطباق في الحوض لعدة أيام.', null, '[{"en":"Dishes","ar":"الأطباق"},{"en":"kept","ar":"ظلت"},{"en":"piling","ar":"تتراكم"},{"en":"up","ar":"فوق"},{"en":"in","ar":"في"},{"en":"the","ar":"الـ"},{"en":"sink","ar":"الحوض"},{"en":"for","ar":"لمدة"},{"en":"days","ar":"أيام"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-7-s4', 'normal-7', 3, 'I didn''t want to start an argument over something small', 'لم أرد أن أبدأ جدالاً حول أمر بسيط.', null, '[{"en":"I","ar":"أنا"},{"en":"didn''t","ar":"لم"},{"en":"want","ar":"أرد"},{"en":"to","ar":"أن"},{"en":"start","ar":"أبدأ"},{"en":"an","ar":"واحداً"},{"en":"argument","ar":"جدالاً"},{"en":"over","ar":"حول"},{"en":"something","ar":"أمر"},{"en":"small","ar":"بسيط"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-7-s5', 'normal-7', 4, 'Eventually, I decided to just bring it up calmly', 'في النهاية، قررت أن أطرح الموضوع بهدوء.', null, '[{"en":"Eventually,","ar":"في النهاية،"},{"en":"I","ar":"أنا"},{"en":"decided","ar":"قررت"},{"en":"to","ar":"أن"},{"en":"just","ar":"فقط"},{"en":"bring","ar":"أطرح"},{"en":"it","ar":"الموضوع"},{"en":"up","ar":"فوق"},{"en":"calmly","ar":"بهدوء"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-7-s6', 'normal-7', 5, 'He admitted he''d been overwhelmed with work lately', 'اعترف بأنه كان مرهقاً بسبب العمل مؤخراً.', null, '[{"en":"He","ar":"هو"},{"en":"admitted","ar":"اعترف"},{"en":"he''d","ar":"بأنه"},{"en":"been","ar":"كان"},{"en":"overwhelmed","ar":"مرهقاً"},{"en":"with","ar":"بسبب"},{"en":"work","ar":"العمل"},{"en":"lately","ar":"مؤخراً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-7-s7', 'normal-7', 6, 'We agreed on a simple cleaning schedule for the week', 'اتفقنا على جدول تنظيف بسيط للأسبوع.', null, '[{"en":"We","ar":"نحن"},{"en":"agreed","ar":"اتفقنا"},{"en":"on","ar":"على"},{"en":"a","ar":"واحد"},{"en":"simple","ar":"بسيط"},{"en":"cleaning","ar":"تنظيف"},{"en":"schedule","ar":"جدول"},{"en":"for","ar":"لـ"},{"en":"the","ar":"الـ"},{"en":"week","ar":"الأسبوع"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-7-s8', 'normal-7', 7, 'It felt awkward at first, but the talk actually helped', 'شعرت بالحرج في البداية، لكن الحديث ساعد فعلاً.', null, '[{"en":"It","ar":"ذلك"},{"en":"felt","ar":"بدا"},{"en":"awkward","ar":"محرجاً"},{"en":"at","ar":"في"},{"en":"first,","ar":"البداية،"},{"en":"but","ar":"لكن"},{"en":"the","ar":"الـ"},{"en":"talk","ar":"الحديث"},{"en":"actually","ar":"فعلاً"},{"en":"helped","ar":"ساعد"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-7-s9', 'normal-7', 8, 'Our apartment has felt a lot more peaceful ever since', 'أصبحت شقتنا أكثر هدوءاً بكثير منذ ذلك الحين.', null, '[{"en":"Our","ar":"لنا"},{"en":"apartment","ar":"الشقة"},{"en":"has","ar":"قد"},{"en":"felt","ar":"أصبحت"},{"en":"a","ar":"أكثر"},{"en":"lot","ar":"بكثير"},{"en":"more","ar":"أكثر"},{"en":"peaceful","ar":"هدوءاً"},{"en":"ever","ar":"منذ"},{"en":"since","ar":"ذلك الحين"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-9-s1', 'normal-9', 0, 'I found a jacket online for half the usual price', 'وجدت سترة على الإنترنت بنصف السعر المعتاد.', null, '[{"en":"I","ar":"أنا"},{"en":"found","ar":"وجدت"},{"en":"a","ar":"واحدة"},{"en":"jacket","ar":"سترة"},{"en":"online","ar":"على الإنترنت"},{"en":"for","ar":"بـ"},{"en":"half","ar":"نصف"},{"en":"the","ar":"الـ"},{"en":"usual","ar":"المعتاد"},{"en":"price","ar":"السعر"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-9-s2', 'normal-9', 1, 'The photos looked exactly like what I wanted', 'بدت الصور مطابقة تماماً لما أردته.', null, '[{"en":"The","ar":"الـ"},{"en":"photos","ar":"الصور"},{"en":"looked","ar":"بدت"},{"en":"exactly","ar":"تماماً"},{"en":"like","ar":"مثل"},{"en":"what","ar":"ما"},{"en":"I","ar":"أنا"},{"en":"wanted","ar":"أردته"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-9-s3', 'normal-9', 2, 'I clicked buy without reading the details carefully', 'ضغطت على "شراء" دون قراءة التفاصيل بعناية.', null, '[{"en":"I","ar":"أنا"},{"en":"clicked","ar":"ضغطت"},{"en":"buy","ar":"شراء"},{"en":"without","ar":"دون"},{"en":"reading","ar":"قراءة"},{"en":"the","ar":"الـ"},{"en":"details","ar":"التفاصيل"},{"en":"carefully","ar":"بعناية"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-9-s4', 'normal-9', 3, 'A week later, a package finally arrived at my door', 'بعد أسبوع، وصل الطرد أخيراً إلى بابي.', null, '[{"en":"A","ar":"واحد"},{"en":"week","ar":"أسبوع"},{"en":"later,","ar":"بعد،"},{"en":"a","ar":"واحد"},{"en":"package","ar":"طرد"},{"en":"finally","ar":"أخيراً"},{"en":"arrived","ar":"وصل"},{"en":"at","ar":"إلى"},{"en":"my","ar":"لي"},{"en":"door","ar":"بابي"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-9-s5', 'normal-9', 4, 'The jacket was two sizes too small', 'كانت السترة أصغر بمقاسين مما يجب.', null, '[{"en":"The","ar":"الـ"},{"en":"jacket","ar":"السترة"},{"en":"was","ar":"كانت"},{"en":"two","ar":"بمقاسين"},{"en":"sizes","ar":"مقاسات"},{"en":"too","ar":"جداً"},{"en":"small","ar":"صغيرة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-9-s6', 'normal-9', 5, 'I checked the website and found a return policy', 'تحققت من الموقع ووجدت سياسة إرجاع.', null, '[{"en":"I","ar":"أنا"},{"en":"checked","ar":"تحققت"},{"en":"the","ar":"الـ"},{"en":"website","ar":"الموقع"},{"en":"and","ar":"و"},{"en":"found","ar":"وجدت"},{"en":"a","ar":"واحدة"},{"en":"return","ar":"إرجاع"},{"en":"policy","ar":"سياسة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-9-s7', 'normal-9', 6, 'I filled out the form and shipped it back the same day', 'ملأت النموذج وأرسلتها في نفس اليوم.', null, '[{"en":"I","ar":"أنا"},{"en":"filled","ar":"ملأت"},{"en":"out","ar":"بالكامل"},{"en":"the","ar":"الـ"},{"en":"form","ar":"النموذج"},{"en":"and","ar":"و"},{"en":"shipped","ar":"أرسلت"},{"en":"it","ar":"ها"},{"en":"back","ar":"بالإعادة"},{"en":"the","ar":"بـ"},{"en":"same","ar":"نفس"},{"en":"day","ar":"اليوم"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-9-s8', 'normal-9', 7, 'Customer service refunded my money within a few days', 'استرد لي خدمة العملاء أموالي خلال أيام قليلة.', null, '[{"en":"Customer","ar":"خدمة"},{"en":"service","ar":"العملاء"},{"en":"refunded","ar":"استرد"},{"en":"my","ar":"لي"},{"en":"money","ar":"أموال"},{"en":"within","ar":"خلال"},{"en":"a","ar":"واحد"},{"en":"few","ar":"قليلة"},{"en":"days","ar":"أيام"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-9-s9', 'normal-9', 8, 'Now I always read the size chart before ordering anything', 'الآن أقرأ دائماً جدول المقاسات قبل طلب أي شيء.', null, '[{"en":"Now","ar":"الآن"},{"en":"I","ar":"أنا"},{"en":"always","ar":"دائماً"},{"en":"read","ar":"أقرأ"},{"en":"the","ar":"الـ"},{"en":"size","ar":"المقاس"},{"en":"chart","ar":"جدول"},{"en":"before","ar":"قبل"},{"en":"ordering","ar":"طلب"},{"en":"anything","ar":"أي شيء"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-8-s1', 'normal-8', 0, 'I''d been dreading this interview for nearly a week', 'كنت أخشى هذه المقابلة منذ ما يقارب أسبوعاً.', null, '[{"en":"I''d","ar":"كنت"},{"en":"been","ar":"قد"},{"en":"dreading","ar":"أخشى"},{"en":"this","ar":"هذه"},{"en":"interview","ar":"المقابلة"},{"en":"for","ar":"منذ"},{"en":"nearly","ar":"ما يقارب"},{"en":"a","ar":"واحد"},{"en":"week","ar":"أسبوعاً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-8-s2', 'normal-8', 1, 'Ten minutes before it started, the recruiter emailed to reschedule', 'قبل عشر دقائق من موعدها، راسلني المسؤول لتأجيلها.', null, '[{"en":"Ten","ar":"عشر"},{"en":"minutes","ar":"دقائق"},{"en":"before","ar":"قبل"},{"en":"it","ar":"هي"},{"en":"started,","ar":"بدأت،"},{"en":"the","ar":"الـ"},{"en":"recruiter","ar":"المسؤول"},{"en":"emailed","ar":"راسلني"},{"en":"to","ar":"لـ"},{"en":"reschedule","ar":"تأجيلها"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-8-s3', 'normal-8', 2, 'Part of me was relieved; another part was oddly disappointed', 'شعر جزء مني بالارتياح، بينما شعر جزء آخر بخيبة أمل غريبة.', null, '[{"en":"Part","ar":"جزء"},{"en":"of","ar":"من"},{"en":"me","ar":"مني"},{"en":"was","ar":"كان"},{"en":"relieved;","ar":"مرتاحاً؛"},{"en":"another","ar":"آخر"},{"en":"part","ar":"جزء"},{"en":"was","ar":"كان"},{"en":"oddly","ar":"بشكل غريب"},{"en":"disappointed","ar":"خائب الأمل"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-8-s4', 'normal-8', 3, 'I realized I''d been going through the motions rather than actually caring', 'أدركت أنني كنت أؤدي الأمر شكلياً دون أن أهتم فعلاً.', null, '[{"en":"I","ar":"أنا"},{"en":"realized","ar":"أدركت"},{"en":"I''d","ar":"أنني"},{"en":"been","ar":"كنت"},{"en":"going","ar":"أؤدي"},{"en":"through","ar":"خلال"},{"en":"the","ar":"الـ"},{"en":"motions","ar":"الحركات"},{"en":"rather","ar":"بدلاً"},{"en":"than","ar":"من"},{"en":"actually","ar":"أن"},{"en":"caring","ar":"أهتم فعلاً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-8-s5', 'normal-8', 4, 'That evening, I sat down and rewrote my entire resume', 'في تلك الأمسية، جلست وأعدت كتابة سيرتي الذاتية بالكامل.', null, '[{"en":"That","ar":"تلك"},{"en":"evening,","ar":"الأمسية،"},{"en":"I","ar":"أنا"},{"en":"sat","ar":"جلست"},{"en":"down","ar":"أسفل"},{"en":"and","ar":"و"},{"en":"rewrote","ar":"أعدت كتابة"},{"en":"my","ar":"لي"},{"en":"entire","ar":"بالكامل"},{"en":"resume","ar":"سيرتي الذاتية"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-8-s6', 'normal-8', 5, 'I stopped padding it with buzzwords and focused on what I''d actually built', 'توقفت عن حشوها بكلمات رنانة وركزت على ما بنيته فعلاً.', null, '[{"en":"I","ar":"أنا"},{"en":"stopped","ar":"توقفت"},{"en":"padding","ar":"حشو"},{"en":"it","ar":"ها"},{"en":"with","ar":"بـ"},{"en":"buzzwords","ar":"كلمات رنانة"},{"en":"and","ar":"و"},{"en":"focused","ar":"ركزت"},{"en":"on","ar":"على"},{"en":"what","ar":"ما"},{"en":"I''d","ar":"كنت"},{"en":"actually","ar":"فعلاً"},{"en":"built","ar":"بنيته"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-8-s7', 'normal-8', 6, 'When the interview finally happened, I felt oddly calm', 'عندما جرت المقابلة أخيراً، شعرت بهدوء غريب.', null, '[{"en":"When","ar":"عندما"},{"en":"the","ar":"الـ"},{"en":"interview","ar":"المقابلة"},{"en":"finally","ar":"أخيراً"},{"en":"happened,","ar":"جرت،"},{"en":"I","ar":"أنا"},{"en":"felt","ar":"شعرت"},{"en":"oddly","ar":"بشكل غريب"},{"en":"calm","ar":"بهدوء"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-8-s8', 'normal-8', 7, 'The recruiter said my answers stood out from everyone else''s', 'قال المسؤول إن إجاباتي تميّزت عن إجابات الجميع.', null, '[{"en":"The","ar":"الـ"},{"en":"recruiter","ar":"المسؤول"},{"en":"said","ar":"قال"},{"en":"my","ar":"لي"},{"en":"answers","ar":"إجاباتي"},{"en":"stood","ar":"تميّزت"},{"en":"out","ar":"بشدة"},{"en":"from","ar":"عن"},{"en":"everyone","ar":"الجميع"},{"en":"else''s","ar":"الآخرين"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-8-s9', 'normal-8', 8, 'Looking back, that last-minute delay turned out to be a gift', 'بالنظر إلى الوراء، تبيّن أن ذلك التأجيل المفاجئ كان نعمة.', null, '[{"en":"Looking","ar":"بالنظر"},{"en":"back,","ar":"إلى الوراء،"},{"en":"that","ar":"ذلك"},{"en":"last-minute","ar":"المفاجئ"},{"en":"delay","ar":"التأجيل"},{"en":"turned","ar":"تبيّن"},{"en":"out","ar":"أنه"},{"en":"to","ar":"أن"},{"en":"be","ar":"يكون"},{"en":"a","ar":"واحدة"},{"en":"gift","ar":"نعمة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-10-s1', 'normal-10', 0, 'We''d been close friends since university, practically inseparable', 'كنا أصدقاء مقربين منذ الجامعة، شبه متلازمين.', null, '[{"en":"We''d","ar":"كنا"},{"en":"been","ar":"قد"},{"en":"close","ar":"مقربين"},{"en":"friends","ar":"أصدقاء"},{"en":"since","ar":"منذ"},{"en":"university,","ar":"الجامعة،"},{"en":"practically","ar":"شبه"},{"en":"inseparable","ar":"متلازمين"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-10-s2', 'normal-10', 1, 'Somewhere along the way, we just stopped making time for each other', 'في مرحلة ما، توقفنا ببساطة عن تخصيص وقت لبعضنا.', null, '[{"en":"Somewhere","ar":"في مكان ما"},{"en":"along","ar":"على"},{"en":"the","ar":"الـ"},{"en":"way,","ar":"الطريق،"},{"en":"we","ar":"نحن"},{"en":"just","ar":"ببساطة"},{"en":"stopped","ar":"توقفنا"},{"en":"making","ar":"تخصيص"},{"en":"time","ar":"وقت"},{"en":"for","ar":"لـ"},{"en":"each","ar":"بعضنا"},{"en":"other","ar":"البعض"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-10-s3', 'normal-10', 2, 'A careless comment at a dinner party made things worse', 'جعل تعليق طائش في حفل عشاء الأمور أسوأ.', null, '[{"en":"A","ar":"واحد"},{"en":"careless","ar":"طائش"},{"en":"comment","ar":"تعليق"},{"en":"at","ar":"في"},{"en":"a","ar":"واحد"},{"en":"dinner","ar":"عشاء"},{"en":"party","ar":"حفل"},{"en":"made","ar":"جعل"},{"en":"things","ar":"الأمور"},{"en":"worse","ar":"أسوأ"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-10-s4', 'normal-10', 3, 'Neither of us apologized, and the silence dragged on for months', 'لم يعتذر أي منا، واستمر الصمت لأشهر.', null, '[{"en":"Neither","ar":"لا"},{"en":"of","ar":"من"},{"en":"us","ar":"منا"},{"en":"apologized,","ar":"اعتذر،"},{"en":"and","ar":"و"},{"en":"the","ar":"الـ"},{"en":"silence","ar":"الصمت"},{"en":"dragged","ar":"استمر"},{"en":"on","ar":"مستمراً"},{"en":"for","ar":"لمدة"},{"en":"months","ar":"أشهر"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-10-s5', 'normal-10', 4, 'I kept telling myself it wasn''t a big deal', 'ظللت أقنع نفسي بأن الأمر ليس بذلك السوء.', null, '[{"en":"I","ar":"أنا"},{"en":"kept","ar":"ظللت"},{"en":"telling","ar":"أقنع"},{"en":"myself","ar":"نفسي"},{"en":"it","ar":"بأن الأمر"},{"en":"wasn''t","ar":"ليس"},{"en":"a","ar":"أمراً"},{"en":"big","ar":"كبيراً"},{"en":"deal","ar":"شأناً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-10-s6', 'normal-10', 5, 'Deep down, though, I really missed having her around', 'لكن في أعماقي، اشتقت فعلاً لوجودها بجانبي.', null, '[{"en":"Deep","ar":"في"},{"en":"down,","ar":"الأعماق،"},{"en":"though,","ar":"لكن،"},{"en":"I","ar":"أنا"},{"en":"really","ar":"فعلاً"},{"en":"missed","ar":"اشتقت"},{"en":"having","ar":"لوجود"},{"en":"her","ar":"ها"},{"en":"around","ar":"بجانبي"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-10-s7', 'normal-10', 6, 'I finally sent a short message, just to check in', 'أرسلت أخيراً رسالة قصيرة، لمجرد الاطمئنان عليها.', null, '[{"en":"I","ar":"أنا"},{"en":"finally","ar":"أخيراً"},{"en":"sent","ar":"أرسلت"},{"en":"a","ar":"واحدة"},{"en":"short","ar":"قصيرة"},{"en":"message,","ar":"رسالة،"},{"en":"just","ar":"لمجرد"},{"en":"to","ar":"أن"},{"en":"check","ar":"أطمئن"},{"en":"in","ar":"عليها"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-10-s8', 'normal-10', 7, 'She replied almost instantly, as if she''d been waiting too', 'ردت على الفور تقريباً، وكأنها كانت تنتظر أيضاً.', null, '[{"en":"She","ar":"هي"},{"en":"replied","ar":"ردت"},{"en":"almost","ar":"تقريباً"},{"en":"instantly,","ar":"فوراً،"},{"en":"as","ar":"كأنها"},{"en":"if","ar":"لو"},{"en":"she''d","ar":"كانت"},{"en":"been","ar":"قد"},{"en":"waiting","ar":"تنتظر"},{"en":"too","ar":"أيضاً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-10-s9', 'normal-10', 8, 'We''re rebuilding things slowly, and honestly, that feels like enough', 'نعيد بناء العلاقة تدريجياً، وبصراحة، هذا يبدو كافياً.', null, '[{"en":"We''re","ar":"نحن"},{"en":"rebuilding","ar":"نعيد بناء"},{"en":"things","ar":"الأمور"},{"en":"slowly,","ar":"تدريجياً،"},{"en":"and","ar":"و"},{"en":"honestly,","ar":"بصراحة،"},{"en":"that","ar":"هذا"},{"en":"feels","ar":"يبدو"},{"en":"like","ar":"وكأنه"},{"en":"enough","ar":"كافياً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-11-s1', 'normal-11', 0, 'I started building the app just to kill time on weekends', 'بدأت ببناء التطبيق فقط لقتل الوقت في عطلات نهاية الأسبوع.', null, '[{"en":"I","ar":"أنا"},{"en":"started","ar":"بدأت"},{"en":"building","ar":"ببناء"},{"en":"the","ar":"الـ"},{"en":"app","ar":"التطبيق"},{"en":"just","ar":"فقط"},{"en":"to","ar":"لـ"},{"en":"kill","ar":"قتل"},{"en":"time","ar":"الوقت"},{"en":"on","ar":"في"},{"en":"weekends","ar":"عطلات نهاية الأسبوع"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-11-s2', 'normal-11', 1, 'A few months in, a stranger online offered to pay for it', 'بعد بضعة أشهر، عرض شخص غريب على الإنترنت أن يدفع مقابله.', null, '[{"en":"A","ar":"بعد"},{"en":"few","ar":"بضعة"},{"en":"months","ar":"أشهر"},{"en":"in,","ar":"فيها،"},{"en":"a","ar":"واحد"},{"en":"stranger","ar":"شخص غريب"},{"en":"online","ar":"على الإنترنت"},{"en":"offered","ar":"عرض"},{"en":"to","ar":"أن"},{"en":"pay","ar":"يدفع"},{"en":"for","ar":"مقابل"},{"en":"it","ar":"له"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-11-s3', 'normal-11', 2, 'I turned him down, half out of disbelief', 'رفضت عرضه، جزئياً بسبب عدم تصديقي.', null, '[{"en":"I","ar":"أنا"},{"en":"turned","ar":"رفضت"},{"en":"him","ar":"عرضه"},{"en":"down,","ar":"تماماً،"},{"en":"half","ar":"جزئياً"},{"en":"out","ar":"بسبب"},{"en":"of","ar":"عدم"},{"en":"disbelief","ar":"تصديقي"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-11-s4', 'normal-11', 3, 'Word spread, and suddenly I had a small waiting list of users', 'انتشر الخبر، وفجأة أصبح لدي قائمة انتظار صغيرة من المستخدمين.', null, '[{"en":"Word","ar":"الخبر"},{"en":"spread,","ar":"انتشر،"},{"en":"and","ar":"و"},{"en":"suddenly","ar":"فجأة"},{"en":"I","ar":"أنا"},{"en":"had","ar":"أصبح لدي"},{"en":"a","ar":"واحدة"},{"en":"small","ar":"صغيرة"},{"en":"waiting","ar":"انتظار"},{"en":"list","ar":"قائمة"},{"en":"of","ar":"من"},{"en":"users","ar":"المستخدمين"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-11-s5', 'normal-11', 4, 'Juggling it alongside my full-time job became genuinely exhausting', 'أصبحت الموازنة بينه وبين وظيفتي بدوام كامل مرهقة حقاً.', null, '[{"en":"Juggling","ar":"الموازنة"},{"en":"it","ar":"بينه"},{"en":"alongside","ar":"وبين"},{"en":"my","ar":"لي"},{"en":"full-time","ar":"بدوام كامل"},{"en":"job","ar":"وظيفتي"},{"en":"became","ar":"أصبح"},{"en":"genuinely","ar":"حقاً"},{"en":"exhausting","ar":"مرهقاً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-11-s6', 'normal-11', 5, 'I had to decide whether this was still just a hobby', 'اضطررت لأقرر ما إذا كان هذا لا يزال مجرد هواية.', null, '[{"en":"I","ar":"أنا"},{"en":"had","ar":"اضطررت"},{"en":"to","ar":"أن"},{"en":"decide","ar":"أقرر"},{"en":"whether","ar":"ما إذا"},{"en":"this","ar":"هذا"},{"en":"was","ar":"كان"},{"en":"still","ar":"لا يزال"},{"en":"just","ar":"مجرد"},{"en":"a","ar":"واحدة"},{"en":"hobby","ar":"هواية"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-11-s7', 'normal-11', 6, 'My manager, surprisingly, encouraged me to give it a real shot', 'شجعني مديري، بشكل مفاجئ، على تجربته بجدية.', null, '[{"en":"My","ar":"لي"},{"en":"manager,","ar":"مديري،"},{"en":"surprisingly,","ar":"بشكل مفاجئ،"},{"en":"encouraged","ar":"شجعني"},{"en":"me","ar":"لي"},{"en":"to","ar":"أن"},{"en":"give","ar":"أجرب"},{"en":"it","ar":"ه"},{"en":"a","ar":"واحدة"},{"en":"real","ar":"حقيقية"},{"en":"shot","ar":"فرصة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-11-s8', 'normal-11', 7, 'I negotiated fewer hours to finally focus on it properly', 'تفاوضت على ساعات عمل أقل لأتمكن أخيراً من التركيز عليه بشكل صحيح.', null, '[{"en":"I","ar":"أنا"},{"en":"negotiated","ar":"تفاوضت"},{"en":"fewer","ar":"أقل"},{"en":"hours","ar":"ساعات"},{"en":"to","ar":"لـ"},{"en":"finally","ar":"أخيراً"},{"en":"focus","ar":"التركيز"},{"en":"on","ar":"على"},{"en":"it","ar":"عليه"},{"en":"properly","ar":"بشكل صحيح"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-11-s9', 'normal-11', 8, 'Whether it succeeds or not, I don''t regret taking the leap', 'سواء نجح أم لا، لا أندم على خوض هذه المخاطرة.', null, '[{"en":"Whether","ar":"سواء"},{"en":"it","ar":"هو"},{"en":"succeeds","ar":"نجح"},{"en":"or","ar":"أم"},{"en":"not,","ar":"لا،"},{"en":"I","ar":"أنا"},{"en":"don''t","ar":"لا"},{"en":"regret","ar":"أندم"},{"en":"taking","ar":"خوض"},{"en":"the","ar":"الـ"},{"en":"leap","ar":"المخاطرة"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-12-s1', 'normal-12', 0, 'The job offer came with a catch: it was only for one year', 'جاء عرض العمل مع شرط: أنه لمدة عام واحد فقط.', null, '[{"en":"The","ar":"الـ"},{"en":"job","ar":"الوظيفة"},{"en":"offer","ar":"عرض"},{"en":"came","ar":"جاء"},{"en":"with","ar":"مع"},{"en":"a","ar":"واحد"},{"en":"catch:","ar":"شرط:"},{"en":"it","ar":"أنه"},{"en":"was","ar":"كان"},{"en":"only","ar":"فقط"},{"en":"for","ar":"لمدة"},{"en":"one","ar":"عام"},{"en":"year","ar":"واحد"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-12-s2', 'normal-12', 1, 'Everyone around me assumed I''d turn it down immediately', 'افترض الجميع من حولي أنني سأرفضه فوراً.', null, '[{"en":"Everyone","ar":"الجميع"},{"en":"around","ar":"حول"},{"en":"me","ar":"ي"},{"en":"assumed","ar":"افترض"},{"en":"I''d","ar":"أنني"},{"en":"turn","ar":"سأرفض"},{"en":"it","ar":"ه"},{"en":"down","ar":"تماماً"},{"en":"immediately","ar":"فوراً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-12-s3', 'normal-12', 2, 'Instead, I found myself seriously weighing the pros and cons', 'بدلاً من ذلك، وجدت نفسي أزن الإيجابيات والسلبيات بجدية.', null, '[{"en":"Instead,","ar":"بدلاً من ذلك،"},{"en":"I","ar":"أنا"},{"en":"found","ar":"وجدت"},{"en":"myself","ar":"نفسي"},{"en":"seriously","ar":"بجدية"},{"en":"weighing","ar":"أزن"},{"en":"the","ar":"الـ"},{"en":"pros","ar":"الإيجابيات"},{"en":"and","ar":"و"},{"en":"cons","ar":"السلبيات"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-12-s4', 'normal-12', 3, 'Leaving my apartment, my routine, and my friends felt daunting', 'بدا ترك شقتي وروتيني وأصدقائي أمراً مرهقاً.', null, '[{"en":"Leaving","ar":"ترك"},{"en":"my","ar":"لي"},{"en":"apartment,","ar":"شقتي،"},{"en":"my","ar":"لي"},{"en":"routine,","ar":"روتيني،"},{"en":"and","ar":"و"},{"en":"my","ar":"لي"},{"en":"friends","ar":"أصدقائي"},{"en":"felt","ar":"بدا"},{"en":"daunting","ar":"مرهقاً"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-12-s5', 'normal-12', 4, 'At the same time, staying felt like choosing comfort over growth', 'في الوقت نفسه، بدا البقاء وكأنه اختيار الراحة على النمو.', null, '[{"en":"At","ar":"في"},{"en":"the","ar":"الـ"},{"en":"same","ar":"نفس"},{"en":"time,","ar":"الوقت،"},{"en":"staying","ar":"البقاء"},{"en":"felt","ar":"بدا"},{"en":"like","ar":"وكأنه"},{"en":"choosing","ar":"اختيار"},{"en":"comfort","ar":"الراحة"},{"en":"over","ar":"على"},{"en":"growth","ar":"النمو"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-12-s6', 'normal-12', 5, 'I gave myself one week to decide, no more', 'منحت نفسي أسبوعاً واحداً لأقرر، لا أكثر.', null, '[{"en":"I","ar":"أنا"},{"en":"gave","ar":"منحت"},{"en":"myself","ar":"نفسي"},{"en":"one","ar":"واحداً"},{"en":"week","ar":"أسبوعاً"},{"en":"to","ar":"لـ"},{"en":"decide,","ar":"أقرر،"},{"en":"no","ar":"لا"},{"en":"more","ar":"أكثر"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-12-s7', 'normal-12', 6, 'In the end, uncertainty scared me less than regret did', 'في النهاية، أخافني الغموض أقل مما أخافني الندم.', null, '[{"en":"In","ar":"في"},{"en":"the","ar":"الـ"},{"en":"end,","ar":"النهاية،"},{"en":"uncertainty","ar":"الغموض"},{"en":"scared","ar":"أخافني"},{"en":"me","ar":"ني"},{"en":"less","ar":"أقل"},{"en":"than","ar":"مما"},{"en":"regret","ar":"الندم"},{"en":"did","ar":"فعل"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-12-s8', 'normal-12', 7, 'I signed the contract two days before the deadline', 'وقّعت العقد قبل يومين من الموعد النهائي.', null, '[{"en":"I","ar":"أنا"},{"en":"signed","ar":"وقّعت"},{"en":"the","ar":"الـ"},{"en":"contract","ar":"العقد"},{"en":"two","ar":"يومين"},{"en":"days","ar":"أيام"},{"en":"before","ar":"قبل"},{"en":"the","ar":"الـ"},{"en":"deadline","ar":"النهائي"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();
insert into sentences (id, lesson_id, order_index, en, ar, speaker, word_translations, updated_at) values ('normal-12-s9', 'normal-12', 8, 'Whatever happens after that year, I know I made the braver choice', 'مهما حدث بعد ذلك العام، أعلم أنني اتخذت الخيار الأكثر جرأة.', null, '[{"en":"Whatever","ar":"مهما"},{"en":"happens","ar":"حدث"},{"en":"after","ar":"بعد"},{"en":"that","ar":"ذلك"},{"en":"year,","ar":"العام،"},{"en":"I","ar":"أنا"},{"en":"know","ar":"أعلم"},{"en":"I","ar":"أنني"},{"en":"made","ar":"اتخذت"},{"en":"the","ar":"الـ"},{"en":"braver","ar":"الأكثر جرأة"},{"en":"choice","ar":"الخيار"}]'::jsonb, now()) on conflict (id) do update set order_index = excluded.order_index, en = excluded.en, ar = excluded.ar, speaker = excluded.speaker, word_translations = excluded.word_translations, updated_at = now();

-- Cleanup: these lessons previously had 12 sentences (order_index 0-11); remove the now-stale trailing three.
delete from sentences where lesson_id in ('normal-1', 'normal-2', 'normal-3', 'normal-4', 'normal-5', 'normal-6', 'normal-7', 'normal-8') and order_index >= 9;

commit;

-- Verification (run separately, after the transaction above has committed):
-- plain read-only SELECTs, no procedural code, safe to run any number of
-- times. Expected results are noted next to each one.

-- Expect exactly 12 rows.
select id, order_index, title, is_free, status
from lessons
where mode = 'normal'
  and id in (
    'normal-1', 'normal-2', 'normal-3', 'normal-4',
    'normal-5', 'normal-6', 'normal-7', 'normal-8',
    'normal-9', 'normal-10', 'normal-11', 'normal-12'
  )
order by order_index;

-- Expect exactly 12 rows, each with sentence_count = 9 (total 108).
select lesson_id, count(*) as sentence_count
from sentences
where lesson_id in (
    'normal-1', 'normal-2', 'normal-3', 'normal-4',
    'normal-5', 'normal-6', 'normal-7', 'normal-8',
    'normal-9', 'normal-10', 'normal-11', 'normal-12'
  )
group by lesson_id
order by lesson_id;
