-- Library expansion: 3 new books, diversifying away from the existing
-- 16 (which skew almost entirely self-development/psychology/
-- productivity, with Business empty and no history/big-picture
-- nonfiction). Applied to the live project via scripts/insert-books.ts;
-- captured here for tracking.
begin;

insert into categories (id, name, order_index, is_active) values ('category-history', 'History & Society', 7, true) on conflict (id) do nothing;

insert into books (id, title, author, description, difficulty_level, is_featured, is_free, status, order_index) values
  ('book-sapiens', 'Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 'An original SentenceStep summary exploring how Homo sapiens rose from an unremarkable ape to reshape the planet through shared myths, cooperation, and the revolutions in thinking, farming, and science that followed', 3, false, true, 'published', 16),
  ('book-cant-hurt-me', 'Can''t Hurt Me', 'David Goggins', 'An original SentenceStep summary of David Goggins'' account of transforming from an overweight, abused childhood into a Navy SEAL and ultra-endurance athlete through relentless mental toughness', 2, false, true, 'published', 17),
  ('book-zero-to-one', 'Zero to One', 'Peter Thiel', 'An original SentenceStep summary of Peter Thiel''s argument that true progress means creating something new rather than copying what already works, and how startups can build monopolies through unique value', 2, false, true, 'published', 18) on conflict (id) do nothing;

insert into book_categories (book_id, category_id, is_primary) values
  ('book-sapiens', 'category-history', true),
  ('book-sapiens', 'category-philosophy', false),
  ('book-cant-hurt-me', 'category-biography', true),
  ('book-cant-hurt-me', 'category-self-development', false),
  ('book-zero-to-one', 'category-business', true),
  ('book-zero-to-one', 'category-self-development', false) on conflict (book_id, category_id) do nothing;

insert into book_sections (id, book_id, order_index, title, description) values
  ('book-sapiens-sec1', 'book-sapiens', 1, 'An Unremarkable Ape', 'How Homo sapiens started out as just one modest species among several human relatives'),
  ('book-sapiens-sec2', 'book-sapiens', 2, 'The Cognitive Revolution', 'The sudden shift in thinking and language that set Sapiens apart from every other species'),
  ('book-sapiens-sec3', 'book-sapiens', 3, 'The Power of Shared Myths', 'Why money, nations, and corporations are all stories that exist only because people believe them'),
  ('book-sapiens-sec4', 'book-sapiens', 4, 'Bands to Villages', 'What everyday life actually looked like for tens of thousands of years of foraging'),
  ('book-sapiens-sec5', 'book-sapiens', 5, 'The Agricultural Trap', 'Why Harari calls the shift to farming history''s biggest fraud'),
  ('book-sapiens-sec6', 'book-sapiens', 6, 'Myths That Build Empires', 'How writing, hierarchy, and shared stories scaled cooperation up to entire empires'),
  ('book-sapiens-sec7', 'book-sapiens', 7, 'The Scientific Revolution', 'How admitting ignorance, backed by capital and empire, exploded human power'),
  ('book-sapiens-sec8', 'book-sapiens', 8, 'The Capitalist Engine', 'Why modern economies run on credit — a shared belief in tomorrow''s growth'),
  ('book-sapiens-sec9', 'book-sapiens', 9, 'Reshaping Life Itself', 'From muscle power to machines, and now to editing biology directly'),
  ('book-sapiens-sec10', 'book-sapiens', 10, 'Are We Happier', 'Harari''s closing question: has all this power actually made us happier'),
  ('book-cant-hurt-me-sec1', 'book-cant-hurt-me', 1, 'A Childhood Built on Fear', 'Growing up under an abusive father, poverty, and a severe stutter'),
  ('book-cant-hurt-me-sec2', 'book-cant-hurt-me', 2, 'The Overweight Recruit', 'The night a television segment about Navy SEALs changed everything'),
  ('book-cant-hurt-me-sec3', 'book-cant-hurt-me', 3, 'Losing a Hundred Pounds', 'Racing against the clock and his own body to qualify in time'),
  ('book-cant-hurt-me-sec4', 'book-cant-hurt-me', 4, 'Hell Week', 'Five days of continuous punishment, and the bell that ends it for those who quit'),
  ('book-cant-hurt-me-sec5', 'book-cant-hurt-me', 5, 'The 40% Rule', 'Goggins'' core idea: when your mind says you''re done, you''re really only 40% done'),
  ('book-cant-hurt-me-sec6', 'book-cant-hurt-me', 6, 'The Accountability Mirror', 'A daily ritual of brutal self-honesty, written down and faced every morning'),
  ('book-cant-hurt-me-sec7', 'book-cant-hurt-me', 7, 'Callousing the Mind', 'Building mental toughness on purpose, the same way skin calluses from friction'),
  ('book-cant-hurt-me-sec8', 'book-cant-hurt-me', 8, 'Becoming an Ultra-Endurance Athlete', 'From the military into ultra-marathons and a pull-up world record'),
  ('book-cant-hurt-me-sec9', 'book-cant-hurt-me', 9, 'Taking Souls', 'Turning other people''s doubt into fuel, and the philosophy readers take away'),
  ('book-zero-to-one-sec1', 'book-zero-to-one', 1, 'Copying Versus Creating', 'The difference between going from one to many and going from zero to one'),
  ('book-zero-to-one-sec2', 'book-zero-to-one', 2, 'The Myth of Competition', 'Why Thiel thinks competition is overrated and mostly destroys value'),
  ('book-zero-to-one-sec3', 'book-zero-to-one', 3, 'Why Monopolies Are Good', 'The difference between a destructive monopoly and a creative one'),
  ('book-zero-to-one-sec4', 'book-zero-to-one', 4, 'Escaping Competition', 'Starting small, dominating a niche, then expanding outward'),
  ('book-zero-to-one-sec5', 'book-zero-to-one', 5, 'The Power of Secrets', 'Why every great company is built around a truth almost no one else sees yet'),
  ('book-zero-to-one-sec6', 'book-zero-to-one', 6, 'Building for the Future', 'Definite optimism versus vague, indefinite drifting'),
  ('book-zero-to-one-sec7', 'book-zero-to-one', 7, 'The Founder''s Paradox', 'The unusual, even contradictory qualities that make founders effective'),
  ('book-zero-to-one-sec8', 'book-zero-to-one', 8, 'People Matter More Than Perks', 'Why a small, mission-aligned team beats a large disorganized one'),
  ('book-zero-to-one-sec9', 'book-zero-to-one', 9, 'The Question Every Founder Should Answer', 'Returning to Thiel''s opening question, and the challenge he leaves readers with') on conflict (id) do nothing;

insert into book_sentences (id, section_id, order_index, en) values
  ('book-sapiens-sec1-s1', 'book-sapiens-sec1', 1, 'Two hundred thousand years ago Homo sapiens was just one of several human species walking the earth'),
  ('book-sapiens-sec1-s2', 'book-sapiens-sec1', 2, 'Physically weaker than many predators our ancestors survived mostly through social cooperation'),
  ('book-sapiens-sec1-s3', 'book-sapiens-sec1', 3, 'Neanderthals were often stronger and had bigger brains yet they eventually disappeared'),
  ('book-sapiens-sec1-s4', 'book-sapiens-sec1', 4, 'For most of that early history humans occupied a modest middle place in the food chain'),
  ('book-sapiens-sec1-s5', 'book-sapiens-sec1', 5, 'Nothing about our biology alone explains why one particular ape species eventually dominated the planet'),
  ('book-sapiens-sec2-s1', 'book-sapiens-sec2', 1, 'Around seventy thousand years ago something shifted in how Sapiens thought and communicated'),
  ('book-sapiens-sec2-s2', 'book-sapiens-sec2', 2, 'New tools art and long-distance trade appeared in the archaeological record almost suddenly'),
  ('book-sapiens-sec2-s3', 'book-sapiens-sec2', 3, 'Language itself was not unique to humans but the content of that language changed everything'),
  ('book-sapiens-sec2-s4', 'book-sapiens-sec2', 4, 'Sapiens gained the rare ability to talk about things that do not physically exist at all'),
  ('book-sapiens-sec2-s5', 'book-sapiens-sec2', 5, 'That single ability to imagine fictions turned out to be the real turning point of the species'),
  ('book-sapiens-sec2-s6', 'book-sapiens-sec2', 6, 'Gossip and shared belief let far larger groups trust and organize with total strangers'),
  ('book-sapiens-sec3-s1', 'book-sapiens-sec3', 1, 'Money nations and corporations are all stories that exist only because enough people believe in them together'),
  ('book-sapiens-sec3-s2', 'book-sapiens-sec3', 2, 'A dollar bill has no real value on its own only the shared trust behind it'),
  ('book-sapiens-sec3-s3', 'book-sapiens-sec3', 3, 'These shared fictions let thousands of strangers cooperate toward a common goal without ever meeting'),
  ('book-sapiens-sec3-s4', 'book-sapiens-sec3', 4, 'No other animal on earth can organize flexibly around an idea that isn''t physically real'),
  ('book-sapiens-sec3-s5', 'book-sapiens-sec3', 5, 'Every large human institution from religion to law ultimately rests on this same kind of agreement'),
  ('book-sapiens-sec4-s1', 'book-sapiens-sec4', 1, 'For most of human history people lived in small foraging bands that moved with the seasons'),
  ('book-sapiens-sec4-s2', 'book-sapiens-sec4', 2, 'Hunter-gatherers often worked fewer hours and ate a more varied diet than early farmers did'),
  ('book-sapiens-sec4-s3', 'book-sapiens-sec4', 3, 'Knowledge in these bands was broad since survival depended on understanding the entire local environment'),
  ('book-sapiens-sec4-s4', 'book-sapiens-sec4', 4, 'Social bonds were tight because everyone''s cooperation was necessary for the group to survive'),
  ('book-sapiens-sec4-s5', 'book-sapiens-sec4', 5, 'This way of life shaped human bodies and minds for tens of thousands of years'),
  ('book-sapiens-sec5-s1', 'book-sapiens-sec5', 1, 'About twelve thousand years ago humans began domesticating wheat rice and other crops'),
  ('book-sapiens-sec5-s2', 'book-sapiens-sec5', 2, 'Farming produced more food per acre but often meant far harder and more repetitive labor'),
  ('book-sapiens-sec5-s3', 'book-sapiens-sec5', 3, 'Diets actually narrowed and health often declined as people depended on just a few crops'),
  ('book-sapiens-sec5-s4', 'book-sapiens-sec5', 4, 'Harari calls this shift history''s biggest fraud since it looked like progress but cost so much'),
  ('book-sapiens-sec5-s5', 'book-sapiens-sec5', 5, 'Once a population grew dependent on farming there was rarely any real way back'),
  ('book-sapiens-sec6-s1', 'book-sapiens-sec6', 1, 'Larger farming populations needed writing to record debts laws and harvests accurately'),
  ('book-sapiens-sec6-s2', 'book-sapiens-sec6', 2, 'Writing made complex bureaucracies and eventually entire empires possible for the first time'),
  ('book-sapiens-sec6-s3', 'book-sapiens-sec6', 3, 'Hierarchies of kings priests and social classes were justified through more shared stories'),
  ('book-sapiens-sec6-s4', 'book-sapiens-sec6', 4, 'Empires spread not only through force but by offering shared laws currency and identity'),
  ('book-sapiens-sec6-s5', 'book-sapiens-sec6', 5, 'Nearly every culture alive today is a descendant of some empire''s long-forgotten myths'),
  ('book-sapiens-sec7-s1', 'book-sapiens-sec7', 1, 'Around five hundred years ago European thinkers began admitting how much they did not yet know'),
  ('book-sapiens-sec7-s2', 'book-sapiens-sec7', 2, 'That admission of ignorance was the spark that launched modern science forward'),
  ('book-sapiens-sec7-s3', 'book-sapiens-sec7', 3, 'Governments and investors realized that funding discovery could produce real practical power'),
  ('book-sapiens-sec7-s4', 'book-sapiens-sec7', 4, 'Science capital and empire reinforced each other and accelerated at an unprecedented pace'),
  ('book-sapiens-sec7-s5', 'book-sapiens-sec7', 5, 'Within a few centuries humanity''s control over nature grew more than in all previous history'),
  ('book-sapiens-sec8-s1', 'book-sapiens-sec8', 1, 'Modern economies run on credit which is really just a shared belief in future growth'),
  ('book-sapiens-sec8-s2', 'book-sapiens-sec8', 2, 'Investors lend money today only because they trust the economy will be bigger tomorrow'),
  ('book-sapiens-sec8-s3', 'book-sapiens-sec8', 3, 'That trust fueled exploration invention and industry on a scale never seen before'),
  ('book-sapiens-sec8-s4', 'book-sapiens-sec8', 4, 'Growth became almost a religion of its own expected and demanded every single year'),
  ('book-sapiens-sec8-s5', 'book-sapiens-sec8', 5, 'Capitalism''s core promise is that tomorrow''s pie will always be larger than today''s'),
  ('book-sapiens-sec9-s1', 'book-sapiens-sec9', 1, 'Industrial technology moved humanity from muscle power to machines almost overnight'),
  ('book-sapiens-sec9-s2', 'book-sapiens-sec9', 2, 'Factories reorganized daily life around the clock rather than around the sun and seasons'),
  ('book-sapiens-sec9-s3', 'book-sapiens-sec9', 3, 'Modern science now edits genes extends lifespans and reshapes bodies directly'),
  ('book-sapiens-sec9-s4', 'book-sapiens-sec9', 4, 'Humans are no longer just changing their environment but starting to change biology itself'),
  ('book-sapiens-sec9-s5', 'book-sapiens-sec9', 5, 'The line between natural evolution and deliberate human design is growing thinner every year'),
  ('book-sapiens-sec10-s1', 'book-sapiens-sec10', 1, 'Humanity has more power wealth and knowledge today than at any point in its history'),
  ('book-sapiens-sec10-s2', 'book-sapiens-sec10', 2, 'Yet Harari asks whether any of this has reliably made individual people happier'),
  ('book-sapiens-sec10-s3', 'book-sapiens-sec10', 3, 'Stress anxiety and dissatisfaction remain common even in the wealthiest societies on earth'),
  ('book-sapiens-sec10-s4', 'book-sapiens-sec10', 4, 'Progress solved many old problems while quietly creating new ones nobody had chosen'),
  ('book-sapiens-sec10-s5', 'book-sapiens-sec10', 5, 'The book closes by asking what humanity actually wants to become next now that it finally can'),
  ('book-cant-hurt-me-sec1-s1', 'book-cant-hurt-me-sec1', 1, 'David Goggins grew up in a home ruled by his abusive and controlling father'),
  ('book-cant-hurt-me-sec1-s2', 'book-cant-hurt-me-sec1', 2, 'Poverty racism and a severe stutter made school feel like its own daily battle'),
  ('book-cant-hurt-me-sec1-s3', 'book-cant-hurt-me-sec1', 3, 'He struggled to read and was placed in special education classes throughout childhood'),
  ('book-cant-hurt-me-sec1-s4', 'book-cant-hurt-me-sec1', 4, 'His mother eventually gathered the courage to leave moving them to a safer town'),
  ('book-cant-hurt-me-sec1-s5', 'book-cant-hurt-me-sec1', 5, 'That escape gave him a chance at a normal life but left deep invisible scars'),
  ('book-cant-hurt-me-sec2-s1', 'book-cant-hurt-me-sec2', 1, 'Years later Goggins weighed nearly three hundred pounds and worked exterminating pests'),
  ('book-cant-hurt-me-sec2-s2', 'book-cant-hurt-me-sec2', 2, 'He felt directionless unhealthy and quietly ashamed of the life he had settled into'),
  ('book-cant-hurt-me-sec2-s3', 'book-cant-hurt-me-sec2', 3, 'One night he saw a television segment about Navy SEAL training and felt something shift'),
  ('book-cant-hurt-me-sec2-s4', 'book-cant-hurt-me-sec2', 4, 'He decided almost instantly that this impossible goal was exactly what he needed'),
  ('book-cant-hurt-me-sec2-s5', 'book-cant-hurt-me-sec2', 5, 'The Navy''s own recruiter told him he had only a few months to lose enough weight'),
  ('book-cant-hurt-me-sec3-s1', 'book-cant-hurt-me-sec3', 1, 'Goggins had roughly three months to lose over a hundred pounds to even qualify'),
  ('book-cant-hurt-me-sec3-s2', 'book-cant-hurt-me-sec3', 2, 'He trained obsessively swimming and running far more than his body was ready for'),
  ('book-cant-hurt-me-sec3-s3', 'book-cant-hurt-me-sec3', 3, 'Stress fractures in both legs threatened to end the attempt before it truly began'),
  ('book-cant-hurt-me-sec3-s4', 'book-cant-hurt-me-sec3', 4, 'He pushed forward anyway treating the pain as information rather than a stop sign'),
  ('book-cant-hurt-me-sec3-s5', 'book-cant-hurt-me-sec3', 5, 'Against nearly every expectation he made the required weight in time'),
  ('book-cant-hurt-me-sec4-s1', 'book-cant-hurt-me-sec4', 1, 'Navy SEAL training includes Hell Week five days of nearly continuous physical punishment'),
  ('book-cant-hurt-me-sec4-s2', 'book-cant-hurt-me-sec4', 2, 'A brass bell sits nearby that any recruit can ring at any moment to quit'),
  ('book-cant-hurt-me-sec4-s3', 'book-cant-hurt-me-sec4', 3, 'Goggins watched dozens of stronger looking recruits ring that bell around him'),
  ('book-cant-hurt-me-sec4-s4', 'book-cant-hurt-me-sec4', 4, 'He focused only on surviving the next few minutes rather than the entire week'),
  ('book-cant-hurt-me-sec4-s5', 'book-cant-hurt-me-sec4', 5, 'He completed Hell Week and would go on to complete it two more times in his life'),
  ('book-cant-hurt-me-sec5-s1', 'book-cant-hurt-me-sec5', 1, 'Goggins developed a personal theory he calls the 40 Percent Rule'),
  ('book-cant-hurt-me-sec5-s2', 'book-cant-hurt-me-sec5', 2, 'When your mind insists you are completely finished you have usually used only 40 percent of your ability'),
  ('book-cant-hurt-me-sec5-s3', 'book-cant-hurt-me-sec5', 3, 'The remaining 60 percent is hidden behind discomfort the brain tries to avoid'),
  ('book-cant-hurt-me-sec5-s4', 'book-cant-hurt-me-sec5', 4, 'Recognizing this gap became his method for pushing past what felt like a hard limit'),
  ('book-cant-hurt-me-sec5-s5', 'book-cant-hurt-me-sec5', 5, 'He argues most people quit long before their bodies actually run out of capacity'),
  ('book-cant-hurt-me-sec6-s1', 'book-cant-hurt-me-sec6', 1, 'Goggins created a practice he calls the Accountability Mirror for total self-honesty'),
  ('book-cant-hurt-me-sec6-s2', 'book-cant-hurt-me-sec6', 2, 'He wrote his weaknesses and goals on sticky notes stuck directly to his mirror'),
  ('book-cant-hurt-me-sec6-s3', 'book-cant-hurt-me-sec6', 3, 'Every morning he faced those notes instead of avoiding uncomfortable truths about himself'),
  ('book-cant-hurt-me-sec6-s4', 'book-cant-hurt-me-sec6', 4, 'This ritual replaced excuses with a clear specific plan for improvement'),
  ('book-cant-hurt-me-sec6-s5', 'book-cant-hurt-me-sec6', 5, 'He credits this daily honesty as the real engine behind his transformation'),
  ('book-cant-hurt-me-sec7-s1', 'book-cant-hurt-me-sec7', 1, 'Goggins compares mental toughness to a callus that forms only through repeated friction'),
  ('book-cant-hurt-me-sec7-s2', 'book-cant-hurt-me-sec7', 2, 'He deliberately sought out difficult uncomfortable challenges to build that toughness on purpose'),
  ('book-cant-hurt-me-sec7-s3', 'book-cant-hurt-me-sec7', 3, 'He describes a mental cookie jar of past hard moments he survived and overcame'),
  ('book-cant-hurt-me-sec7-s4', 'book-cant-hurt-me-sec7', 4, 'In new difficult moments he reaches back into that jar for proof he can endure'),
  ('book-cant-hurt-me-sec7-s5', 'book-cant-hurt-me-sec7', 5, 'Comfort he argues quietly weakens people while chosen difficulty strengthens them'),
  ('book-cant-hurt-me-sec8-s1', 'book-cant-hurt-me-sec8', 1, 'After the military Goggins turned to ultra-marathons some over a hundred miles long'),
  ('book-cant-hurt-me-sec8-s2', 'book-cant-hurt-me-sec8', 2, 'He often trained and competed while still recovering from serious injuries'),
  ('book-cant-hurt-me-sec8-s3', 'book-cant-hurt-me-sec8', 3, 'He broke the world record for pull-ups completed within twenty-four hours'),
  ('book-cant-hurt-me-sec8-s4', 'book-cant-hurt-me-sec8', 4, 'Each new extreme challenge became another test of the mindset he had built'),
  ('book-cant-hurt-me-sec8-s5', 'book-cant-hurt-me-sec8', 5, 'His body kept failing in small ways yet his will kept finding a way through'),
  ('book-cant-hurt-me-sec9-s1', 'book-cant-hurt-me-sec9', 1, 'Goggins uses the phrase taking souls to describe outworking people who underestimate him'),
  ('book-cant-hurt-me-sec9-s2', 'book-cant-hurt-me-sec9', 2, 'Other people''s doubt became fuel rather than discouragement throughout his story'),
  ('book-cant-hurt-me-sec9-s3', 'book-cant-hurt-me-sec9', 3, 'His core message is that most limits people accept are mental not truly physical'),
  ('book-cant-hurt-me-sec9-s4', 'book-cant-hurt-me-sec9', 4, 'He urges readers to stop negotiating with themselves during difficult moments'),
  ('book-cant-hurt-me-sec9-s5', 'book-cant-hurt-me-sec9', 5, 'Can''t Hurt Me ultimately argues that anyone can build extraordinary toughness through daily discipline'),
  ('book-zero-to-one-sec1-s1', 'book-zero-to-one-sec1', 1, 'Peter Thiel opens with a question he asks every job candidate about a truth few agree with him on'),
  ('book-zero-to-one-sec1-s2', 'book-zero-to-one-sec1', 2, 'He divides progress into two kinds going from one to many or from zero to one'),
  ('book-zero-to-one-sec1-s3', 'book-zero-to-one-sec1', 3, 'Copying an existing idea takes it from one to many spreading what already works'),
  ('book-zero-to-one-sec1-s4', 'book-zero-to-one-sec1', 4, 'Creating something genuinely new takes the world from zero to one for the first time'),
  ('book-zero-to-one-sec1-s5', 'book-zero-to-one-sec1', 5, 'Thiel argues real progress depends far more on the rarer zero to one kind of leap'),
  ('book-zero-to-one-sec2-s1', 'book-zero-to-one-sec2', 1, 'Business schools often praise competition as the engine that keeps companies sharp'),
  ('book-zero-to-one-sec2-s2', 'book-zero-to-one-sec2', 2, 'Thiel argues intense competition mostly destroys profits and distracts founders from real value'),
  ('book-zero-to-one-sec2-s3', 'book-zero-to-one-sec2', 3, 'Companies trapped in competition end up copying rivals instead of building something new'),
  ('book-zero-to-one-sec2-s4', 'book-zero-to-one-sec2', 4, 'He points to Silicon Valley successes that avoided direct competition almost entirely'),
  ('book-zero-to-one-sec2-s5', 'book-zero-to-one-sec2', 5, 'Chasing competitors in his view is usually a sign of a weak underlying business idea'),
  ('book-zero-to-one-sec3-s1', 'book-zero-to-one-sec3', 1, 'Thiel distinguishes between destructive monopolies and what he calls creative monopolies'),
  ('book-zero-to-one-sec3-s2', 'book-zero-to-one-sec3', 2, 'A creative monopoly earns its position by offering something genuinely better than any alternative'),
  ('book-zero-to-one-sec3-s3', 'book-zero-to-one-sec3', 3, 'Such companies can reinvest their profits into further innovation instead of price wars'),
  ('book-zero-to-one-sec3-s4', 'book-zero-to-one-sec3', 4, 'Perfectly competitive markets by contrast often leave no one with resources to innovate'),
  ('book-zero-to-one-sec3-s5', 'book-zero-to-one-sec3', 5, 'He argues every truly successful company is in some sense its own kind of monopoly'),
  ('book-zero-to-one-sec4-s1', 'book-zero-to-one-sec4', 1, 'Thiel recommends starting in a deliberately small specific market rather than a huge one'),
  ('book-zero-to-one-sec4-s2', 'book-zero-to-one-sec4', 2, 'A small market is easier to dominate completely before facing serious competition'),
  ('book-zero-to-one-sec4-s3', 'book-zero-to-one-sec4', 3, 'Once a company owns its small niche it can expand outward into adjacent markets'),
  ('book-zero-to-one-sec4-s4', 'book-zero-to-one-sec4', 4, 'He points to Amazon starting narrowly with books before expanding into nearly everything'),
  ('book-zero-to-one-sec4-s5', 'book-zero-to-one-sec4', 5, 'Trying to win a huge market immediately usually spreads a young company far too thin'),
  ('book-zero-to-one-sec5-s1', 'book-zero-to-one-sec5', 1, 'Thiel believes every great company is built around a secret almost no one else sees yet'),
  ('book-zero-to-one-sec5-s2', 'book-zero-to-one-sec5', 2, 'A secret here means an important truth that is hard to discover but not impossible'),
  ('book-zero-to-one-sec5-s3', 'book-zero-to-one-sec5', 3, 'Society often discourages this kind of contrarian thinking in favor of safe consensus'),
  ('book-zero-to-one-sec5-s4', 'book-zero-to-one-sec5', 4, 'Founders willing to search for overlooked secrets can find extraordinary opportunities'),
  ('book-zero-to-one-sec5-s5', 'book-zero-to-one-sec5', 5, 'He argues that believing few unclaimed secrets remain is itself a limiting belief'),
  ('book-zero-to-one-sec6-s1', 'book-zero-to-one-sec6', 1, 'Thiel contrasts definite thinking a clear vision of the future with vague indefinite drifting'),
  ('book-zero-to-one-sec6-s2', 'book-zero-to-one-sec6', 2, 'Definite optimism means believing the future can be better and planning specifically for it'),
  ('book-zero-to-one-sec6-s3', 'book-zero-to-one-sec6', 3, 'Many modern institutions default to indefinite plans hedging instead of truly committing'),
  ('book-zero-to-one-sec6-s4', 'book-zero-to-one-sec6', 4, 'He argues bold definite plans though riskier produce far more meaningful progress'),
  ('book-zero-to-one-sec6-s5', 'book-zero-to-one-sec6', 5, 'A startup in his view needs a specific concrete vision rather than a flexible vague one'),
  ('book-zero-to-one-sec7-s1', 'book-zero-to-one-sec7', 1, 'Thiel describes founders as often possessing unusual extreme even contradictory qualities'),
  ('book-zero-to-one-sec7-s2', 'book-zero-to-one-sec7', 2, 'The same intensity that drives extraordinary success can also alienate people around them'),
  ('book-zero-to-one-sec7-s3', 'book-zero-to-one-sec7', 3, 'History often treats such unusual founders with a strange mix of admiration and suspicion'),
  ('book-zero-to-one-sec7-s4', 'book-zero-to-one-sec7', 4, 'He argues boards and investors should protect founders rather than sanding down their edges'),
  ('book-zero-to-one-sec7-s5', 'book-zero-to-one-sec7', 5, 'Removing what makes a founder unusual can accidentally remove what makes them effective'),
  ('book-zero-to-one-sec8-s1', 'book-zero-to-one-sec8', 1, 'Thiel emphasizes hiring a small number of people fully committed to one shared mission'),
  ('book-zero-to-one-sec8-s2', 'book-zero-to-one-sec8', 2, 'He is skeptical of lavish office perks used to substitute for genuine purpose'),
  ('book-zero-to-one-sec8-s3', 'book-zero-to-one-sec8', 3, 'Every early employee in his view meaningfully shapes a young company''s culture'),
  ('book-zero-to-one-sec8-s4', 'book-zero-to-one-sec8', 4, 'He recommends hiring people who are genuinely excited by the specific mission itself'),
  ('book-zero-to-one-sec8-s5', 'book-zero-to-one-sec8', 5, 'A tightly aligned founding team can outperform a much larger disorganized one'),
  ('book-zero-to-one-sec9-s1', 'book-zero-to-one-sec9', 1, 'Thiel returns to his opening question about an important truth few people agree with you on'),
  ('book-zero-to-one-sec9-s2', 'book-zero-to-one-sec9', 2, 'Answering it honestly requires real independent thought rather than comfortable consensus'),
  ('book-zero-to-one-sec9-s3', 'book-zero-to-one-sec9', 3, 'He argues the best startups are built around convictions the rest of the world hasn''t seen yet'),
  ('book-zero-to-one-sec9-s4', 'book-zero-to-one-sec9', 4, 'Zero to One ultimately urges founders to imagine genuinely new futures not just copy the present'),
  ('book-zero-to-one-sec9-s5', 'book-zero-to-one-sec9', 5, 'The book closes by challenging readers to find their own overlooked zero to one idea') on conflict (id) do nothing;

commit;
